-- Create a new table called '[PAAE_TECNOLOGICO]' in schema '[dbo]'
-- Drop the table if it already exists
IF OBJECT_ID('[dbo].[PAAE_TECNOLOGICO]', 'U') IS NOT NULL
DROP TABLE [dbo].[PAAE_TECNOLOGICO]
GO
-- Create the table in the specified schema
CREATE TABLE [dbo].[PAAE_TECNOLOGICO]
(
    [PK_TECNOLOGICO] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY, -- Primary Key column
    [Nombre] NVARCHAR(50) NOT NULL,
    [Estado] NVARCHAR(50) NOT NULL,
    [Municipio] NVARCHAR(50) NOT NULL
);
GO

ALTER TABLE dbo.users ADD FK_TECNOLOGICO INT NULL;  

ALTER TABLE [dbo].[users]  WITH CHECK ADD  CONSTRAINT [users_fk_tecnologico_foreing] FOREIGN KEY([FK_TECNOLOGICO])
REFERENCES [dbo].[PAAE_TECNOLOGICO] ([PK_TECNOLOGICO])
GO
ALTER TABLE [dbo].[users] CHECK CONSTRAINT [users_fk_tecnologico_foreing]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAAE_PERIODO_SOLICITUD](
	[PK_PAAE_PERIODO] [int] IDENTITY(1,1) NOT NULL,
	[FECHA_INICIO] [date] NOT NULL,
	[FECHA_FIN] [date] NOT NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAAE_PERIODO_SOLICITUD] ADD PRIMARY KEY CLUSTERED 
(
	[PK_PAAE_PERIODO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAAE_PERIODO_SOLICITUD] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[PAAE_PERIODO_SOLICITUD] ADD  DEFAULT ('0') FOR [BORRADO]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATR_USER_ASESORIA_HORARIO](
	[PK_USER_ASESORIA_HORARIO] [int] IDENTITY(1,1) NOT NULL,
	[FK_USUARIO] INT NOT NULL,
	[MATERIA] NVARCHAR(50) NOT NULL,
	[DIA] NVARCHAR(12) NOT NULL,
	[HORA] NVARCHAR(20) NOT NULL,
  [PERIODO]  NVARCHAR(5) NOT NULL,
  [CAMPUS]  NVARCHAR(50) NOT NULL, 
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[STATUS] NVARCHAR(20) NOT NULL,
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_USER_ASESORIA_HORARIO] ADD PRIMARY KEY CLUSTERED 
(
	[PK_USER_ASESORIA_HORARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_USER_ASESORIA_HORARIO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[CATR_USER_ASESORIA_HORARIO]  WITH CHECK ADD CONSTRAINT [fk_user_solicitud] FOREIGN KEY([FK_USUARIO])
REFERENCES [dbo].[users] ([PK_USUARIO])
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATR_ASESOR_ASESORIA_HORARIO]
(
    [PK_ASESOR_ASESORIA_HORARIO] [int] IDENTITY(1,1) NOT NULL,
    [FK_USUARIO] INT NOT NULL,
    [MATERIA] NVARCHAR(50) NOT NULL,
    [MATERIA1] NVARCHAR(50) NOT NULL,
    [MATERIA2] NVARCHAR(50) NOT NULL,
    [DIA] NVARCHAR(12) NOT NULL,
    [HORA] NVARCHAR(20) NOT NULL,
    [PERIODO] NVARCHAR(5) NOT NULL,
    [CAMPUS] NVARCHAR(50) NOT NULL,
    [VALIDA] NVARCHAR(30) NOT NULL,
    [FECHA_REGISTRO] [datetime] NOT NULL,
	  [STATUS] NVARCHAR(20) NOT NULL

) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_ASESOR_ASESORIA_HORARIO] ADD PRIMARY KEY CLUSTERED 
(
	[PK_ASESOR_ASESORIA_HORARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_ASESOR_ASESORIA_HORARIO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[CATR_ASESOR_ASESORIA_HORARIO]  WITH CHECK ADD CONSTRAINT [fk_asesor_solicitud] FOREIGN KEY([FK_USUARIO])
REFERENCES [dbo].[users] ([PK_USUARIO])
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATR_ASESORIA_ACEPTADA]
(
    [PK_ASESORIA_ACEPTADA] [int] IDENTITY(1,1) NOT NULL,
    [FK_ASESOR] INT NOT NULL,
    [FK_ALUMNO] INT NOT NULL,
    [MATERIA] NVARCHAR(50) NOT NULL,
    [DIA] NVARCHAR(12) NOT NULL,
    [HORA] NVARCHAR(20) NOT NULL,
    [PERIODO] NVARCHAR(5) NOT NULL,
    [CAMPUS] NVARCHAR(50) NOT NULL,
    [ESPACIO] NVARCHAR(50) NOT NULL,
    [FECHA_REGISTRO] [datetime] NOT NULL,
	[STATUS] NVARCHAR(20) NOT NULL

) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_ASESORIA_ACEPTADA] ADD PRIMARY KEY CLUSTERED 
(
	[PK_ASESORIA_ACEPTADA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_ASESORIA_ACEPTADA] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO
ALTER TABLE [dbo].[CATR_ASESORIA_ACEPTADA]  WITH CHECK ADD CONSTRAINT [fk_asesor_asesoria] FOREIGN KEY([FK_ASESOR])
REFERENCES [dbo].[users] ([PK_USUARIO])
GO
ALTER TABLE [dbo].[CATR_ASESORIA_ACEPTADA]  WITH CHECK ADD CONSTRAINT [fk_alumno_asesoria] FOREIGN KEY([FK_ALUMNO])
REFERENCES [dbo].[users] ([PK_USUARIO])
GO

ALTER TABLE dbo.users ADD NUMERO_CONTROL NVARCHAR(8);

ALTER TABLE [SWIITL].[dbo].[users] ADD CLAVE_CARRERA NVARCHAR(10);

  ALTER TABLE [SWIITL].[dbo].[users] ADD SEMESTRE NVARCHAR(2);