CREATE TABLE CATR_ASPIRANTE (
    PK_ASPIRANTE INT IDENTITY(1,1) PRIMARY KEY,
    NUMERO_FICHA CHAR(4)
    );


CREATE TABLE PERIODO(
    PK_PERIODO INT IDENTITY(1,1) PRIMARY KEY,
    FECHA_PEDIODO DATETIME,
    FECHA_FIN DATETIME,
    NUMERO_FICHA NUMERIC(4)
);
Insert into PERIODO values ('12/12/12','12/12/12',0000)

CREATE TABLE PREFICHA(
    PK_PREFICHA INT IDENTITY(1,1) PRIMARY KEY,
    FK_PERIODO INT,
    NUMERO_FICHA CHAR(4)
);
ALTER TABLE PREFICHA ADD CONSTRAINT FK_PERIODO FOREIGN KEY (FK_PERIODO) REFERENCES PERIODO (PK_PERIODO);

CREATE TABLE FICHA(
    PK_FICHA CHAR(10) PRIMARY KEY,
    FK_PREFICHA INT
);
ALTER TABLE FICHA ADD CONSTRAINT FK_PREFICHA FOREIGN KEY (FK_PREFICHA) REFERENCES PREFICHA (PK_PREFICHA);


SELECT MAX( FK_PERIODO )  FROM PREFICHA

GO
CREATE PROCEDURE GENERAR_PREFICHA   
AS  
    --SELECT MAX( PK_PERIODO )  FROM PERIODO
    IF (SELECT MAX( PK_PERIODO )  FROM PERIODO) = (SELECT MAX( FK_PERIODO )  FROM PREFICHA)
        --PRINT 'Si existe el periodo.' 
        INSERT INTO PREFICHA (FK_PERIODO,NUMERO_FICHA) 
        SELECT MAX(FK_PERIODO), MAX(NUMERO_FICHA)+1 FROM PREFICHA WHERE FK_PERIODO = (SELECT MAX( PK_PERIODO )  FROM PERIODO);
    ELSE 
        --PRINT 'No existe el periodo.'
        INSERT INTO PREFICHA (FK_PERIODO,NUMERO_FICHA)
        SELECT MAX(PK_PERIODO), NUMERO_FICHA+1 FROM PERIODO WHERE PK_PERIODO = (SELECT MAX( PK_PERIODO )  FROM PERIODO)
        GROUP BY NUMERO_FICHA;
GO  

SELECT MAX( PK_PREFICHA )  FROM PREFICHA
SELECT FORMAT(GETDATE(),'yy') as fecha;
SELECT CONCAT('ITL',FORMAT(GETDATE(),'yy'),'-',1001);
SELECT PK_FICHA FROM FICHA;
SELECT RIGHT(PK_FICHA,4) FROM FICHA;
SELECT RIGHT(PK_FICHA,4) FROM FICHA WHERE RIGHT(PK_FICHA,4) BETWEEN '1001' AND '1999';



GO
CREATE PROCEDURE GENERAR_FICHA   
AS  
    --SELECT MAX( PK_PERIODO )  FROM PERIODO
    IF EXISTS (SELECT RIGHT(PK_FICHA,4) FROM FICHA WHERE RIGHT(PK_FICHA,4) BETWEEN '1001' AND '1999')
        --PRINT 'Si existe alguna ficha de sistemas.' 
        INSERT INTO FICHA (PK_FICHA,FK_PREFICHA)
        SELECT CONCAT('ITL',FORMAT(GETDATE(),'yy'),'-',MAX(RIGHT(PK_FICHA,4))+1), PK_PREFICHA  FROM FICHA, PREFICHA WHERE NUMERO_FICHA = 3006 AND RIGHT(PK_FICHA,4) BETWEEN '1001' AND '1999' 
        GROUP BY PK_PREFICHA;        
    ELSE 
        --PRINT 'Si no existe alguna ficha de sistemas.'
        INSERT INTO FICHA (PK_FICHA,FK_PREFICHA)
        SELECT CONCAT('ITL',FORMAT(GETDATE(),'yy'),'-',1001) AS PK_FICHA, PK_PREFICHA  FROM PREFICHA WHERE NUMERO_FICHA = 3006
        GROUP BY PK_PREFICHA;        
GO  GO
CREATE PROCEDURE GENERAR_PREFICHA   
AS  
    --SELECT MAX( PK_PERIODO )  FROM PERIODO
    IF (SELECT MAX( PK_PERIODO )  FROM PERIODO) = (SELECT MAX( FK_PERIODO )  FROM PREFICHA)
        --PRINT 'Si existe el periodo.' 
        INSERT INTO PREFICHA (FK_PERIODO,NUMERO_FICHA) 
        SELECT MAX(FK_PERIODO), MAX(NUMERO_FICHA)+1 FROM PREFICHA WHERE FK_PERIODO = (SELECT MAX( PK_PERIODO )  FROM PERIODO);
    ELSE 
        --PRINT 'No existe el periodo.'
        INSERT INTO PREFICHA (FK_PERIODO,NUMERO_FICHA)
        SELECT MAX(PK_PERIODO), NUMERO_FICHA+1 FROM PERIODO WHERE PK_PERIODO = (SELECT MAX( PK_PERIODO )  FROM PERIODO)
        GROUP BY NUMERO_FICHA;
GO  


use SWIITL
GO
CREATE PROCEDURE GENERAR_PREFICHA   
AS        
    IF (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS) = (SELECT MAX( FK_PERIODO )  FROM CATR_ASPIRANTE)
        BEGIN
        IF ((SELECT LEN (NUMERO_PREFICHA) FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( FK_PERIODO )  FROM CATR_ASPIRANTE))=1)
            SELECT MAX(FK_PERIODO) as FK_PERIODO,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'000',NUMERO_PREFICHA+1) as PREFICHA,
            MAX(NUMERO_PREFICHA)+1 as NUMERO_PREFICHA FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHA;
        ELSE IF ((SELECT LEN (NUMERO_PREFICHA) FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( FK_PERIODO )  FROM CATR_ASPIRANTE))=2)
            SELECT MAX(FK_PERIODO) as FK_PERIODO,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'00',NUMERO_PREFICHA+1) as PREFICHA,
            MAX(NUMERO_PREFICHA)+1 as NUMERO_PREFICHA FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHA;
        ELSE IF ((SELECT LEN (NUMERO_PREFICHA) FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( FK_PERIODO )  FROM CATR_ASPIRANTE))=3)
            SELECT MAX(FK_PERIODO) as FK_PERIODO,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'0',NUMERO_PREFICHA+1) as PREFICHA,
            MAX(NUMERO_PREFICHA)+1 as NUMERO_PREFICHA FROM CATR_ASPIRANTE WHERE FK_PERIODO = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHA;
        END
    ELSE 
        BEGIN
        IF ((SELECT LEN (NUMERO_PREFICHAS) FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS))=1)
            SELECT MAX(PK_PERIODO_PREFICHAS) as PK_PERIODO_PREFICHAS,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'000',NUMERO_PREFICHAS+1) as PREFICHA,
            NUMERO_PREFICHAS+1 as NUMERO_PREFICHAS FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHAS;
        ELSE IF ((SELECT LEN (NUMERO_PREFICHAS) FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS))=2)
            SELECT MAX(PK_PERIODO_PREFICHAS) as PK_PERIODO_PREFICHAS,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'00',NUMERO_PREFICHAS+1) as PREFICHA,
            NUMERO_PREFICHAS+1 as NUMERO_PREFICHAS FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHAS;
        ELSE IF ((SELECT LEN (NUMERO_PREFICHAS) FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS))=3)
            SELECT MAX(PK_PERIODO_PREFICHAS) as PK_PERIODO_PREFICHAS,
            CONCAT('TL',FORMAT(GETDATE(),'yy'),'0',NUMERO_PREFICHAS+1) as PREFICHA,
            NUMERO_PREFICHAS+1 as NUMERO_PREFICHAS FROM CAT_PERIODO_PREFICHAS WHERE PK_PERIODO_PREFICHAS = (SELECT MAX( PK_PERIODO_PREFICHAS )  FROM CAT_PERIODO_PREFICHAS)
            GROUP BY NUMERO_PREFICHAS;
        END
GO  

        SELECT LEN('Hola') as hola

drop PROCEDURE  GENERAR_PREFICHA   

exec GENERAR_PREFICHA

INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Soltero / Soltera', 1);
INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Casado / Casada', 1);
INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Viudo / Viuda', 1);
INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Divorciado / Divorciada', 1);
INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Concubino / Concubina', 1);
INSERT INTO CAT_ESTADO_CIVIL (NOMBRE,ESTADO) VALUES ('Comprometido / Comprometida', 1);


INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Papá', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Mamá', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Padres', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Tutor', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Familiar', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE,ESTADO) VALUES ('Nadie', 1);


INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Fórum educativo', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Visitaron mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Visite las instalaciones con mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Visite las instalaciones por mi cuenta', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Grupo deportivo', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Grupo cultural/artístico', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Curso de idioma', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Otro tipo de curso', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un familiar', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un familiar egresado del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un amigo o conocido', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un amigo o conocido egresado del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un docente de mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Recomendación de un docente del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Decisión de mis padres', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Facebook', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Twitter', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Folleto', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Internet', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Radio', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Periódico', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Televisión', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE,ESTADO) VALUES ('Por su ubicación', 1);


INSERT INTO CAT_INCAPACIDAD (NOMBRE,ESTADO) VALUES ('Visual', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE,ESTADO) VALUES ('Motriz', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE,ESTADO) VALUES ('Auditiva', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE,ESTADO) VALUES ('Otra', 1);


INSERT INTO CAT_AREA_ACADEMICA (NOMBRE,ESTADO) VALUES ('Ingeniería Industrial', 1);
INSERT INTO CAT_AREA_ACADEMICA (NOMBRE,ESTADO) VALUES ('Ciencias Económico Administrativas', 1);
INSERT INTO CAT_AREA_ACADEMICA (NOMBRE,ESTADO) VALUES ('Metalmecánica', 1);
INSERT INTO CAT_AREA_ACADEMICA (NOMBRE,ESTADO) VALUES ('Sistemas y Computación', 1);


INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IEME-2010-210', 'Ingeniería Electromecánica Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Metalmecánica';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IELC-2010-211', 'Ingeniería Electrónica Campus II', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Metalmecánica';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'ISIC-2010-224', 'Ingeniería en Sistemas Computacionales Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Sistemas y Computación';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'ITIC-2010-225', 'Ingeniería en Tecnologías de la Información y Comunicaciones Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Sistemas y Computación';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IIND-2010-227', 'Ingeniería Industrial Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Ingeniería Industrial';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IMCT-2010-229', 'Ingeniería Mecatrónica Campus II', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Metalmecánica';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IGEM-2009-201', 'Ingeniería en Gestión Empresarial Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Ciencias Económico Administrativas';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'IGEM-2009-201', 'Ingeniería en Gestión Empresarial Campus II', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Ciencias Económico Administrativas';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'ILOG-2009-202', 'Ingeniería en Logística Campus I', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Ingeniería Industrial';
INSERT INTO CATR_CARRERA (CLAVE,NOMBRE,ESTADO,FK_AREA_ACADEMICA) SELECT 'ILOG-2009-202', 'Ingeniería en Logística Campus II', 1, PK_AREA_ACADEMICA FROM CAT_AREA_ACADEMICA WHERE NOMBRE = 'Ingeniería Industrial';







