/* DATOS PARA ROL DE TOMA DE ASISTENCIA */

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA) VALUES
(
    (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE ABREVIATURA = 'SIT'),
    'Capturista',
    'CAP_TUT'
);

INSERT INTO PER_CAT_MODULO(NOMBRE, ORDEN, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Asistencia',
    1,
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'toma_asistencia_conferencias')), 3, 32 )),
    N'Para módulo de toma de asistencia a conferencias',
    'toma_asistencia_conferencias'
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES(
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'CAP_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'toma_asistencia_conferencias')
);

/* CAMBIOS EN APLICACION DE ENCUESTAS */
DROP VIEW IF EXISTS VIEW_LISTA_ENCUESTAS;
DROP VIEW IF EXISTS VW_LISTA_ENCUESTAS;
CREATE VIEW VW_LISTA_ENCUESTAS AS
SELECT
    -- DATOS DE LA ENCUESTA
    CAT_ENCUESTA.PK_ENCUESTA,
    CAT_ENCUESTA.NOMBRE,

    -- DATOS DE LA APLICACION
    TR_APLICACION_ENCUESTA.FECHA_APLICACION,
    TR_APLICACION_ENCUESTA.PERIODO,

    -- DATOS DE APLICACION DETALLE
    TR_APLICACION_ENCUESTA_DETALLE.PK_APLICACION_ENCUESTA_DETALLE,
    TR_APLICACION_ENCUESTA_DETALLE.FK_USUARIO,
    TR_APLICACION_ENCUESTA_DETALLE.FECHA_RESPUESTA,
    TR_APLICACION_ENCUESTA_DETALLE.ESTADO AS ESTADO_APLICACION
FROM
    TR_APLICACION_ENCUESTA_DETALLE
        LEFT JOIN TR_APLICACION_ENCUESTA
                  ON TR_APLICACION_ENCUESTA_DETALLE.FK_APLICACION_ENCUESTA = TR_APLICACION_ENCUESTA.PK_APLICACION
        LEFT JOIN CAT_ENCUESTA
                  ON TR_APLICACION_ENCUESTA.FK_ENCUESTA = CAT_ENCUESTA.PK_ENCUESTA
;
