/*********************  INICIO MODIFICACIONES PUESTA EN PRODUCCIÓN (14-08-2019)  *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      OK
 * PRUEBAS:    OK
 * PRODUCCIÓN: OK
*/

/* ****************************************************** *
 * ********** ELIMINACIÓN DE TABLAS DE ENCUESTAS ******** *
 * ****************************************************** */
DROP TABLE IF EXISTS TR_APLICACION_ENCUESTA;
DROP TABLE IF EXISTS TR_RESPUESTA_USUARIO_ENCUESTA;
DROP TABLE IF EXISTS CAT_RESPUESTA_POSIBLE;
DROP TABLE IF EXISTS CAT_PREGUNTA;
DROP TABLE IF EXISTS CAT_TIPO_PREGUNTA;
DROP TABLE IF EXISTS CAT_SECCION;
DROP TABLE IF EXISTS CAT_ENCUESTA;

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE ENCUESTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA ENCUESTAS */
CREATE TABLE CAT_ENCUESTA
(
    PK_ENCUESTA             INT          NOT NULL IDENTITY (1,1),

    NOMBRE                  VARCHAR(100) NOT NULL,
    OBJETIVO                TEXT,
    INSTRUCCIONES           TEXT,
    FUENTE_CITA             TEXT,
    ES_ADMINISTRABLE        SMALLINT     NOT NULL DEFAULT 1, -- Sí de administrable
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_ENCUESTA
    ADD CONSTRAINT PRK_ENCUESTA_CAT_ENCUESTA PRIMARY KEY (PK_ENCUESTA ASC);
/* FIN TABLA PARA ENCUESTAS */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE SECCIONES ******** *
 * *************************************************** */

/* INICIO TABLA PARA SECCIONES */
CREATE TABLE CAT_SECCION
(
    PK_SECCION              INT          NOT NULL IDENTITY (1,1),
    FK_ENCUESTA             INT,

    NOMBRE                  VARCHAR(100) NOT NULL,
    NUMERO                  INT          NOT NULL,
    ORDEN                   SMALLINT     NOT NULL DEFAULT 1,
    OBJETIVO                TEXT                  DEFAULT NULL,
    INSTRUCCIONES           TEXT                  DEFAULT NULL,
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_SECCION
    ADD CONSTRAINT PRK_SECCION_CAT_SECCION PRIMARY KEY (PK_SECCION ASC);
ALTER TABLE CAT_SECCION
    ADD CONSTRAINT FRK_ENCUESTA_CAT_SECCION FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA)
/* FIN TABLA PARA SECCIONES */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE TIPOS DE PREGUNTA ******** *
 * *************************************************** */

/* INICIO TABLA PARA TIPOS DE PREGUNTA */
CREATE TABLE CAT_TIPO_PREGUNTA
(
    PK_TIPO_PREGUNTA        INT          NOT NULL IDENTITY (1,1),

    NOMBRE_TIPO_PREGUNTA    VARCHAR(100) NOT NULL,
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_TIPO_PREGUNTA
    ADD CONSTRAINT PRK_TIPO_PREGUNTA_CAT_TIPO_PREGUNTA PRIMARY KEY (PK_TIPO_PREGUNTA ASC);
/* FIN TABLA PARA TIPOS DE PREGUNTA */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE PREGUNTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA PREGUNTAS */
CREATE TABLE CAT_PREGUNTA
(
    PK_PREGUNTA             INT          NOT NULL IDENTITY (1,1),
    FK_TIPO_PREGUNTA        INT,
    FK_SECCION              INT,

    ORDEN                   INT          NOT NULL,
    PLANTEAMIENTO           VARCHAR(300) NOT NULL,
    TEXTO_GUIA              VARCHAR(100) NOT NULL,
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_PREGUNTA
    ADD CONSTRAINT PRK_PREGUNTA_CAT_PREGUNTA PRIMARY KEY (PK_PREGUNTA ASC);
ALTER TABLE CAT_PREGUNTA
    ADD CONSTRAINT FRK_TIPO_PREGUNTA_CAT_PREGUNTA FOREIGN KEY (FK_TIPO_PREGUNTA) REFERENCES CAT_TIPO_PREGUNTA (PK_TIPO_PREGUNTA);
ALTER TABLE CAT_PREGUNTA
    ADD CONSTRAINT FRK_SECCION_CAT_PREGUNTA FOREIGN KEY (FK_SECCION) REFERENCES CAT_SECCION (PK_SECCION);
/* FIN TABLA PARA PREGUNTAS */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE POSIBLES RESPUESTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA POSIBLES RESPUESTAS */
CREATE TABLE CAT_RESPUESTA_POSIBLE
(
    PK_RESPUESTA_POSIBLE    INT      NOT NULL IDENTITY (1,1),
    FK_PREGUNTA             INT,

    RESPUESTA               NVARCHAR(255),
    VALOR_NUMERICO          INT               DEFAULT NULL,
    MINIMO                  INT               DEFAULT NULL,
    MAXIMO                  INT               DEFAULT NULL,
    ORDEN                   INT               DEFAULT 1,
    ESTADO                  SMALLINT NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT NOT NULL DEFAULT 0
);

ALTER TABLE CAT_RESPUESTA_POSIBLE
    ADD CONSTRAINT PRK_RESPUESTA_POSIBLE_CAT_RESPUESTA_POSIBLE PRIMARY KEY (PK_RESPUESTA_POSIBLE ASC);
ALTER TABLE CAT_RESPUESTA_POSIBLE
    ADD CONSTRAINT FRK_PREGUNTA_CAT_RESPUESTA_POSIBLE FOREIGN KEY (FK_PREGUNTA) REFERENCES CAT_PREGUNTA (PK_PREGUNTA);
/* FIN TABLA PARA POSIBLES RESPUESTAS */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE APLICACIÓN ENCUESTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA APLICACIÓN DE ENCUESTAS */
CREATE TABLE TR_APLICACION_ENCUESTA
(
    PK_APLICACION_ENCUESTA  INT      NOT NULL IDENTITY (1,1),
    FK_USUARIO              INT,
    FK_ENCUESTA             INT,

    FECHA_APLICACION        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_RESPUESTA         DATETIME          DEFAULT NULL,
    ESTADO                  SMALLINT NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT NOT NULL DEFAULT 0
);

ALTER TABLE TR_APLICACION_ENCUESTA
    ADD CONSTRAINT PRK_APLICACION_ENCUESTA_TR_APLICACION_ENCUESTA PRIMARY KEY (PK_APLICACION_ENCUESTA ASC);

ALTER TABLE TR_APLICACION_ENCUESTA
    ADD CONSTRAINT FRK_USUARIO_TR_APLICACION_ENCUESTA FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO (PK_USUARIO);

ALTER TABLE TR_APLICACION_ENCUESTA
    ADD CONSTRAINT FRK_ENCUESTA_TR_APLICACION_ENCUESTA FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA);
/* INICIO TABLA PARA APLICACIÓN DE ENCUESTAS */

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE RESPUESTA DE ENCUESTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA RESPUESTA DE ENCUESTAS */
CREATE TABLE TR_RESPUESTA_USUARIO_ENCUESTA
(
    PK_RESPUESTA_USUARIO_ENCUESTA INT      NOT NULL IDENTITY (1,1),
    FK_RESPUESTA_POSIBLE          INT      NOT NULL,
    FK_APLICACION_ENCUESTA        INT      NOT NULL,

    RESPUESTA_ABIERTA             TEXT              DEFAULT NULL,
    ESTADO                        SMALLINT NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO           INT,
    FECHA_REGISTRO                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION       INT,
    FECHA_MODIFICACION            DATETIME,
    BORRADO                       SMALLINT NOT NULL DEFAULT 0
);

ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ADD CONSTRAINT PRK_RESPUESTA_USUARIO_ENCUESTA_TR_RESPUESTA_USUARIO_ENCUESTA PRIMARY KEY (PK_RESPUESTA_USUARIO_ENCUESTA ASC);

ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ADD CONSTRAINT FRK_RESPUESTA_POSIBLE_TR_RESPUESTA_USUARIO_ENCUESTA FOREIGN KEY (FK_RESPUESTA_POSIBLE) REFERENCES CAT_RESPUESTA_POSIBLE (PK_RESPUESTA_POSIBLE);

ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ADD CONSTRAINT FRK_APLICACION_ENCUESTA_TR_RESPUESTA_USUARIO_ENCUESTA FOREIGN KEY (FK_APLICACION_ENCUESTA) REFERENCES TR_APLICACION_ENCUESTA (PK_APLICACION_ENCUESTA);

/* FIN TABLA PARA RESPUESTA DE ENCUESTAS */

/* *************************************************** *
 * ********** MODIFICACION DE TABLAS ******** *
 * *************************************************** */
ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ADD ORDEN SMALLINT DEFAULT NULL;

ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ADD RANGO SMALLINT DEFAULT NULL;

ALTER TABLE CAT_RESPUESTA_POSIBLE
    ADD ES_MIXTA SMALLINT DEFAULT 0;


/*********************  FIN MODIFICACIONES PUESTA EN PRODUCCIÓN (14-08-2019) *********************************/

-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------

/*********************  INICIO MODIFICACIONES VISTA DE TUTORES (25-08-2019)  *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      OK
 * PRUEBAS:    OK
 * PRODUCCIÓN: OK
*/

/* AGREGANDO PERIODO EN APLICACIÓN DE ENCUESTA */
ALTER TABLE TR_APLICACION_ENCUESTA
    ADD PERIODO NVARCHAR(5) NULL;

/* INICIO TABLA PARA GRUPO DE TUTORIAS */
CREATE TABLE TR_GRUPO_TUTORIA
(
    PK_GRUPO_TUTORIA        INT          NOT NULL IDENTITY (1,1),
    FK_CARRERA              INT          NOT NULL,
    FK_USUARIO              INT          NOT NULL,           -- ES EL TUTOR

    PERIODO                 NVARCHAR(5)  NOT NULL,
    CLAVE                   NVARCHAR(10) NOT NULL,
    TIPO_GRUPO              SMALLINT     NOT NULL, -- 1 PARA TUTORIA INICIAL, 2 PARA TUTORIA DE SEGUIMIENTO
    EVALUACION              SMALLINT     NOT NULL DEFAULT 0, -- CUANDO EL TUTOR EVALÚA AL GRUPO
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE TR_GRUPO_TUTORIA
    ADD CONSTRAINT PRK_GRUPO_TUTORIA_TR_GRUPO_TUTORIA PRIMARY KEY (PK_GRUPO_TUTORIA ASC);

ALTER TABLE TR_GRUPO_TUTORIA
    ADD CONSTRAINT FRK_CARRERA_TR_GRUPO_TUTORIA FOREIGN KEY (FK_CARRERA) REFERENCES CAT_CARRERA (PK_CARRERA);

ALTER TABLE TR_GRUPO_TUTORIA
    ADD CONSTRAINT FRK_USUARIO_TR_GRUPO_TUTORIA FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO (PK_USUARIO);

/* FIN TABLA PARA GRUPO DE TUTORIAS */

/* INICIO TABLA PARA DETALLE GRUPO DE TUTORIAS */
CREATE TABLE TR_GRUPO_TUTORIA_DETALLE
(
    PK_GRUPO_TUTORIA_DETALLE        INT          NOT NULL IDENTITY (1,1),
    FK_GRUPO              INT          NOT NULL,
    FK_USUARIO              INT          NOT NULL,           -- ES CADA UNO DE LOS ALUMNOS

    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE TR_GRUPO_TUTORIA_DETALLE
    ADD CONSTRAINT PRK_GRUPO_TUTORIA_DETALLE_TR_GRUPO_TUTORIA_DETALLE PRIMARY KEY (PK_GRUPO_TUTORIA_DETALLE ASC);

ALTER TABLE TR_GRUPO_TUTORIA_DETALLE
    ADD CONSTRAINT FRK_GRUPO_TR_GRUPO_TUTORIA_DETALLE FOREIGN KEY (FK_GRUPO) REFERENCES TR_GRUPO_TUTORIA (PK_GRUPO_TUTORIA);

ALTER TABLE TR_GRUPO_TUTORIA_DETALLE
    ADD CONSTRAINT FRK_USUARIO_TR_GRUPO_TUTORIA_DETALLE FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO (PK_USUARIO);

/* FIN TABLA PARA DETALLE GRUPO DE TUTORIAS */

/*********************  FIN INICIO MODIFICACIONES VISTA DE TUTORES (25-08-2019) *********************************/

-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------

