/* CAMBIOS EN APLICACION DE ENCUESTAS */
DROP VIEW IF EXISTS VIEW_LISTA_ENCUESTAS;
DROP VIEW IF EXISTS VW_LISTA_ENCUESTAS;
CREATE VIEW VW_LISTA_ENCUESTAS AS
SELECT
    -- DATOS DE LA ENCUESTA
    CAT_ENCUESTA.PK_ENCUESTA,
    CAT_ENCUESTA.NOMBRE,

    -- DATOS DE LA APLICACION
    TR_APLICACION_ENCUESTA.FECHA_APLICACION,
    TR_APLICACION_ENCUESTA.PERIODO,

    -- DATOS DE APLICACION DETALLE
    TR_APLICACION_ENCUESTA_DETALLE.PK_APLICACION_ENCUESTA_DETALLE,
    TR_APLICACION_ENCUESTA_DETALLE.FK_USUARIO,
    TR_APLICACION_ENCUESTA_DETALLE.FECHA_RESPUESTA,
    TR_APLICACION_ENCUESTA_DETALLE.ESTADO AS ESTADO_APLICACION
FROM
    TR_APLICACION_ENCUESTA_DETALLE
        LEFT JOIN TR_APLICACION_ENCUESTA
                  ON TR_APLICACION_ENCUESTA_DETALLE.FK_APLICACION_ENCUESTA = TR_APLICACION_ENCUESTA.PK_APLICACION
        LEFT JOIN CAT_ENCUESTA
                  ON TR_APLICACION_ENCUESTA.FK_ENCUESTA = CAT_ENCUESTA.PK_ENCUESTA
;
