/* CAMBIOS PARA ADMNISTRAR COORDINADORES DEPARTAMENTALES */
-- BUSCAR CONSTRAINT
ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    DROP CONSTRAINT DF__TR_RESPUE__RESPU__336AA144;

ALTER TABLE TR_RESPUESTA_USUARIO_ENCUESTA
    ALTER COLUMN RESPUESTA_ABIERTA NVARCHAR(500) NULL
;

/* INICIO TABLA PARA COORDINADORES DE TUTORIAS */
CREATE TABLE TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
(
    PK_COORDINADOR          INT      NOT NULL IDENTITY (1,1),
    FK_USUARIO              INT      NOT NULL,
    FK_AREA_ACADEMICA       INT      NOT NULL,

    ESTADO                  SMALLINT NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT NOT NULL DEFAULT 0
);

ALTER TABLE TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
    ADD CONSTRAINT PRK_COORDINADOR_TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
        PRIMARY KEY (PK_COORDINADOR ASC);

ALTER TABLE TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
    ADD CONSTRAINT FRK_USUARIO_TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
        FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO (PK_USUARIO);

ALTER TABLE TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
    ADD CONSTRAINT FRK_DEPARTAMENTO_TR_COORDINADOR_DEPARTAMENTAL_TUTORIA
        FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA (PK_AREA_ACADEMICA);
/* FIN TABLA PARA COORDINADORES DE TUTORIAS */

-- REGISTRO DE ROLES
INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (1, 'Coordinador departamental', 'COORD_TUT');

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (1, 'Coordinador institucional', 'COORI_TUT');

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (1, 'Administrador', 'ADM_TUT');

 -- REGISTRO DE MÓDULOS
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Coordinadores institucionales', 1, 1);

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Coordinadores departamentales', 1, 1);

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Datos tutor', 1, 1);

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Usuarios', 1, 1);

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Horario', 1, 3);

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)
VALUES ('Seguimiento académico', 1, 4);

-- ASIGNACIÓN DE MÓDULOS A ROLES
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Datos tutor')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Horario')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Seguimiento académico')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'ADM_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Grupos')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORI_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Grupos')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'ADM_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Coordinadores institucionales')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'ADM_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Usuarios')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'ADM_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Coordinadores departamentales')
);

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (
   (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORI_TUT'),
   (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Coordinadores departamentales')
);


/* ************************ *
    * PRODUCCIÓN: PENDIENTE *
 * ************************ */

/* ASIGNACIÓN DE ROL A ADMINISTRADOR */
-- SIIA: 1501 NOMBRE: MARÍA ELENA	MARTINEZ	HERNÁNDEZ
INSERT INTO PER_TR_ROL_USUARIO(FK_ROL, FK_USUARIO)
VALUES (5, (SELECT PK_USUARIO FROM CAT_USUARIO WHERE NUMERO_CONTROL = '1501'));

UPDATE PER_CAT_SISTEMA SET NOMBRE = 'Tutorías' WHERE NOMBRE = 'tutorias';

UPDATE PER_CAT_MODULO SET NOMBRE = 'Grupos actuales' WHERE NOMBRE = 'Grupos';

-- MÓDULO DE HISTÓRICO DE GRUPOS DE UN TUTOR
INSERT INTO PER_CAT_MODULO(NOMBRE, ORDEN, RUTA, RUTA_MD5, DESCRIPCION)
    VALUES ('Histórico grupos', 2, 'historico_grupos_tutor', 'e150022cbe6813b2d7efe161c9641e93',
            'Histórico de grupos de un tutor');

 -- -----------------------------------------
-- CAMBIOS PARA MÓDULO DE JORNDAS --
-- -----------------------------------------

/* INICIO TABLA PARA JORNADAS */
CREATE TABLE CAT_JORNADA
(
    PK_JORNADA              INT          NOT NULL IDENTITY (1,1),

    TEMA                    VARCHAR(100) NOT NULL,
    FECHA                   DATE         NOT NULL,
    LUGAR                   VARCHAR(30)  NOT NULL,
    DESCRIPCION             TEXT         NOT NULL,
    NOMBRE_EXPOSITOR        VARCHAR(50)  NOT NULL,
    CURRICULUM_EXPOSITOR    TEXT         NULL,
    ESTADO                  SMALLINT     NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_JORNADA
    ADD CONSTRAINT PRK_JORNADA_CAT_JORNADA PRIMARY KEY (PK_JORNADA ASC);
/* FIN TABLA PARA JORNADAS */


/* CAMBIOS EN APLICACIÓN DE ENCUESTAS */
/* Se crea la tabla que define los diferentes tipos de aplicación, 'CAT_TIPO_APLICACION' */
DROP TABLE IF EXISTS CAT_TIPO_APLICACION;
CREATE TABLE CAT_TIPO_APLICACION(
                                    PK_TIPO_APLICACION     INT             NOT NULL IDENTITY (1,1),
                                    NOMBRE                 VARCHAR(50)     NOT NULL
);

ALTER TABLE CAT_TIPO_APLICACION
    ADD CONSTRAINT PRK_TIPO_APLICACION_CAT_TIPO_APLICACION PRIMARY KEY (PK_TIPO_APLICACION ASC);

INSERT INTO CAT_TIPO_APLICACION (NOMBRE)
VALUES ('Institucional'), ('Carrera'), ('Semestre'), ('Grupo'), ('Individual');

SELECT * FROM CAT_TIPO_APLICACION;

/* Modificar 'TR_APLICACION_ENCUESTA' para hacer uso de 'CAT_APLICACION' */

ALTER TABLE TR_APLICACION_ENCUESTA
    ADD FK_TIPO_APLICACION INT NULL;

ALTER TABLE TR_APLICACION_ENCUESTA
    ADD CONSTRAINT FRK_TIPO_APLICACION_TR_APLICACION_ENCUESTA
        FOREIGN KEY (FK_TIPO_APLICACION) REFERENCES CAT_TIPO_APLICACION (PK_TIPO_APLICACION);

ALTER TABLE TR_APLICACION_ENCUESTA ADD APLICACION_SEMESTRE NVARCHAR(2) NULL;
ALTER TABLE TR_APLICACION_ENCUESTA ADD APLICACION_FK_CARRERA INT NULL;
ALTER TABLE TR_APLICACION_ENCUESTA ADD APLICACION_NUMERO_CONTROL INT NULL;

SELECT * FROM TR_APLICACION_ENCUESTA;

INSERT INTO TR_APLICACION_ENCUESTA(FK_USUARIO, FK_ENCUESTA, FK_TIPO_APLICACION, APLICACION_SEMESTRE, FECHA_APLICACION)
VALUES(1,1,3,9,GETDATE());


SELECT * FROM CAT_ENCUESTA

ALTER TABLE TR_APLICACION_ENCUESTA DROP COLUMN APLICACION_NUMERO_CONTROL;

UPDATE TR_APLICACION_ENCUESTA
SET FK_TIPO_APLICACION = 5
WHERE FK_TIPO_APLICACION IS NULL

SELECT * FROM CAT_USUARIO WHERE PK_USUARIO = 60;

DROP TABLE IF EXISTS RESPUESTA_ENCUESTA;
CREATE TABLE RESPUESTA_ENCUESTA(
                                   PK_RESPUESTA_ENCUESTA INT NOT NULL IDENTITY (1,1),
                                   FK_APLICACION INT,
                                   FK_USUARIO INT,
                                   FECHA_RESPUESTA DATETIME,
);

ALTER TABLE RESPUESTA_ENCUESTA
    ADD CONSTRAINT PRK_RESPUESTA_ENCUESTA_RESPUESTA_ENCUESTA PRIMARY KEY (PK_RESPUESTA_ENCUESTA ASC);

ALTER TABLE RESPUESTA_ENCUESTA
    ADD CONSTRAINT FRK_APLICACION_RESPUESTA_ENCUESTA
        FOREIGN KEY (FK_APLICACION) REFERENCES TR_APLICACION_ENCUESTA(PK_APLICACION_ENCUESTA);

ALTER TABLE RESPUESTA_ENCUESTA
    ADD CONSTRAINT FRK_USUARIO_RESPUESTA_ENCUESTA
        FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO(PK_USUARIO);
