/* ROL ESTUDIANTE */
INSERT INTO PER_CAT_ROL (FK_SISTEMA, NOMBRE, ABREVIATURA) VALUES (
    (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE ABREVIATURA = 'SIT'),
    N'Estudiante',
    N'EST_TUT'
);

/* modulo ENCUESTAS DE ALUMNO */
INSERT INTO PER_CAT_MODULO(NOMBRE, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Encuestas',
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'encuestas_alumno')), 3, 32 )),
    N'Listado de encuestas, rol alumno',
    'encuestas_alumno'
);

/* relacion rol modulo */
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'encuestas_alumno')
);

/* acciones */
INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'encuestas_alumno'),
    'VER_ENCUESTAS'
);

INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'encuestas_alumno'),
    'RESPONDER_ENCUESTA'
);

INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'encuestas_alumno'),
    'VER_REPORTE'
);

/* permisos */
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_ENCUESTAS')
);
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'RESPONDER_ENCUESTA')
);
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_REPORTE')
);










/* modulo DATOS DEL TUTOR */
INSERT INTO PER_CAT_MODULO(NOMBRE, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Datos tutor',
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'datos_tutor')), 3, 32 )),
    N'Datos del tutor del alumno',
    'datos_tutor'
);

/* relacion rol modulo */
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'datos_tutor')
);

/* acciones */
INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'datos_tutor'),
    'VER_DATOS_TUTOR'
);

/* permisos */
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_DATOS_TUTOR')
);










/* modulo HORARIO */
INSERT INTO PER_CAT_MODULO(NOMBRE, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Mi horario',
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'horario')), 3, 32 )),
    N'Horario del alumno, vista de alumno',
    'horario'
);

/* relacion rol modulo */
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'horario')
);

/* acciones */
INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'horario'),
    'VER_HORARIO'
);

/* permisos */
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_HORARIO')
);





/* modulo SEGUIMIENTO ACADEMICO */
INSERT INTO PER_CAT_MODULO(NOMBRE, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Seguimiento',
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'seguimiento_academico')), 3, 32 )),
    N'Seguimiento académico del alumno, vista de alumno',
    'seguimiento_academico'
);

/* relacion rol modulo */
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'seguimiento_academico')
);

/* acciones */
INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'seguimiento_academico'),
    'VER_SEGUIMIENTO_ACADEMICO'
);

/* permisos */
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'EST_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_SEGUIMIENTO_ACADEMICO')
);



