/* ROL CAPTURISTA */
INSERT INTO PER_CAT_ROL (FK_SISTEMA, NOMBRE, ABREVIATURA) VALUES (
    (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE ABREVIATURA = 'SIT'),
    N'Capturista',
    N'CAP_TUT'
);

/* modulo CAPTURISTA */
INSERT INTO PER_CAT_MODULO(NOMBRE, RUTA_MD5, DESCRIPCION, RUTA) VALUES
(
    'Asistencia jornadas',
    (SELECT SUBSTRING(master.dbo.fn_varbintohexstr(HashBytes('MD5', 'toma_asistencia_conferencias')), 3, 32 )),
    N'Módulo de toma de asistencia a conferencias',
    'toma_asistencia_conferencias'
);

/* relacion rol modulo */
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'CAP_TUT'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'toma_asistencia_conferencias')
);

/* acciones */
INSERT INTO PER_CAT_ACCION(FK_MODULO, CLAVE_ACCION) VALUES
(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'toma_asistencia_conferencias'),
    'VER_JORNADAS_ASIGNADAS'
),
(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'toma_asistencia_conferencias'),
    'VER_DETALLE_JORNADA'
),
(
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA = 'toma_asistencia_conferencias'),
    'TOMAR_ASISTENCIA'
)
;

/* permisos */
INSERT INTO PER_TR_PERMISO(FK_ROL, FK_ACCION) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'CAP_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_JORNADAS_ASIGNADAS')
),
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'CAP_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'VER_DETALLE_JORNADA')
),
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'CAP_TUT'),
    (SELECT PK_ACCION FROM PER_CAT_ACCION WHERE CLAVE_ACCION = 'TOMAR_ASISTENCIA')
);






