/* CAMBIOS PARA COMPLETAR PERFIL */
CREATE TABLE CAT_SITUACION_RESIDENCIA
(
    PK_SITUACION_RESIDENCIA INT IDENTITY PRIMARY KEY,
    NOMBRE                  NVARCHAR(100) NOT NULL,
    ESTADO                  SMALLINT      NOT NULL DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT      NOT NULL DEFAULT 0,
);

-- BUSCAR NOMBRE DE CONSTRAINT
ALTER TABLE CAT_USUARIO
    DROP CONSTRAINT DF__CAT_USUAR__SITUA__3335971A;

ALTER TABLE CAT_USUARIO
    DROP COLUMN SITUACION_RESIDENCIA;

ALTER TABLE CAT_USUARIO
    ADD FK_SITUACION_RESIDENCIA INT NULL;

ALTER TABLE CAT_USUARIO
    ADD CONSTRAINT FRK_SITUACION_RESIDENCIA_CAT_USUARIO
        FOREIGN KEY (FK_SITUACION_RESIDENCIA) REFERENCES CAT_SITUACION_RESIDENCIA (PK_SITUACION_RESIDENCIA);


INSERT INTO CAT_SITUACION_RESIDENCIA(NOMBRE) VALUES
('Vivo en León'),
('Soy foráneo. Me traslado todos los días'),
('Soy foráneo. Por el estudio vivo en León')
;

ALTER TABLE CAT_USUARIO
    DROP CONSTRAINT DF__CAT_USUARI__SEXO__2180FB33;

ALTER TABLE CAT_USUARIO ALTER COLUMN SEXO INT NULL;

-- COLUMNA AREA ACADEMICA PARA USUARIOS ADMINISTRATIVOS Y DOCENTES
ALTER TABLE CAT_USUARIO
    ADD FK_AREA_ACADEMICA INT NULL;

ALTER TABLE CAT_USUARIO
    ADD CONSTRAINT FRK_AREA_ACADEMICA_CAT_USUARIO
        FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA (PK_AREA_ACADEMICA);

/* ***************************************** *
   ***** CAMBIOS PENDIENTES EN SERVIDOR **** *
 * ***************************************** */
-- AGREGAR CAMPO PARA FOTO DE PERFIL
ALTER TABLE CAT_USUARIO
    ADD FOTO_PERFIL NVARCHAR(250) NULL;
