/* ***************************************** *
   ***** CAMBIOS PENDIENTES EN SERVIDOR **** *
 * ***************************************** */

ALTER TABLE CAT_COLONIA
ALTER COLUMN FK_TIPO_ASENTAMIENTO INT NULL;

/* PARA ALUMNOS CON NUMERO DE CONTROL CON LETRA INICIAL EJ: M10420419*/
ALTER TABLE CAT_USUARIO ALTER COLUMN NUMERO_CONTROL NVARCHAR(9) NULL;
