use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

/* INICIO REGISTROS PROVISIONALES SIIA */
/*INSERT INTO SIIA(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, NUMERO_CONTORL, CLAVE_CARRERA, FECHA_INGRESO, SEMESTRE, ESTADO, MOTIVO)
VALUES('MIGUEL ANGEL', 'PEÑA', 'LOPEZ', '10420419', 'ISX', '2013-08-19 00:00:00.000', 19, 'BD', 'Concluir Creditos Carrera');*/
/* FIN REGISTROS PROVISIONALES SIIA */

/* INICIO REGISTROS DEL CATÁLOGO DE CARRERAS */
INSERT INTO CAT_CARRERA(NOMBRE, ABREVIATURA, CLAVE_TECNM, CLAVE_TECLEON, CLAVE_CARRERA) VALUES
('INGENIERÍA ELECTRÓNICA',                                       'ELX', 'IELC-2010-211', 'ELX', 5191),
('INGENIERÍA ELECTROMECÁNICA',                                   'EMX', 'IEME-2010-210', 'EMX', 5189),
('INGENIERÍA EN GESTIÓN EMPRESARIAL',                            'GE9', 'IGEM-2009-201', 'GE9', 6157),
('INGENIERÍA INDUSTRIAL',                                        'IIX', 'IIND-2010-227', 'IIX', 5190),
('INGENIERÍA EN SISTEMAS COMPUTACIONALES',                       'ISX', 'ISIC-2010-224', 'ISX', 5188),
('INGENIERÍA EN LOGÍSTICA',                                      'LOX', 'ILOG-2009-202', 'LOX', 5997),
('INGENIERÍA MECATRÓNICA',                                       'MCX', 'IMCT-2010-229', 'MCX', 6628),
('INGENIERÍA EN TECNOLOGÍAS DE LA INFORMACIÓN Y COMUNICACIONES', 'TIX', 'ITIC-2010-225', 'TIX', 5192);
/* FIN REGISTROS DEL CATÁLOGO DE CARRERAS */


/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
