INSERT INTO CAT_CIUDAD (NOMBRE, FK_ENTIDAD_FEDERATIVA) VALUES
('Abalá', 31),
('Abasolo', 5),
('Abasolo', 28),
('Abasolo', 19),
('Abasolo', 11),
('Abejones', 20),
('Acacoyagua', 7),
('Acajete', 30),
('Acajete', 21),
('Acala', 7),
('Acámbaro', 11),
('Acambay de Ruíz Castañeda', 15),
('Acanceh', 31),
('Acapetahua', 7),
('Acaponeta', 18),
('Acapulco de Juárez', 12),
('Acateno', 21),
('Acatepec', 12),
('Acatic', 14),
('Acatlán', 21),
('Acatlán', 30),
('Acatlán', 13),
('Acatlán de Juárez', 14),
('Acatlán de Pérez Figueroa', 20),
('Acatzingo', 21),
('Acaxochitlán', 13),
('Acayucan', 30),
('Acolman', 15),
('Aconchi', 26),
('Acteopan', 21),
('Actopan', 30),
('Actopan', 13),
('Acuamanala de Miguel Hidalgo', 29),
('Acuitzio', 16),
('Acula', 30),
('Aculco', 15),
('Acultzingo', 30),
('Acuña', 5),
('Agua Blanca de Iturbide', 13),
('Agua Dulce', 30),
('Agua Prieta', 26),
('Agualeguas', 19),
('Aguascalientes', 1),
('Aguililla', 16),
('Ahome', 25),
('Ahuacatlán', 18),
('Ahuacatlán', 21),
('Ahuacuotzingo', 12),
('Ahualulco', 24),
('Ahualulco de Mercado', 14),
('Ahuatlán', 21),
('Ahuazotepec', 21),
('Ahuehuetitla', 21),
('Ahumada', 8),
('Ajacuba', 13),
('Ajalpan', 21),
('Ajuchitlán del Progreso', 12),
('Akil', 31),
('Álamo Temapache', 30),
('Alamos', 26),
('Alaquines', 24),
('Albino Zertuche', 21),
('Alcozauca de Guerrero', 12),
('Aldama', 7),
('Aldama', 8),
('Aldama', 28),
('Alfajayucan', 13),
('Aljojuca', 21),
('Allende', 5),
('Allende', 8),
('Allende', 19),
('Almoloya', 13),
('Almoloya de Alquisiras', 15),
('Almoloya de Juárez', 15),
('Almoloya del Río', 15),
('Alpatláhuac', 30),
('Alpoyeca', 12),
('Altamira', 28),
('Altamirano', 7),
('Altar', 26),
('Altepexi', 21),
('Alto Lucero de Gutiérrez Barrios', 30),
('Altotonga', 30),
('Alvarado', 30),
('Álvaro Obregón', 9),
('Álvaro Obregón', 16),
('Amacueca', 14),
('Amacuzac', 17),
('Amanalco', 15),
('Amatán', 7),
('Amatenango de la Frontera', 7),
('Amatenango del Valle', 7),
('Amatepec', 15),
('Amatitán', 14),
('Amatitlán', 30),
('Amatlán de Cañas', 18),
('Amatlán de los Reyes', 30),
('Amaxac de Guerrero', 29),
('Amealco de Bonfil', 22),
('Ameca', 14),
('Amecameca', 15),
('Amixtlán', 21),
('Amozoc', 21),
('Anáhuac', 19),
('Angamacutiro', 16),
('Angangueo', 16),
('Angel Albino Corzo', 7),
('Angel R. Cabada', 30),
('Angostura', 25),
('Ánimas Trujano', 20),
('Antiguo Morelos', 28),
('Apan', 13),
('Apaseo el Alto', 11),
('Apaseo el Grande', 11),
('Apatzingán', 16),
('Apaxco', 15),
('Apaxtla', 12),
('Apazapan', 30),
('Apetatitlán de Antonio Carvajal', 29),
('Apizaco', 29),
('Apodaca', 19),
('Aporo', 16),
('Apozol', 32),
('Apulco', 32),
('Aquila', 30),
('Aquila', 16),
('Aquiles Serdán', 8),
('Aquismón', 24),
('Aquixtla', 21),
('Aramberri', 19),
('Arandas', 14),
('Arcelia', 12),
('Ario', 16),
('Arivechi', 26),
('Arizpe', 26),
('Armadillo de los Infante', 24),
('Armería', 6),
('Arriaga', 7),
('Arroyo Seco', 22),
('Arteaga', 16),
('Arteaga', 5),
('Ascensión', 8),
('Asientos', 1),
('Astacinga', 30),
('Asunción Cacalotepec', 20),
('Asunción Cuyotepeji', 20),
('Asunción Ixtaltepec', 20),
('Asunción Nochixtlán', 20),
('Asunción Ocotlán', 20),
('Asunción Tlacolulita', 20),
('Atarjea', 11),
('Atemajac de Brizuela', 14),
('Atempan', 21),
('Atenango del Río', 12),
('Atenco', 15),
('Atengo', 14),
('Atenguillo', 14),
('Atexcal', 21),
('Atil', 26),
('Atitalaquia', 13),
('Atizapán', 15),
('Atizapán de Zaragoza', 15),
('Atlacomulco', 15),
('Atlahuilco', 30),
('Atlamajalcingo del Monte', 12),
('Atlangatepec', 29),
('Atlapexco', 13),
('Atlatlahucan', 17),
('Atlautla', 15),
('Atlequizayan', 21),
('Atlixco', 21),
('Atlixtac', 12),
('Atltzayanca', 29),
('Atolinga', 32),
('Atotonilco de Tula', 13),
('Atotonilco el Alto', 14),
('Atotonilco el Grande', 13),
('Atoyac', 14),
('Atoyac', 30),
('Atoyac de Álvarez', 12),
('Atoyatempan', 21),
('Atzacan', 30),
('Atzala', 21),
('Atzalan', 30),
('Atzitzihuacán', 21),
('Atzitzintla', 21),
('Autlán de Navarro', 14),
('Axapusco', 15),
('Axochiapan', 17),
('Axtla de Terrazas', 24),
('Axutla', 21),
('Ayahualulco', 30),
('Ayala', 17),
('Ayapango', 15),
('Ayoquezco de Aldama', 20),
('Ayotlán', 14),
('Ayotoxco de Guerrero', 21),
('Ayotzintepec', 20),
('Ayutla', 14),
('Ayutla de los Libres', 12),
('Azcapotzalco', 9),
('Azoyú', 12),
('Baca', 31),
('Bacadéhuachi', 26),
('Bacalar', 23),
('Bacanora', 26),
('Bacerac', 26),
('Bachíniva', 8),
('Bacoachi', 26),
('Bácum', 26),
('Badiraguato', 25),
('Bahía de Banderas', 18),
('Balancán', 27),
('Balleza', 8),
('Banámichi', 26),
('Banderilla', 30),
('Batopilas de Manuel Gómez Morín', 8),
('Baviácora', 26),
('Bavispe', 26),
('Bejucal de Ocampo', 7),
('Bella Vista', 7),
('Benemérito de las Américas', 7),
('Benito Juárez', 30),
('Benito Juárez', 23),
('Benito Juárez', 29),
('Benito Juárez', 32),
('Benito Juárez', 26),
('Benito Juárez', 12),
('Benito Juárez', 9),
('Benjamín Hill', 26),
('Berriozábal', 7),
('Boca del Río', 30),
('Bochil', 7),
('Bocoyna', 8),
('Bokobá', 31),
('Bolaños', 14),
('Briseñas', 16),
('Buctzotz', 31),
('Buenaventura', 8),
('Buenavista', 16),
('Buenavista de Cuéllar', 12),
('Burgos', 28),
('Bustamante', 19),
('Bustamante', 28),
('Cabo Corrientes', 14),
('Caborca', 26),
('Cacahoatán', 7),
('Cacalchén', 31),
('Cadereyta de Montes', 22),
('Cadereyta Jiménez', 19),
('Cajeme', 26),
('Calakmul', 4),
('Calcahualco', 30),
('Calera', 32),
('Calihualá', 20),
('Calimaya', 15),
('Calkiní', 4),
('Calnali', 13),
('Calotmul', 31),
('Calpan', 21),
('Calpulalpan', 29),
('Caltepec', 21),
('Calvillo', 1),
('Camargo', 8),
('Camargo', 28),
('Camarón de Tejeda', 30),
('Camerino Z. Mendoza', 30),
('Camocuautla', 21),
('Campeche', 4),
('Cañada Morelos', 21),
('Cañadas de Obregón', 14),
('Cananea', 26),
('Canatlán', 10),
('Candela', 5),
('Candelaria', 4),
('Candelaria Loxicha', 20),
('Canelas', 10),
('Cañitas de Felipe Pescador', 32),
('Cansahcab', 31),
('Cantamayec', 31),
('Capitán Luis Ángel Vidal', 7),
('Capulálpam de Méndez', 20),
('Capulhuac', 15),
('Carácuaro', 16),
('Carbó', 26),
('Cárdenas', 24),
('Cárdenas', 27),
('Cardonal', 13),
('Carichí', 8),
('Carlos A. Carrillo', 30),
('Carmen', 4),
('Carrillo Puerto', 30),
('Casas', 28),
('Casas Grandes', 8),
('Casimiro Castillo', 14),
('Castaños', 5),
('Castillo de Teayo', 30),
('Catazajá', 7),
('Catemaco', 30),
('Catorce', 24),
('Caxhuacan', 21),
('Cazones de Herrera', 30),
('Cedral', 24),
('Celaya', 11),
('Celestún', 31),
('Cenotillo', 31),
('Centla', 27),
('Centro', 27),
('Cerralvo', 19),
('Cerritos', 24),
('Cerro Azul', 30),
('Cerro de San Pedro', 24),
('Chacaltianguis', 30),
('Chacsinkín', 31),
('Chahuites', 20),
('Chalcatongo de Hidalgo', 20),
('Chalchicomula de Sesma', 21),
('Chalchihuitán', 7),
('Chalchihuites', 32),
('Chalco', 15),
('Chalma', 30),
('Champotón', 4),
('Chamula', 7),
('Chanal', 7),
('Chankom', 31),
('Chapa de Mota', 15),
('Chapab', 31),
('Chapala', 14),
('Chapantongo', 13),
('Chapulco', 21),
('Chapulhuacán', 13),
('Chapultenango', 7),
('Chapultepec', 15),
('Charapan', 16),
('Charcas', 24),
('Charo', 16),
('Chavinda', 16),
('Chemax', 31),
('Chenalhó', 7),
('Cherán', 16),
('Chiapa de Corzo', 7),
('Chiapilla', 7),
('Chiautempan', 29),
('Chiautla', 21),
('Chiautla', 15),
('Chiautzingo', 21),
('Chichimilá', 31),
('Chichiquila', 21),
('Chicoasén', 7),
('Chicoloapan', 15),
('Chicomuselo', 7),
('Chiconamel', 30),
('Chiconcuac', 15),
('Chiconcuautla', 21),
('Chiconquiaco', 30),
('Chicontepec', 30),
('Chicxulub Pueblo', 31),
('Chietla', 21),
('Chigmecatitlán', 21),
('Chignahuapan', 21),
('Chignautla', 21),
('Chihuahua', 8),
('Chikindzonot', 31),
('Chila', 21),
('Chila de la Sal', 21),
('Chilapa de Álvarez', 12),
('Chilchota', 16),
('Chilchotla', 21),
('Chilcuautla', 13),
('Chilón', 7),
('Chilpancingo de los Bravo', 12),
('Chimalhuacán', 15),
('Chimaltitán', 14),
('China', 19),
('Chinameca', 30),
('Chinampa de Gorostiza', 30),
('Chinantla', 21),
('Chinicuila', 16),
('Chínipas', 8),
('Chiquihuitlán de Benito Juárez', 20),
('Chiquilistlán', 14),
('Chocamán', 30),
('Chocholá', 31),
('Choix', 25),
('Chontla', 30),
('Chucándiro', 16),
('Chumatlán', 30),
('Chumayel', 31),
('Churintzio', 16),
('Churumuco', 16),
('Ciénega de Flores', 19),
('Ciénega de Zimatlán', 20),
('Cihuatlán', 14),
('Cintalapa', 7),
('Citlaltépetl', 30),
('Ciudad del Maíz', 24),
('Ciudad Fernández', 24),
('Ciudad Ixtepec', 20),
('Ciudad Madero', 28),
('Ciudad Valles', 24),
('Coacalco de Berriozábal', 15),
('Coacoatzintla', 30),
('Coahuayana', 16),
('Coahuayutla de José María Izazaga', 12),
('Coahuitlán', 30),
('Coalcomán de Vázquez Pallares', 16),
('Coapilla', 7),
('Coatecas Altas', 20),
('Coatepec', 30),
('Coatepec', 21),
('Coatepec Harinas', 15),
('Coatlán del Río', 17),
('Coatzacoalcos', 30),
('Coatzingo', 21),
('Coatzintla', 30),
('Cochoapa el Grande', 12),
('Cocotitlán', 15),
('Cocula', 12),
('Cocula', 14),
('Coeneo', 16),
('Coetzala', 30),
('Cohetzala', 21),
('Cohuecan', 21),
('Coicoyán de las Flores', 20),
('Cojumatlán de Régules', 16),
('Colima', 6),
('Colipa', 30),
('Colón', 22),
('Colotlán', 14),
('Comala', 6),
('Comalcalco', 27),
('Comapa', 30),
('Comitán de Domínguez', 7),
('Comondú', 3),
('Comonfort', 11),
('Compostela', 18),
('Concepción Buenavista', 20),
('Concepción de Buenos Aires', 14),
('Concepción del Oro', 32),
('Concepción Pápalo', 20),
('Concordia', 25),
('Coneto de Comonfort', 10),
('Conkal', 31),
('Constancia del Rosario', 20),
('Contepec', 16),
('Contla de Juan Cuamatzi', 29),
('Copainalá', 7),
('Copala', 12),
('Copalillo', 12),
('Copanatoyac', 12),
('Copándaro', 16),
('Coquimatlán', 6),
('Córdoba', 30),
('Coronado', 8),
('Coronango', 21),
('Coroneo', 11),
('Corregidora', 22),
('Cortazar', 11),
('Cosalá', 25),
('Cosamaloapan de Carpio', 30),
('Cosautlán de Carvajal', 30),
('Coscomatepec', 30),
('Cosío', 1),
('Cosolapa', 20),
('Cosoleacaque', 30),
('Cosoltepec', 20),
('Cotaxtla', 30),
('Cotija', 16),
('Coxcatlán', 24),
('Coxcatlán', 21),
('Coxquihui', 30),
('Coyame del Sotol', 8),
('Coyoacán', 9),
('Coyomeapan', 21),
('Coyotepec', 21),
('Coyotepec', 15),
('Coyuca de Benítez', 12),
('Coyuca de Catalán', 12),
('Coyutla', 30),
('Cozumel', 23),
('Cruillas', 28),
('Cuajimalpa de Morelos', 9),
('Cuajinicuilapa', 12),
('Cualác', 12),
('Cuapiaxtla', 29),
('Cuapiaxtla de Madero', 21),
('Cuatro Ciénegas', 5),
('Cuauhtémoc', 8),
('Cuauhtémoc', 9),
('Cuauhtémoc', 6),
('Cuauhtémoc', 32),
('Cuautempan', 21),
('Cuautepec', 12),
('Cuautepec de Hinojosa', 13),
('Cuautinchán', 21),
('Cuautitlán', 15),
('Cuautitlán de García Barragán', 14),
('Cuautitlán Izcalli', 15),
('Cuautla', 17),
('Cuautla', 14),
('Cuautlancingo', 21),
('Cuaxomulco', 29),
('Cuayuca de Andrade', 21),
('Cucurpe', 26),
('Cuencamé', 10),
('Cuerámaro', 11),
('Cuernavaca', 17),
('Cuetzala del Progreso', 12),
('Cuetzalan del Progreso', 21),
('Cuichapa', 30),
('Cuilápam de Guerrero', 20),
('Cuitláhuac', 30),
('Cuitzeo', 16),
('Culiacán', 25),
('Cumpas', 26),
('Cuncunul', 31),
('Cunduacán', 27),
('Cuquío', 14),
('Cusihuiriachi', 8),
('Cutzamala de Pinzón', 12),
('Cuyamecalco Villa de Zaragoza', 20),
('Cuyoaco', 21),
('Cuzamá', 31),
('Degollado', 14),
('Del Nayar', 18),
('Delicias', 8),
('Divisaderos', 26),
('Doctor Arroyo', 19),
('Doctor Coss', 19),
('Doctor González', 19),
('Doctor Mora', 11),
('Dolores Hidalgo Cuna de la Independencia Nacional', 11),
('Domingo Arenas', 21),
('Donato Guerra', 15),
('Dr. Belisario Domínguez', 8),
('Durango', 10),
('Dzán', 31),
('Dzemul', 31),
('Dzidzantún', 31),
('Dzilam de Bravo', 31),
('Dzilam González', 31),
('Dzitás', 31),
('Dzoncauich', 31),
('Ebano', 24),
('Ecatepec de Morelos', 15),
('Ecatzingo', 15),
('Ecuandureo', 16),
('Eduardo Neri', 12),
('Ejutla', 14),
('El Arenal', 14),
('El Arenal', 13),
('El Barrio de la Soledad', 20),
('El Bosque', 7),
('El Carmen', 19),
('El Carmen Tequexquitla', 29),
('El Espinal', 20),
('El Fuerte', 25),
('El Grullo', 14),
('El Higo', 30),
('El Limón', 14),
('El Llano', 1),
('El Mante', 28),
('El Marqués', 22),
('El Naranjo', 24),
('El Oro', 10),
('El Oro', 15),
('El Parral', 7),
('El Plateado de Joaquín Amaro', 32),
('El Porvenir', 7),
('El Salto', 14),
('El Salvador', 32),
('El Tule', 8),
('Elota', 25),
('Eloxochitlán', 21),
('Eloxochitlán', 13),
('Eloxochitlán de Flores Magón', 20),
('Emiliano Zapata', 17),
('Emiliano Zapata', 29),
('Emiliano Zapata', 13),
('Emiliano Zapata', 30),
('Emiliano Zapata', 7),
('Emiliano Zapata', 27),
('Empalme', 26),
('Encarnación de Díaz', 14),
('Ensenada', 2),
('Epatlán', 21),
('Epazoyucan', 13),
('Epitacio Huerta', 16),
('Erongarícuaro', 16),
('Escárcega', 4),
('Escobedo', 5),
('Escuinapa', 25),
('Escuintla', 7),
('Españita', 29),
('Esperanza', 21),
('Espinal', 30),
('Espita', 31),
('Etchojoa', 26),
('Etzatlán', 14),
('Ezequiel Montes', 22),
('Felipe Carrillo Puerto', 23),
('Filomeno Mata', 30),
('Florencio Villarreal', 12),
('Fortín', 30),
('Francisco I. Madero', 13),
('Francisco I. Madero', 5),
('Francisco León', 7),
('Francisco Z. Mena', 21),
('Fresnillo', 32),
('Fresnillo de Trujano', 20),
('Frontera', 5),
('Frontera Comalapa', 7),
('Frontera Hidalgo', 7),
('Fronteras', 26),
('Gabriel Zamora', 16),
('Galeana', 8),
('Galeana', 19),
('García', 19),
('Genaro Codina', 32),
('General Bravo', 19),
('General Canuto A. Neri', 12),
('General Cepeda', 5),
('General Enrique Estrada', 32),
('General Escobedo', 19),
('General Felipe Ángeles', 21),
('General Francisco R. Murguía', 32),
('General Heliodoro Castillo', 12),
('General Pánfilo Natera', 32),
('General Plutarco Elías Calles', 26),
('General Simón Bolívar', 10),
('General Terán', 19),
('General Treviño', 19),
('General Zaragoza', 19),
('General Zuazua', 19),
('Gómez Farías', 8),
('Gómez Farías', 28),
('Gómez Farías', 14),
('Gómez Palacio', 10),
('González', 28),
('Gran Morelos', 8),
('Granados', 26),
('Guachinango', 14),
('Guachochi', 8),
('Guadalajara', 14),
('Guadalcázar', 24),
('Guadalupe', 21),
('Guadalupe', 32),
('Guadalupe', 19),
('Guadalupe', 8),
('Guadalupe de Ramírez', 20),
('Guadalupe Etla', 20),
('Guadalupe Victoria', 10),
('Guadalupe Victoria', 21),
('Guadalupe y Calvo', 8),
('Guanaceví', 10),
('Guanajuato', 11),
('Guasave', 25),
('Guaymas', 26),
('Guazapares', 8),
('Guelatao de Juárez', 20),
('Güémez', 28),
('Guerrero', 28),
('Guerrero', 8),
('Guerrero', 5),
('Guevea de Humboldt', 20),
('Gustavo A. Madero', 9),
('Gustavo Díaz Ordaz', 28),
('Gutiérrez Zamora', 30),
('Halachó', 31),
('Hecelchakán', 4),
('Hermenegildo Galeana', 21),
('Hermosillo', 26),
('Heroica Ciudad de Ejutla de Crespo', 20),
('Heroica Ciudad de Huajuapan de León', 20),
('Heroica Ciudad de Juchitán de Zaragoza', 20),
('Heroica Ciudad de Tlaxiaco', 20),
('Hidalgo', 16),
('Hidalgo', 5),
('Hidalgo', 19),
('Hidalgo', 28),
('Hidalgo', 10),
('Hidalgo del Parral', 8),
('Hidalgotitlán', 30),
('Higueras', 19),
('Hocabá', 31),
('Hoctún', 31),
('Homún', 31),
('Honey', 21),
('Hopelchén', 4),
('Hostotipaquillo', 14),
('Huachinera', 26),
('Huajicori', 18),
('Hualahuises', 19),
('Huamantla', 29),
('Huamuxtitlán', 12),
('Huandacareo', 16),
('Huanímaro', 11),
('Huaniqueo', 16),
('Huanusco', 32),
('Huaquechula', 21),
('Huásabas', 26),
('Huasca de Ocampo', 13),
('Huatabampo', 26),
('Huatlatlauca', 21),
('Huatusco', 30),
('Huauchinango', 21),
('Huautepec', 20),
('Huautla', 13),
('Huautla de Jiménez', 20),
('Huayacocotla', 30),
('Huazalingo', 13),
('Huehuetán', 7),
('Huehuetla', 21),
('Huehuetla', 13),
('Huehuetlán', 24),
('Huehuetlán el Chico', 21),
('Huehuetlán el Grande', 21),
('Huehuetoca', 15),
('Huejotitán', 8),
('Huejotzingo', 21),
('Huejúcar', 14),
('Huejuquilla el Alto', 14),
('Huejutla de Reyes', 13),
('Huépac', 26),
('Huetamo', 16),
('Hueyapan', 21),
('Hueyapan de Ocampo', 30),
('Hueyotlipan', 29),
('Hueypoxtla', 15),
('Hueytamalco', 21),
('Hueytlalpan', 21),
('Huhí', 31),
('Huichapan', 13),
('Huiloapan de Cuauhtémoc', 30),
('Huimanguillo', 27),
('Huimilpan', 22),
('Huiramba', 16),
('Huitiupán', 7),
('Huitzilac', 17),
('Huitzilan de Serdán', 21),
('Huitziltepec', 21),
('Huitzuco de los Figueroa', 12),
('Huixquilucan', 15),
('Huixtán', 7),
('Huixtla', 7),
('Hunucmá', 31),
('Ignacio de la Llave', 30),
('Ignacio Zaragoza', 8),
('Iguala de la Independencia', 12),
('Igualapa', 12),
('Ilamatlán', 30),
('Iliatenco', 12),
('Imuris', 26),
('Indaparapeo', 16),
('Indé', 10),
('Irapuato', 11),
('Irimbo', 16),
('Isidro Fabela', 15),
('Isla', 30),
('Isla Mujeres', 23),
('Iturbide', 19),
('Ixcamilpa de Guerrero', 21),
('Ixcaquixtla', 21),
('Ixcateopan de Cuauhtémoc', 12),
('Ixcatepec', 30),
('Ixhuacán de los Reyes', 30),
('Ixhuatán', 7),
('Ixhuatlán de Madero', 30),
('Ixhuatlán del Café', 30),
('Ixhuatlán del Sureste', 30),
('Ixhuatlancillo', 30),
('Ixil', 31),
('Ixmatlahuacan', 30),
('Ixmiquilpan', 13),
('Ixpantepec Nieves', 20),
('Ixtacamaxtitlán', 21),
('Ixtacomitán', 7),
('Ixtacuixtla de Mariano Matamoros', 29),
('Ixtaczoquitlán', 30),
('Ixtapa', 7),
('Ixtapaluca', 15),
('Ixtapan de la Sal', 15),
('Ixtapan del Oro', 15),
('Ixtapangajoya', 7),
('Ixtenco', 29),
('Ixtepec', 21),
('Ixtlahuaca', 15),
('Ixtlahuacán', 6),
('Ixtlahuacán de los Membrillos', 14),
('Ixtlahuacán del Río', 14),
('Ixtlán', 16),
('Ixtlán de Juárez', 20),
('Ixtlán del Río', 18),
('Izamal', 31),
('Iztacalco', 9),
('Iztapalapa', 9),
('Izúcar de Matamoros', 21),
('Jacala de Ledezma', 13),
('Jacona', 16),
('Jala', 18),
('Jalacingo', 30),
('Jalapa', 27),
('Jalcomulco', 30),
('Jalostotitlán', 14),
('Jalpa', 32),
('Jalpa de Méndez', 27),
('Jalpan', 21),
('Jalpan de Serra', 22),
('Jaltenco', 15),
('Jáltipan', 30),
('Jaltocán', 13),
('Jamapa', 30),
('Jamay', 14),
('Janos', 8),
('Jantetelco', 17),
('Jaral del Progreso', 11),
('Jaumave', 28),
('Jerécuaro', 11),
('Jerez', 32),
('Jesús Carranza', 30),
('Jesús María', 1),
('Jesús María', 14),
('Jilotepec', 30),
('Jilotepec', 15),
('Jilotlán de los Dolores', 14),
('Jilotzingo', 15),
('Jiménez', 8),
('Jiménez', 28),
('Jiménez', 5),
('Jiménez', 16),
('Jiménez del Teul', 32),
('Jiquilpan', 16),
('Jiquipilas', 7),
('Jiquipilco', 15),
('Jitotol', 7),
('Jiutepec', 17),
('Jocotepec', 14),
('Jocotitlán', 15),
('Jojutla', 17),
('Jolalpan', 21),
('Jonacatepec de Leandro Valle', 17),
('Jonotla', 21),
('Jonuta', 27),
('Jopala', 21),
('Joquicingo', 15),
('José Azueta', 30),
('José Joaquín de Herrera', 12),
('José María Morelos', 23),
('José Sixto Verduzco', 16),
('Juan Aldama', 32),
('Juan C. Bonilla', 21),
('Juan Galindo', 21),
('Juan N. Méndez', 21),
('Juan R. Escudero', 12),
('Juan Rodríguez Clara', 30),
('Juanacatlán', 14),
('Juárez', 7),
('Juárez', 8),
('Juárez', 5),
('Juárez', 19),
('Juárez', 16),
('Juárez Hidalgo', 13),
('Juchipila', 32),
('Juchique de Ferrer', 30),
('Juchitán', 12),
('Juchitepec', 15),
('Juchitlán', 14),
('Julimes', 8),
('Jungapeo', 16),
('Kanasín', 31),
('Kantunil', 31),
('Kaua', 31);

INSERT INTO CAT_CIUDAD (NOMBRE, FK_ENTIDAD_FEDERATIVA) VALUES
('Kinchil', 31),
('Kopomá', 31),
('La Antigua', 30),
('La Barca', 14),
('La Colorada', 26),
('La Compañía', 20),
('La Concordia', 7),
('La Cruz', 8),
('La Grandeza', 7),
('La Huacana', 16),
('La Huerta', 14),
('La Independencia', 7),
('La Libertad', 7),
('La Magdalena Contreras', 9),
('La Magdalena Tlaltelulco', 29),
('La Magdalena Tlatlauquitepec', 21),
('La Manzanilla de la Paz', 14),
('La Misión', 13),
('La Paz', 15),
('La Paz', 3),
('La Pe', 20),
('La Perla', 30),
('La Piedad', 16),
('La Reforma', 20),
('La Trinidad Vista Hermosa', 20),
('La Trinitaria', 7),
('La Unión de Isidoro Montes de Oca', 12),
('La Yesca', 18),
('Lafragua', 21),
('Lagos de Moreno', 14),
('Lagunillas', 24),
('Lagunillas', 16),
('Lamadrid', 5),
('Lampazos de Naranjo', 19),
('Landa de Matamoros', 22),
('Landero y Coss', 30),
('Larráinzar', 7),
('Las Choapas', 30),
('Las Margaritas', 7),
('Las Minas', 30),
('Las Rosas', 7),
('Las Vigas de Ramírez', 30),
('Lázaro Cárdenas', 23),
('Lázaro Cárdenas', 16),
('Lázaro Cárdenas', 29),
('León', 11),
('Leonardo Bravo', 12),
('Lerdo', 10),
('Lerdo de Tejada', 30),
('Lerma', 15),
('Libres', 21),
('Linares', 19),
('Llera', 28),
('Lolotla', 13),
('Loma Bonita', 20),
('López', 8),
('Loreto', 3),
('Loreto', 32),
('Los Aldamas', 19),
('Los Cabos', 3),
('Los Herreras', 19),
('Los Ramones', 19),
('Los Reyes', 30),
('Los Reyes', 16),
('Los Reyes de Juárez', 21),
('Luis Moya', 32),
('Luvianos', 15),
('Macuspana', 27),
('Madera', 8),
('Madero', 16),
('Magdalena', 26),
('Magdalena', 14),
('Magdalena', 30),
('Magdalena Apasco', 20),
('Magdalena Jaltepec', 20),
('Magdalena Mixtepec', 20),
('Magdalena Ocotlán', 20),
('Magdalena Peñasco', 20),
('Magdalena Teitipac', 20),
('Magdalena Tequisistlán', 20),
('Magdalena Tlacotepec', 20),
('Magdalena Yodocono de Porfirio Díaz', 20),
('Magdalena Zahuatlán', 20),
('Maguarichi', 8),
('Mainero', 28),
('Malinalco', 15),
('Malinaltepec', 12),
('Maltrata', 30),
('Mama', 31),
('Maní', 31),
('Manlio Fabio Altamirano', 30),
('Manuel Benavides', 8),
('Manuel Doblado', 11),
('Manzanillo', 6),
('Mapastepec', 7),
('Mapimí', 10),
('Maravatío', 16),
('Maravilla Tenejapa', 7),
('Marcos Castellanos', 16),
('Mariano Escobedo', 30),
('Marín', 19),
('Mariscala de Juárez', 20),
('Marquelia', 12),
('Marqués de Comillas', 7),
('Martínez de la Torre', 30),
('Mártir de Cuilapan', 12),
('Mártires de Tacubaya', 20),
('Mascota', 14),
('Matachí', 8),
('Matamoros', 28),
('Matamoros', 5),
('Matamoros', 8),
('Matehuala', 24),
('Matías Romero Avendaño', 20),
('Matlapa', 24),
('Maxcanú', 31),
('Mayapán', 31),
('Mazamitla', 14),
('Mazapa de Madero', 7),
('Mazapil', 32),
('Mazapiltepec de Juárez', 21),
('Mazatán', 7),
('Mazatán', 26),
('Mazatecochco de José María Morelos', 29),
('Mazatepec', 17),
('Mazatlán', 25),
('Mazatlán Villa de Flores', 20),
('Mecatlán', 30),
('Mecayapan', 30),
('Medellín de Bravo', 30),
('Melchor Ocampo', 19),
('Melchor Ocampo', 32),
('Melchor Ocampo', 15),
('Méndez', 28),
('Meoqui', 8),
('Mérida', 31),
('Mesones Hidalgo', 20),
('Metapa', 7),
('Metepec', 13),
('Metepec', 15),
('Metlatónoc', 12),
('Metztitlán', 13),
('Mexicali', 2),
('Mexicaltzingo', 15),
('Mexquitic de Carmona', 24),
('Mexticacán', 14),
('Mezcalapa', 7),
('Mezquital', 10),
('Mezquital del Oro', 32),
('Mezquitic', 14),
('Miacatlán', 17),
('Miahuatlán', 30),
('Miahuatlán de Porfirio Díaz', 20),
('Mier', 28),
('Mier y Noriega', 19),
('Miguel Alemán', 28),
('Miguel Auza', 32),
('Miguel Hidalgo', 9),
('Milpa Alta', 9),
('Mina', 19),
('Minatitlán', 30),
('Minatitlán', 6),
('Mineral de la Reforma', 13),
('Mineral del Chico', 13),
('Mineral del Monte', 13),
('Miquihuana', 28),
('Misantla', 30),
('Mitontic', 7),
('Mixistlán de la Reforma', 20),
('Mixquiahuala de Juárez', 13),
('Mixtla', 21),
('Mixtla de Altamirano', 30),
('Mixtlán', 14),
('Mochitlán', 12),
('Mocochá', 31),
('Mocorito', 25),
('Moctezuma', 24),
('Moctezuma', 26),
('Molango de Escamilla', 13),
('Molcaxac', 21),
('Moloacán', 30),
('Momax', 32),
('Monclova', 5),
('Monjas', 20),
('Monte Escobedo', 32),
('Montecristo de Guerrero', 7),
('Montemorelos', 19),
('Monterrey', 19),
('Morelia', 16),
('Morelos', 5),
('Morelos', 16),
('Morelos', 32),
('Morelos', 15),
('Morelos', 8),
('Moris', 8),
('Moroleón', 11),
('Motozintla', 7),
('Motul', 31),
('Moyahua de Estrada', 32),
('Múgica', 16),
('Mulegé', 3),
('Muna', 31),
('Muñoz de Domingo Arenas', 29),
('Muxupip', 31),
('Múzquiz', 5),
('Nacajuca', 27),
('Naco', 26),
('Nácori Chico', 26),
('Nacozari de García', 26),
('Nadadores', 5),
('Nahuatzen', 16),
('Namiquipa', 8),
('Nanacamilpa de Mariano Arista', 29),
('Nanchital de Lázaro Cárdenas del Río', 30),
('Naolinco', 30),
('Naranjal', 30),
('Naranjos Amatlán', 30),
('Natividad', 20),
('Natívitas', 29),
('Naucalpan de Juárez', 15),
('Naupan', 21),
('Nautla', 30),
('Nauzontla', 21),
('Nava', 5),
('Navojoa', 26),
('Navolato', 25),
('Nazareno Etla', 20),
('Nazas', 10),
('Nealtican', 21),
('Nejapa de Madero', 20),
('Nextlalpan', 15),
('Nezahualcóyotl', 15),
('Nicolás Bravo', 21),
('Nicolás Flores', 13),
('Nicolás Romero', 15),
('Nicolás Ruíz', 7),
('Nochistlán de Mejía', 32),
('Nocupétaro', 16),
('Nogales', 30),
('Nogales', 26),
('Nombre de Dios', 10),
('Nonoava', 8),
('Nopala de Villagrán', 13),
('Nopaltepec', 15),
('Nopalucan', 21),
('Noria de Ángeles', 32),
('Nuevo Casas Grandes', 8),
('Nuevo Ideal', 10),
('Nuevo Laredo', 28),
('Nuevo Morelos', 28),
('Nuevo Parangaricutiro', 16),
('Nuevo Urecho', 16),
('Nuevo Zoquiápam', 20),
('Numarán', 16),
('Oaxaca de Juárez', 20),
('Ocampo', 11),
('Ocampo', 5),
('Ocampo', 8),
('Ocampo', 28),
('Ocampo', 16),
('Ocampo', 10),
('Ocosingo', 7),
('Ocotepec', 21),
('Ocotepec', 7),
('Ocotlán', 14),
('Ocotlán de Morelos', 20),
('Ocoyoacac', 15),
('Ocoyucan', 21),
('Ocozocoautla de Espinosa', 7),
('Ocuilan', 15),
('Ocuituco', 17),
('Ojinaga', 8),
('Ojocaliente', 32),
('Ojuelos de Jalisco', 14),
('Olinalá', 12),
('Olintla', 21),
('Oluta', 30),
('Omealca', 30),
('Ometepec', 12),
('Omitlán de Juárez', 13),
('Onavas', 26),
('Opichén', 31),
('Opodepe', 26),
('Oquitoa', 26),
('Oriental', 21),
('Orizaba', 30),
('Ostuacán', 7),
('Osumacinta', 7),
('Otáez', 10),
('Otatitlán', 30),
('Oteapan', 30),
('Othón P. Blanco', 23),
('Otumba', 15),
('Otzoloapan', 15),
('Otzolotepec', 15),
('Oxchuc', 7),
('Oxkutzcab', 31),
('Ozuluama de Mascareñas', 30),
('Ozumba', 15),
('Pabellón de Arteaga', 1),
('Pachuca de Soto', 13),
('Pacula', 13),
('Padilla', 28),
('Pahuatlán', 21),
('Pajacuarán', 16),
('Pajapan', 30),
('Palenque', 7),
('Palizada', 4),
('Palmar de Bravo', 21),
('Palmillas', 28),
('Panabá', 31),
('Panindícuaro', 16),
('Panotla', 29),
('Pantelhó', 7),
('Pantepec', 21),
('Pantepec', 7),
('Pánuco', 30),
('Pánuco', 32),
('Pánuco de Coronado', 10),
('Papalotla', 15),
('Papalotla de Xicohténcatl', 29),
('Papantla', 30),
('Paracho', 16),
('Parácuaro', 16),
('Paraíso', 27),
('Parás', 19),
('Parras', 5),
('Paso de Ovejas', 30),
('Paso del Macho', 30),
('Pátzcuaro', 16),
('Pedro Ascencio Alquisiras', 12),
('Pedro Escobedo', 22),
('Peñamiller', 22),
('Penjamillo', 16),
('Pénjamo', 11),
('Peñón Blanco', 10),
('Peribán', 16),
('Perote', 30),
('Pesquería', 19),
('Petatlán', 12),
('Petlalcingo', 21),
('Peto', 31),
('Piaxtla', 21),
('Pichucalco', 7),
('Piedras Negras', 5),
('Pihuamo', 14),
('Pijijiapan', 7),
('Pilcaya', 12),
('Pinal de Amoles', 22),
('Pinos', 32),
('Pinotepa de Don Luis', 20),
('Pisaflores', 13),
('Pitiquito', 26),
('Platón Sánchez', 30),
('Playa Vicente', 30),
('Playas de Rosarito', 2),
('Pluma Hidalgo', 20),
('Poanas', 10),
('Polotitlán', 15),
('Poncitlán', 14),
('Poza Rica de Hidalgo', 30),
('Praxedis G. Guerrero', 8),
('Progreso', 31),
('Progreso', 5),
('Progreso de Obregón', 13),
('Puebla', 21),
('Pueblo Nuevo', 11),
('Pueblo Nuevo', 10),
('Pueblo Nuevo Solistahuacán', 7),
('Pueblo Viejo', 30),
('Puente de Ixtla', 17),
('Puente Nacional', 30),
('Puerto Morelos', 23),
('Puerto Peñasco', 26),
('Puerto Vallarta', 14),
('Pungarabato', 12),
('Purépero', 16),
('Purísima del Rincón', 11),
('Puruándiro', 16),
('Putla Villa de Guerrero', 20),
('Quecholac', 21),
('Quechultenango', 12),
('Queréndaro', 16),
('Querétaro', 22),
('Quimixtlán', 21),
('Quintana Roo', 31),
('Quiriego', 26),
('Quiroga', 16),
('Quitupan', 14),
('Rafael Delgado', 30),
('Rafael Lara Grajales', 21),
('Rafael Lucio', 30),
('Ramos Arizpe', 5),
('Rayón', 7),
('Rayón', 24),
('Rayón', 26),
('Rayón', 15),
('Rayones', 19),
('Reforma', 7),
('Reforma de Pineda', 20),
('Reyes Etla', 20),
('Reynosa', 28),
('Rincón Chamula San Pedro', 7),
('Rincón de Romos', 1),
('Río Blanco', 30),
('Río Bravo', 28),
('Río Grande', 32),
('Río Lagartos', 31),
('Rioverde', 24),
('Riva Palacio', 8),
('Rodeo', 10),
('Rojas de Cuauhtémoc', 20),
('Romita', 11),
('Rosales', 8),
('Rosamorada', 18),
('Rosario', 26),
('Rosario', 25),
('Rosario', 8),
('Ruíz', 18),
('Sabanilla', 7),
('Sabinas', 5),
('Sabinas Hidalgo', 19),
('Sacalum', 31),
('Sacramento', 5),
('Sahuaripa', 26),
('Sahuayo', 16),
('Sain Alto', 32),
('Salamanca', 11),
('Salina Cruz', 20),
('Salinas', 24),
('Salinas Victoria', 19),
('Saltabarranca', 30),
('Saltillo', 5),
('Salto de Agua', 7),
('Salvador Alvarado', 25),
('Salvador Escalante', 16),
('Salvatierra', 11),
('Samahil', 31),
('San Agustín Amatengo', 20),
('San Agustín Atenango', 20),
('San Agustín Chayuco', 20),
('San Agustín de las Juntas', 20),
('San Agustín Etla', 20),
('San Agustín Loxicha', 20),
('San Agustín Metzquititlán', 13),
('San Agustín Tlacotepec', 20),
('San Agustín Tlaxiaca', 13),
('San Agustín Yatareni', 20),
('San Andrés Cabecera Nueva', 20),
('San Andrés Cholula', 21),
('San Andrés Dinicuiti', 20),
('San Andrés Duraznal', 7),
('San Andrés Huaxpaltepec', 20),
('San Andrés Huayápam', 20),
('San Andrés Ixtlahuaca', 20),
('San Andrés Lagunas', 20),
('San Andrés Nuxiño', 20),
('San Andrés Paxtlán', 20),
('San Andrés Sinaxtla', 20),
('San Andrés Solaga', 20),
('San Andrés Tenejapan', 30),
('San Andrés Teotilálpam', 20),
('San Andrés Tepetlapa', 20),
('San Andrés Tuxtla', 30),
('San Andrés Yaá', 20),
('San Andrés Zabache', 20),
('San Andrés Zautla', 20),
('San Antonino Castillo Velasco', 20),
('San Antonino el Alto', 20),
('San Antonino Monte Verde', 20),
('San Antonio', 24),
('San Antonio Acutla', 20),
('San Antonio Cañada', 21),
('San Antonio de la Cal', 20),
('San Antonio Huitepec', 20),
('San Antonio la Isla', 15),
('San Antonio Nanahuatípam', 20),
('San Antonio Sinicahua', 20),
('San Antonio Tepetlapa', 20),
('San Baltazar Chichicápam', 20),
('San Baltazar Loxicha', 20),
('San Baltazar Yatzachi el Bajo', 20),
('San Bartolo Coyotepec', 20),
('San Bartolo Soyaltepec', 20),
('San Bartolo Tutotepec', 13),
('San Bartolo Yautepec', 20),
('San Bartolomé Ayautla', 20),
('San Bartolomé Loxicha', 20),
('San Bartolomé Quialana', 20),
('San Bartolomé Yucuañe', 20),
('San Bartolomé Zoogocho', 20),
('San Bernardo', 10),
('San Bernardo Mixtepec', 20),
('San Blas', 18),
('San Blas Atempa', 20),
('San Buenaventura', 5),
('San Carlos', 28),
('San Carlos Yautepec', 20),
('San Ciro de Acosta', 24),
('San Cristóbal Amatlán', 20),
('San Cristóbal Amoltepec', 20),
('San Cristóbal de la Barranca', 14),
('San Cristóbal de las Casas', 7),
('San Cristóbal Lachirioag', 20),
('San Cristóbal Suchixtlahuaca', 20),
('San Damián Texóloc', 29),
('San Diego de Alejandría', 14),
('San Diego de la Unión', 11),
('San Diego la Mesa Tochimiltzingo', 21),
('San Dimas', 10),
('San Dionisio del Mar', 20),
('San Dionisio Ocotepec', 20),
('San Dionisio Ocotlán', 20),
('San Esteban Atatlahuca', 20),
('San Felipe', 11),
('San Felipe', 31),
('San Felipe de Jesús', 26),
('San Felipe del Progreso', 15),
('San Felipe Jalapa de Díaz', 20),
('San Felipe Orizatlán', 13),
('San Felipe Tejalápam', 20),
('San Felipe Teotlalcingo', 21),
('San Felipe Tepatlán', 21),
('San Felipe Usila', 20),
('San Fernando', 7),
('San Fernando', 28),
('San Francisco Cahuacuá', 20),
('San Francisco Cajonos', 20),
('San Francisco Chapulapa', 20),
('San Francisco Chindúa', 20),
('San Francisco de Borja', 8),
('San Francisco de Conchos', 8),
('San Francisco de los Romo', 1),
('San Francisco del Mar', 20);

INSERT INTO CAT_CIUDAD (NOMBRE, FK_ENTIDAD_FEDERATIVA) VALUES
('San Francisco del Oro', 8),
('San Francisco del Rincón', 11),
('San Francisco Huehuetlán', 20),
('San Francisco Ixhuatán', 20),
('San Francisco Jaltepetongo', 20),
('San Francisco Lachigoló', 20),
('San Francisco Logueche', 20),
('San Francisco Nuxaño', 20),
('San Francisco Ozolotepec', 20),
('San Francisco Sola', 20),
('San Francisco Telixtlahuaca', 20),
('San Francisco Teopan', 20),
('San Francisco Tetlanohcan', 29),
('San Francisco Tlapancingo', 20),
('San Gabriel', 14),
('San Gabriel Chilac', 21),
('San Gabriel Mixtepec', 20),
('San Gregorio Atzompa', 21),
('San Ignacio', 25),
('San Ignacio Cerro Gordo', 14),
('San Ignacio Río Muerto', 26),
('San Ildefonso Amatlán', 20),
('San Ildefonso Sola', 20),
('San Ildefonso Villa Alta', 20),
('San Jacinto Amilpas', 20),
('San Jacinto Tlacotepec', 20),
('San Javier', 26),
('San Jerónimo Coatlán', 20),
('San Jerónimo Silacayoapilla', 20),
('San Jerónimo Sosola', 20),
('San Jerónimo Taviche', 20),
('San Jerónimo Tecóatl', 20),
('San Jerónimo Tecuanipan', 21),
('San Jerónimo Tlacochahuaya', 20),
('San Jerónimo Xayacatlán', 21),
('San Jerónimo Zacualpan', 29),
('San Joaquín', 22),
('San Jorge Nuchita', 20),
('San José Ayuquila', 20),
('San José Chiapa', 21),
('San José Chiltepec', 20),
('San José de Gracia', 1),
('San José del Peñasco', 20),
('San José del Progreso', 20),
('San José del Rincón', 15),
('San José Estancia Grande', 20),
('San José Independencia', 20),
('San José Iturbide', 11),
('San José Lachiguiri', 20),
('San José Miahuatlán', 21),
('San José Teacalco', 29),
('San José Tenango', 20),
('San Juan Achiutla', 20),
('San Juan Atenco', 21),
('San Juan Atepec', 20),
('San Juan Atzompa', 21),
('San Juan Bautista Atatlahuca', 20),
('San Juan Bautista Coixtlahuaca', 20),
('San Juan Bautista Cuicatlán', 20),
('San Juan Bautista Guelache', 20),
('San Juan Bautista Jayacatlán', 20),
('San Juan Bautista Lo de Soto', 20),
('San Juan Bautista Suchitepec', 20),
('San Juan Bautista Tlachichilco', 20),
('San Juan Bautista Tlacoatzintepec', 20),
('San Juan Bautista Tuxtepec', 20),
('San Juan Bautista Valle Nacional', 20),
('San Juan Cacahuatepec', 20),
('San Juan Cancuc', 7),
('San Juan Chicomezúchil', 20),
('San Juan Chilateca', 20),
('San Juan Cieneguilla', 20),
('San Juan Coatzóspam', 20),
('San Juan Colorado', 20),
('San Juan Comaltepec', 20),
('San Juan Cotzocón', 20),
('San Juan de Guadalupe', 10),
('San Juan de los Cués', 20),
('San Juan de los Lagos', 14),
('San Juan de Sabinas', 5),
('San Juan del Estado', 20),
('San Juan del Río', 20),
('San Juan del Río', 22),
('San Juan del Río', 10),
('San Juan Diuxi', 20),
('San Juan Evangelista', 30),
('San Juan Evangelista Analco', 20),
('San Juan Guelavía', 20),
('San Juan Guichicovi', 20),
('San Juan Huactzinco', 29),
('San Juan Ihualtepec', 20),
('San Juan Juquila Mixes', 20),
('San Juan Juquila Vijanos', 20),
('San Juan Lachao', 20),
('San Juan Lachigalla', 20),
('San Juan Lajarcia', 20),
('San Juan Lalana', 20),
('San Juan Mazatlán', 20),
('San Juan Mixtepec -Dto. 08 -', 20),
('San Juan Mixtepec -Dto. 26 -', 20),
('San Juan Ñumí', 20),
('San Juan Ozolotepec', 20),
('San Juan Petlapa', 20),
('San Juan Quiahije', 20),
('San Juan Quiotepec', 20),
('San Juan Sayultepec', 20),
('San Juan Tabaá', 20),
('San Juan Tamazola', 20),
('San Juan Teita', 20),
('San Juan Teitipac', 20),
('San Juan Tepeuxila', 20),
('San Juan Teposcolula', 20),
('San Juan Yaeé', 20),
('San Juan Yatzona', 20),
('San Juan Yucuita', 20),
('San Juanito de Escobedo', 14),
('San Julián', 14),
('San Lorenzo', 20),
('San Lorenzo Albarradas', 20),
('San Lorenzo Axocomanitla', 29),
('San Lorenzo Cacaotepec', 20),
('San Lorenzo Cuaunecuiltitla', 20),
('San Lorenzo Texmelúcan', 20),
('San Lorenzo Victoria', 20),
('San Lucas', 7),
('San Lucas', 16),
('San Lucas Camotlán', 20),
('San Lucas Ojitlán', 20),
('San Lucas Quiaviní', 20),
('San Lucas Tecopilco', 29),
('San Lucas Zoquiápam', 20),
('San Luis Acatlán', 12),
('San Luis Amatlán', 20),
('San Luis de la Paz', 11),
('San Luis del Cordero', 10),
('San Luis Potosí', 24),
('San Luis Río Colorado', 26),
('San Marcial Ozolotepec', 20),
('San Marcos', 14),
('San Marcos', 12),
('San Marcos Arteaga', 20),
('San Martín Chalchicuautla', 24),
('San Martín de Bolaños', 14),
('San Martín de las Pirámides', 15),
('San Martín de los Cansecos', 20),
('San Martín Hidalgo', 14),
('San Martín Huamelúlpam', 20),
('San Martín Itunyoso', 20),
('San Martín Lachilá', 20),
('San Martín Peras', 20),
('San Martín Texmelucan', 21),
('San Martín Tilcajete', 20),
('San Martín Totoltepec', 21),
('San Martín Toxpalan', 20),
('San Martín Zacatepec', 20),
('San Mateo Atenco', 15),
('San Mateo Cajonos', 20),
('San Mateo del Mar', 20),
('San Mateo Etlatongo', 20),
('San Mateo Nejápam', 20),
('San Mateo Peñasco', 20),
('San Mateo Piñas', 20),
('San Mateo Río Hondo', 20),
('San Mateo Sindihui', 20),
('San Mateo Tlapiltepec', 20),
('San Mateo Yoloxochitlán', 20),
('San Mateo Yucutindoo', 20),
('San Matías Tlalancaleca', 21),
('San Melchor Betaza', 20),
('San Miguel Achiutla', 20),
('San Miguel Ahuehuetitlán', 20),
('San Miguel Aloápam', 20),
('San Miguel Amatitlán', 20),
('San Miguel Amatlán', 20),
('San Miguel Chicahua', 20),
('San Miguel Chimalapa', 20),
('San Miguel Coatlán', 20),
('San Miguel de Allende', 11),
('San Miguel de Horcasitas', 26),
('San Miguel del Puerto', 20),
('San Miguel del Río', 20),
('San Miguel Ejutla', 20),
('San Miguel el Alto', 14),
('San Miguel el Grande', 20),
('San Miguel Huautla', 20),
('San Miguel Ixitlán', 21),
('San Miguel Mixtepec', 20),
('San Miguel Panixtlahuaca', 20),
('San Miguel Peras', 20),
('San Miguel Piedras', 20),
('San Miguel Quetzaltepec', 20),
('San Miguel Santa Flor', 20),
('San Miguel Soyaltepec', 20),
('San Miguel Suchixtepec', 20),
('San Miguel Tecomatlán', 20),
('San Miguel Tenango', 20),
('San Miguel Tequixtepec', 20),
('San Miguel Tilquiápam', 20),
('San Miguel Tlacamama', 20),
('San Miguel Tlacotepec', 20),
('San Miguel Totolapan', 12),
('San Miguel Tulancingo', 20),
('San Miguel Xoxtla', 21),
('San Miguel Yotao', 20),
('San Nicolás', 20),
('San Nicolás', 28),
('San Nicolás Buenos Aires', 21),
('San Nicolás de los Garza', 19),
('San Nicolás de los Ranchos', 21),
('San Nicolás Hidalgo', 20),
('San Nicolás Tolentino', 24),
('San Pablo Anicano', 21),
('San Pablo Coatlán', 20),
('San Pablo Cuatro Venados', 20),
('San Pablo del Monte', 29),
('San Pablo Etla', 20),
('San Pablo Huitzo', 20),
('San Pablo Huixtepec', 20),
('San Pablo Macuiltianguis', 20),
('San Pablo Tijaltepec', 20),
('San Pablo Villa de Mitla', 20),
('San Pablo Yaganiza', 20),
('San Pedro', 5),
('San Pedro Amuzgos', 20),
('San Pedro Apóstol', 20),
('San Pedro Atoyac', 20),
('San Pedro Cajonos', 20),
('San Pedro Cholula', 21),
('San Pedro Comitancillo', 20),
('San Pedro Coxcaltepec Cántaros', 20),
('San Pedro de la Cueva', 26),
('San Pedro del Gallo', 10),
('San Pedro el Alto', 20),
('San Pedro Garza García', 19),
('San Pedro Huamelula', 20),
('San Pedro Huilotepec', 20),
('San Pedro Ixcatlán', 20),
('San Pedro Ixtlahuaca', 20),
('San Pedro Jaltepetongo', 20),
('San Pedro Jicayán', 20),
('San Pedro Jocotipac', 20),
('San Pedro Juchatengo', 20),
('San Pedro Lagunillas', 18),
('San Pedro Mártir', 20),
('San Pedro Mártir Quiechapa', 20),
('San Pedro Mártir Yucuxaco', 20),
('San Pedro Mixtepec -Dto. 22 -', 20),
('San Pedro Mixtepec -Dto. 26 -', 20),
('San Pedro Molinos', 20),
('San Pedro Nopala', 20),
('San Pedro Ocopetatillo', 20),
('San Pedro Ocotepec', 20),
('San Pedro Pochutla', 20),
('San Pedro Quiatoni', 20),
('San Pedro Sochiápam', 20),
('San Pedro Tapanatepec', 20),
('San Pedro Taviche', 20),
('San Pedro Teozacoalco', 20),
('San Pedro Teutila', 20),
('San Pedro Tidaá', 20),
('San Pedro Tlaquepaque', 14),
('San Pedro Topiltepec', 20),
('San Pedro Totolápam', 20),
('San Pedro y San Pablo Ayutla', 20),
('San Pedro y San Pablo Teposcolula', 20),
('San Pedro y San Pablo Tequixtepec', 20),
('San Pedro Yaneri', 20),
('San Pedro Yeloixtlahuaca', 21),
('San Pedro Yólox', 20),
('San Pedro Yucunama', 20),
('San Rafael', 30),
('San Raymundo Jalpan', 20),
('San Salvador', 13),
('San Salvador el Seco', 21),
('San Salvador el Verde', 21),
('San Salvador Huixcolotla', 21),
('San Sebastián Abasolo', 20),
('San Sebastián Coatlán', 20),
('San Sebastián del Oeste', 14),
('San Sebastián Ixcapa', 20),
('San Sebastián Nicananduta', 20),
('San Sebastián Río Hondo', 20),
('San Sebastián Tecomaxtlahuaca', 20),
('San Sebastián Teitipac', 20),
('San Sebastián Tlacotepec', 21),
('San Sebastián Tutla', 20),
('San Simón Almolongas', 20),
('San Simón de Guerrero', 15),
('San Simón Zahuatlán', 20),
('San Vicente Coatlán', 20),
('San Vicente Lachixío', 20),
('San Vicente Nuñú', 20),
('San Vicente Tancuayalab', 24),
('Sanahcat', 31),
('Sanctórum de Lázaro Cárdenas', 29),
('Santa Ana', 20),
('Santa Ana', 26),
('Santa Ana Ateixtlahuaca', 20),
('Santa Ana Cuauhtémoc', 20),
('Santa Ana del Valle', 20),
('Santa Ana Maya', 16),
('Santa Ana Nopalucan', 29),
('Santa Ana Tavela', 20),
('Santa Ana Tlapacoyan', 20),
('Santa Ana Yareni', 20),
('Santa Ana Zegache', 20),
('Santa Apolonia Teacalco', 29),
('Santa Bárbara', 8),
('Santa Catalina Quierí', 20),
('Santa Catarina', 11),
('Santa Catarina', 19),
('Santa Catarina', 24),
('Santa Catarina Ayometla', 29),
('Santa Catarina Cuixtla', 20),
('Santa Catarina Ixtepeji', 20),
('Santa Catarina Juquila', 20),
('Santa Catarina Lachatao', 20),
('Santa Catarina Loxicha', 20),
('Santa Catarina Mechoacán', 20),
('Santa Catarina Minas', 20),
('Santa Catarina Quiané', 20),
('Santa Catarina Quioquitani', 20),
('Santa Catarina Tayata', 20),
('Santa Catarina Ticuá', 20),
('Santa Catarina Tlaltempan', 21),
('Santa Catarina Yosonotú', 20),
('Santa Catarina Zapoquila', 20),
('Santa Clara', 10),
('Santa Cruz', 26),
('Santa Cruz Acatepec', 20),
('Santa Cruz Amilpas', 20),
('Santa Cruz de Bravo', 20),
('Santa Cruz de Juventino Rosas', 11),
('Santa Cruz Itundujia', 20),
('Santa Cruz Mixtepec', 20),
('Santa Cruz Nundaco', 20),
('Santa Cruz Papalutla', 20),
('Santa Cruz Quilehtla', 29),
('Santa Cruz Tacache de Mina', 20),
('Santa Cruz Tacahua', 20),
('Santa Cruz Tayata', 20),
('Santa Cruz Tlaxcala', 29),
('Santa Cruz Xitla', 20),
('Santa Cruz Xoxocotlán', 20),
('Santa Cruz Zenzontepec', 20),
('Santa Elena', 31),
('Santa Gertrudis', 20),
('Santa Inés Ahuatempan', 21),
('Santa Inés de Zaragoza', 20),
('Santa Inés del Monte', 20),
('Santa Inés Yatzeche', 20),
('Santa Isabel', 8),
('Santa Isabel Cholula', 21),
('Santa Isabel Xiloxoxtla', 29);

INSERT INTO CAT_CIUDAD (NOMBRE, FK_ENTIDAD_FEDERATIVA) VALUES
('Santa Lucía del Camino', 20),
('Santa Lucía Miahuatlán', 20),
('Santa Lucía Monteverde', 20),
('Santa Lucía Ocotlán', 20),
('Santa Magdalena Jicotlán', 20),
('Santa María Alotepec', 20),
('Santa María Apazco', 20),
('Santa María Atzompa', 20),
('Santa María Camotlán', 20),
('Santa María Chachoápam', 20),
('Santa María Chilchotla', 20),
('Santa María Chimalapa', 20),
('Santa María Colotepec', 20),
('Santa María Cortijo', 20),
('Santa María Coyotepec', 20),
('Santa María de la Paz', 32),
('Santa María de los Ángeles', 14),
('Santa María del Oro', 18),
('Santa María del Oro', 14),
('Santa María del Río', 24),
('Santa María del Rosario', 20),
('Santa María del Tule', 20),
('Santa María Ecatepec', 20),
('Santa María Guelacé', 20),
('Santa María Guienagati', 20),
('Santa María Huatulco', 20),
('Santa María Huazolotitlán', 20),
('Santa María Ipalapa', 20),
('Santa María Ixcatlán', 20),
('Santa María Jacatepec', 20),
('Santa María Jalapa del Marqués', 20),
('Santa María Jaltianguis', 20),
('Santa María la Asunción', 20),
('Santa María Lachixío', 20),
('Santa María Mixtequilla', 20),
('Santa María Nativitas', 20),
('Santa María Nduayaco', 20),
('Santa María Ozolotepec', 20),
('Santa María Pápalo', 20),
('Santa María Peñoles', 20),
('Santa María Petapa', 20),
('Santa María Quiegolani', 20),
('Santa María Sola', 20),
('Santa María Tataltepec', 20),
('Santa María Tecomavaca', 20),
('Santa María Temaxcalapa', 20),
('Santa María Temaxcaltepec', 20),
('Santa María Teopoxco', 20),
('Santa María Tepantlali', 20),
('Santa María Texcatitlán', 20),
('Santa María Tlahuitoltepec', 20),
('Santa María Tlalixtac', 20),
('Santa María Tonameca', 20),
('Santa María Totolapilla', 20),
('Santa María Xadani', 20),
('Santa María Yalina', 20),
('Santa María Yavesía', 20),
('Santa María Yolotepec', 20),
('Santa María Yosoyúa', 20),
('Santa María Yucuhiti', 20),
('Santa María Zacatepec', 20),
('Santa María Zaniza', 20),
('Santa María Zoquitlán', 20),
('Santiago', 19),
('Santiago Amoltepec', 20),
('Santiago Apoala', 20),
('Santiago Apóstol', 20),
('Santiago Astata', 20),
('Santiago Atitlán', 20),
('Santiago Ayuquililla', 20),
('Santiago Cacaloxtepec', 20),
('Santiago Camotlán', 20),
('Santiago Chazumba', 20),
('Santiago Choápam', 20),
('Santiago Comaltepec', 20),
('Santiago de Anaya', 13),
('Santiago del Río', 20),
('Santiago el Pinar', 7),
('Santiago Huajolotitlán', 20),
('Santiago Huauclilla', 20),
('Santiago Ihuitlán Plumas', 20),
('Santiago Ixcuintepec', 20),
('Santiago Ixcuintla', 18),
('Santiago Ixtayutla', 20),
('Santiago Jamiltepec', 20),
('Santiago Jocotepec', 20),
('Santiago Juxtlahuaca', 20),
('Santiago Lachiguiri', 20),
('Santiago Lalopa', 20),
('Santiago Laollaga', 20),
('Santiago Laxopa', 20),
('Santiago Llano Grande', 20),
('Santiago Maravatío', 11),
('Santiago Matatlán', 20),
('Santiago Miahuatlán', 21),
('Santiago Miltepec', 20),
('Santiago Minas', 20),
('Santiago Nacaltepec', 20),
('Santiago Nejapilla', 20),
('Santiago Niltepec', 20),
('Santiago Nundiche', 20),
('Santiago Nuyoó', 20),
('Santiago Papasquiaro', 10),
('Santiago Pinotepa Nacional', 20),
('Santiago Sochiapan', 30),
('Santiago Suchilquitongo', 20),
('Santiago Tamazola', 20),
('Santiago Tapextla', 20),
('Santiago Tenango', 20),
('Santiago Tepetlapa', 20),
('Santiago Tetepec', 20),
('Santiago Texcalcingo', 20),
('Santiago Textitlán', 20),
('Santiago Tilantongo', 20),
('Santiago Tillo', 20),
('Santiago Tlazoyaltepec', 20),
('Santiago Tulantepec de Lugo Guerrero', 13),
('Santiago Tuxtla', 30),
('Santiago Xanica', 20),
('Santiago Xiacuí', 20),
('Santiago Yaitepec', 20),
('Santiago Yaveo', 20),
('Santiago Yolomécatl', 20),
('Santiago Yosondúa', 20),
('Santiago Yucuyachi', 20),
('Santiago Zacatepec', 20),
('Santiago Zoochila', 20),
('Santo Domingo', 24),
('Santo Domingo Albarradas', 20),
('Santo Domingo Armenta', 20),
('Santo Domingo Chihuitán', 20),
('Santo Domingo de Morelos', 20),
('Santo Domingo Ingenio', 20),
('Santo Domingo Ixcatlán', 20),
('Santo Domingo Nuxaá', 20),
('Santo Domingo Ozolotepec', 20),
('Santo Domingo Petapa', 20),
('Santo Domingo Roayaga', 20),
('Santo Domingo Tehuantepec', 20),
('Santo Domingo Teojomulco', 20),
('Santo Domingo Tepuxtepec', 20),
('Santo Domingo Tlatayápam', 20),
('Santo Domingo Tomaltepec', 20),
('Santo Domingo Tonalá', 20),
('Santo Domingo Tonaltepec', 20),
('Santo Domingo Xagacía', 20),
('Santo Domingo Yanhuitlán', 20),
('Santo Domingo Yodohino', 20),
('Santo Domingo Zanatepec', 20),
('Santo Tomás', 15),
('Santo Tomás Hueyotlipan', 21),
('Santo Tomás Jalieza', 20),
('Santo Tomás Mazaltepec', 20),
('Santo Tomás Ocotepec', 20),
('Santo Tomás Tamazulapan', 20),
('Santos Reyes Nopala', 20),
('Santos Reyes Pápalo', 20),
('Santos Reyes Tepejillo', 20),
('Santos Reyes Yucuná', 20),
('Sáric', 26),
('Satevó', 8),
('Saucillo', 8),
('Sayula', 14),
('Sayula de Alemán', 30),
('Senguio', 16),
('Seyé', 31),
('Sierra Mojada', 5),
('Silacayoápam', 20),
('Silao de la Victoria', 11),
('Siltepec', 7),
('Simojovel', 7),
('Sinaloa', 25),
('Sinanché', 31),
('Singuilucan', 13),
('Sitalá', 7),
('Sitio de Xitlapehua', 20),
('Sochiapa', 30),
('Socoltenango', 7),
('Soconusco', 30),
('Soledad Atzompa', 30),
('Soledad de Doblado', 30),
('Soledad de Graciano Sánchez', 24),
('Soledad Etla', 20),
('Solidaridad', 23),
('Solosuchiapa', 7),
('Soltepec', 21),
('Sombrerete', 32),
('Soteapan', 30),
('Soto la Marina', 28),
('Sotuta', 31),
('Soyaló', 7),
('Soyaniquilpan de Juárez', 15),
('Soyopa', 26),
('Suaqui Grande', 26),
('Suchiapa', 7),
('Suchiate', 7),
('Súchil', 10),
('Sucilá', 31),
('Sudzal', 31),
('Sultepec', 15),
('Suma', 31),
('Sunuapa', 7),
('Susticacán', 32),
('Susupuato', 16),
('Tabasco', 32),
('Tacámbaro', 16),
('Tacotalpa', 27),
('Tahdziú', 31),
('Tahmek', 31),
('Tala', 14),
('Talpa de Allende', 14),
('Tamalín', 30),
('Tamasopo', 24),
('Tamazula', 10),
('Tamazula de Gordiano', 14),
('Tamazulápam del Espíritu Santo', 20),
('Tamazunchale', 24),
('Tamiahua', 30),
('Tampacán', 24),
('Tampamolón Corona', 24),
('Tampico', 28),
('Tampico Alto', 30),
('Tamuín', 24),
('Tancanhuitz', 24),
('Tancítaro', 16),
('Tancoco', 30),
('Tanetze de Zaragoza', 20),
('Tangamandapio', 16),
('Tangancícuaro', 16),
('Tanhuato', 16),
('Taniche', 20),
('Tanlajás', 24),
('Tanquián de Escobedo', 24),
('Tantima', 30),
('Tantoyuca', 30),
('Tapachula', 7),
('Tapalapa', 7),
('Tapalpa', 14),
('Tapilula', 7),
('Tarandacuao', 11),
('Taretan', 16),
('Tarímbaro', 16),
('Tarimoro', 11),
('Tasquillo', 13),
('Tatahuicapan de Juárez', 30),
('Tataltepec de Valdés', 20),
('Tatatila', 30),
('Taxco de Alarcón', 12),
('Teabo', 31),
('Teapa', 27),
('Tecali de Herrera', 21),
('Tecalitlán', 14),
('Tecámac', 15),
('Tecamachalco', 21),
('Tecate', 2),
('Techaluta de Montenegro', 14),
('Tecoanapa', 12),
('Tecoh', 31),
('Tecolotlán', 14),
('Tecolutla', 30),
('Tecomán', 6),
('Tecomatlán', 21),
('Tecozautla', 13),
('Técpan de Galeana', 12),
('Tecpatán', 7),
('Tecuala', 18),
('Tehuacán', 21),
('Tehuipango', 30),
('Tehuitzingo', 21),
('Tejupilco', 15),
('Tekal de Venegas', 31),
('Tekantó', 31),
('Tekax', 31),
('Tekit', 31),
('Tekom', 31),
('Telchac Pueblo', 31),
('Telchac Puerto', 31),
('Teloloapan', 12),
('Temamatla', 15),
('Temascalapa', 15),
('Temascalcingo', 15),
('Temascaltepec', 15),
('Temax', 31),
('Temixco', 17),
('Temoac', 17),
('Temoaya', 15),
('Temósachic', 8),
('Temozón', 31),
('Tempoal', 30),
('Tenabo', 4),
('Tenamaxtlán', 14),
('Tenampa', 30),
('Tenampulco', 21),
('Tenancingo', 29),
('Tenancingo', 15),
('Tenango de Doria', 13),
('Tenango del Aire', 15),
('Tenango del Valle', 15),
('Tenejapa', 7),
('Tenochtitlán', 30),
('Tenosique', 27),
('Teocaltiche', 14),
('Teocelo', 30),
('Teococuilco de Marcos Pérez', 20),
('Teocuitatlán de Corona', 14),
('Teolocholco', 29),
('Teoloyucan', 15),
('Teopantlán', 21),
('Teopisca', 7),
('Teotihuacán', 15),
('Teotitlán de Flores Magón', 20),
('Teotitlán del Valle', 20),
('Teotlalco', 21),
('Teotongo', 20),
('Tepache', 26),
('Tepakán', 31),
('Tepalcatepec', 16),
('Tepalcingo', 17),
('Tepanco de López', 21),
('Tepango de Rodríguez', 21),
('Tepatitlán de Morelos', 14),
('Tepatlaxco', 30),
('Tepatlaxco de Hidalgo', 21),
('Tepeaca', 21),
('Tepeapulco', 13),
('Tepechitlán', 32),
('Tepecoacuilco de Trujano', 12),
('Tepehuacán de Guerrero', 13),
('Tepehuanes', 10),
('Tepeji del Río de Ocampo', 13),
('Tepelmeme Villa de Morelos', 20),
('Tepemaxalco', 21),
('Tepeojuma', 21),
('Tepetitla de Lardizábal', 29),
('Tepetitlán', 13),
('Tepetlán', 30),
('Tepetlaoxtoc', 15),
('Tepetlixpa', 15),
('Tepetongo', 32),
('Tepetzintla', 21),
('Tepetzintla', 30),
('Tepexco', 21),
('Tepexi de Rodríguez', 21),
('Tepeyahualco', 21),
('Tepeyahualco de Cuauhtémoc', 21),
('Tepeyanco', 29),
('Tepezalá', 1),
('Tepic', 18),
('Tepotzotlán', 15),
('Tepoztlán', 17),
('Tequila', 14),
('Tequila', 30),
('Tequisquiapan', 22),
('Tequixquiac', 15),
('Terrenate', 29),
('Tetecala', 17),
('Tetela de Ocampo', 21),
('Tetela del Volcán', 17),
('Teteles de Avila Castillo', 21),
('Tetepango', 13),
('Tetipac', 12),
('Tetiz', 31),
('Tetla de la Solidaridad', 29),
('Tetlatlahuca', 29),
('Teuchitlán', 14),
('Teúl de González Ortega', 32),
('Texcaltitlán', 15),
('Texcalyacac', 15),
('Texcatepec', 30),
('Texcoco', 15),
('Texhuacán', 30),
('Texistepec', 30),
('Teya', 31),
('Teziutlán', 21),
('Tezoatlán de Segura y Luna', 20),
('Tezonapa', 30),
('Tezontepec de Aldama', 13),
('Tezoyuca', 15),
('Tianguismanalco', 21),
('Tianguistenco', 15),
('Tianguistengo', 13),
('Ticul', 31),
('Tierra Blanca', 11),
('Tierra Blanca', 30),
('Tierra Nueva', 24),
('Tihuatlán', 30),
('Tijuana', 2),
('Tila', 7),
('Tilapa', 21),
('Timilpan', 15),
('Timucuy', 31),
('Tingambato', 16),
('Tingüindín', 16),
('Tinum', 31),
('Tiquicheo de Nicolás Romero', 16),
('Tixcacalcupul', 31),
('Tixkokob', 31),
('Tixmehuac', 31),
('Tixpéhual', 31),
('Tixtla de Guerrero', 12),
('Tizapán el Alto', 14),
('Tizayuca', 13),
('Tizimín', 31),
('Tlachichilco', 30),
('Tlachichuca', 21),
('Tlacoachistlahuaca', 12),
('Tlacoapa', 12),
('Tlacojalpan', 30),
('Tlacolula de Matamoros', 20),
('Tlacolulan', 30),
('Tlacotalpan', 30),
('Tlacotepec de Benito Juárez', 21),
('Tlacotepec de Mejía', 30),
('Tlacotepec Plumas', 20),
('Tlacuilotepec', 21),
('Tláhuac', 9),
('Tlahualilo', 10),
('Tlahuapan', 21),
('Tlahuelilpan', 13),
('Tlahuiltepa', 13),
('Tlajomulco de Zúñiga', 14),
('Tlalchapa', 12),
('Tlalixcoyan', 30),
('Tlalixtac de Cabrera', 20),
('Tlalixtaquilla de Maldonado', 12),
('Tlalmanalco', 15),
('Tlalnelhuayocan', 30),
('Tlalnepantla', 17),
('Tlalnepantla de Baz', 15),
('Tlalpan', 9),
('Tlalpujahua', 16),
('Tlaltenango', 21),
('Tlaltenango de Sánchez Román', 32),
('Tlaltetela', 30),
('Tlaltizapán de Zapata', 17),
('Tlanalapa', 13),
('Tlanchinol', 13),
('Tlanepantla', 21),
('Tlaola', 21),
('Tlapa de Comonfort', 12),
('Tlapacoya', 21),
('Tlapacoyan', 30),
('Tlapanalá', 21),
('Tlapehuala', 12),
('Tlaquilpa', 30),
('Tlaquiltenango', 17),
('Tlatlauquitepec', 21),
('Tlatlaya', 15),
('Tlaxcala', 29),
('Tlaxco', 29),
('Tlaxco', 21),
('Tlaxcoapan', 13),
('Tlayacapan', 17),
('Tlazazalca', 16),
('Tlilapan', 30),
('Tocatlán', 29),
('Tochimilco', 21),
('Tochtepec', 21),
('Tocumbo', 16),
('Tolcayuca', 13),
('Tolimán', 22),
('Tolimán', 14),
('Toluca', 15),
('Tomatlán', 30),
('Tomatlán', 14),
('Tonalá', 7),
('Tonalá', 14),
('Tonanitla', 15),
('Tonatico', 15),
('Tonaya', 14),
('Tonayán', 30),
('Tonila', 14),
('Topia', 10),
('Torreón', 5),
('Totatiche', 14),
('Totolac', 29),
('Totolapa', 7),
('Totolapan', 17),
('Totoltepec de Guerrero', 21),
('Totontepec Villa de Morelos', 20),
('Tototlán', 14),
('Totutla', 30),
('Trancoso', 32),
('Tres Valles', 30),
('Trincheras', 26),
('Trinidad García de la Cadena', 32),
('Trinidad Zaachila', 20),
('Tubutama', 26),
('Tula', 28),
('Tula de Allende', 13),
('Tulancingo de Bravo', 13),
('Tulcingo', 21),
('Tultepec', 15),
('Tultitlán', 15),
('Tulum', 23),
('Tumbalá', 7),
('Tumbiscatío', 16),
('Tunkás', 31),
('Turicato', 16),
('Tuxcacuesco', 14),
('Tuxcueca', 14),
('Tuxpan', 16),
('Tuxpan', 30),
('Tuxpan', 14),
('Tuxpan', 18),
('Tuxtilla', 30),
('Tuxtla Chico', 7),
('Tuxtla Gutiérrez', 7),
('Tuzamapan de Galeana', 21),
('Tuzantán', 7),
('Tuzantla', 16),
('Tzicatlacoyan', 21),
('Tzimol', 7),
('Tzintzuntzan', 16),
('Tzitzio', 16),
('Tzompantepec', 29),
('Tzucacab', 31),
('Uayma', 31),
('Ucú', 31),
('Umán', 31),
('Unión de San Antonio', 14),
('Unión de Tula', 14),
('Unión Hidalgo', 20),
('Unión Juárez', 7),
('Ures', 26),
('Uriangato', 11),
('Urique', 8),
('Ursulo Galván', 30),
('Uruachi', 8),
('Uruapan', 16),
('Uxpanapa', 30),
('Valerio Trujano', 20),
('Valladolid', 31),
('Valle de Bravo', 15),
('Valle de Chalco Solidaridad', 15),
('Valle de Guadalupe', 14),
('Valle de Juárez', 14),
('Valle de Santiago', 11),
('Valle de Zaragoza', 8),
('Valle Hermoso', 28),
('Vallecillo', 19),
('Valparaíso', 32),
('Vanegas', 24),
('Vega de Alatorre', 30),
('Venado', 24),
('Venustiano Carranza', 7),
('Venustiano Carranza', 9),
('Venustiano Carranza', 16),
('Venustiano Carranza', 21),
('Veracruz', 30),
('Vetagrande', 32),
('Vicente Guerrero', 10),
('Vicente Guerrero', 21),
('Victoria', 28),
('Victoria', 11),
('Viesca', 5),
('Villa Aldama', 30),
('Villa Comaltitlán', 7),
('Villa Corona', 14),
('Villa Corzo', 7),
('Villa de Allende', 15),
('Villa de Álvarez', 6),
('Villa de Arista', 24),
('Villa de Arriaga', 24),
('Villa de Chilapa de Díaz', 20),
('Villa de Cos', 32),
('Villa de Etla', 20),
('Villa de Guadalupe', 24),
('Villa de la Paz', 24),
('Villa de Ramos', 24),
('Villa de Reyes', 24),
('Villa de Tamazulápam del Progreso', 20),
('Villa de Tezontepec', 13),
('Villa de Tututepec', 20),
('Villa de Zaachila', 20),
('Villa del Carbón', 15),
('Villa Díaz Ordaz', 20),
('Villa García', 32),
('Villa González Ortega', 32),
('Villa Guerrero', 14),
('Villa Guerrero', 15),
('Villa Hidalgo', 24),
('Villa Hidalgo', 14),
('Villa Hidalgo', 20),
('Villa Hidalgo', 26),
('Villa Hidalgo', 32),
('Villa Juárez', 24),
('Villa Pesqueira', 26),
('Villa Purificación', 14),
('Villa Sola de Vega', 20),
('Villa Talea de Castro', 20),
('Villa Tejúpam de la Unión', 20),
('Villa Unión', 5),
('Villa Victoria', 15),
('Villaflores', 7),
('Villagrán', 28),
('Villagrán', 11),
('Villaldama', 19),
('Villamar', 16),
('Villanueva', 32),
('Vista Hermosa', 16),
('Xalapa', 30),
('Xalatlaco', 15),
('Xalisco', 18),
('Xaloztoc', 29),
('Xalpatláhuac', 12),
('Xaltocan', 29),
('Xayacatlán de Bravo', 21),
('Xichú', 11),
('Xico', 30),
('Xicohtzinco', 29),
('Xicoténcatl', 28),
('Xicotepec', 21),
('Xicotlán', 21),
('Xilitla', 24),
('Xiutetelco', 21),
('Xocchel', 31),
('Xochiapulco', 21),
('Xochiatipan', 13),
('Xochicoatlán', 13),
('Xochihuehuetlán', 12),
('Xochiltepec', 21),
('Xochimilco', 9),
('Xochistlahuaca', 12),
('Xochitepec', 17),
('Xochitlán de Vicente Suárez', 21),
('Xochitlán Todos Santos', 21),
('Xonacatlán', 15),
('Xoxocotla', 30),
('Yahualica', 13),
('Yahualica de González Gallo', 14),
('Yajalón', 7),
('Yanga', 30),
('Yaonáhuac', 21),
('Yauhquemehcan', 29),
('Yautepec', 17),
('Yaxcabá', 31),
('Yaxe', 20),
('Yaxkukul', 31),
('Yecapixtla', 17),
('Yécora', 26),
('Yecuatla', 30),
('Yehualtepec', 21),
('Yobaín', 31),
('Yogana', 20),
('Yurécuaro', 16),
('Yuriria', 11),
('Yutanduchi de Guerrero', 20),
('Zacapala', 21),
('Zacapoaxtla', 21),
('Zacapu', 16),
('Zacatecas', 32),
('Zacatelco', 29),
('Zacatepec', 17),
('Zacatlán', 21),
('Zacazonapan', 15),
('Zacoalco de Torres', 14),
('Zacualpan', 15),
('Zacualpan', 30),
('Zacualpan de Amilpas', 17),
('Zacualtipán de Ángeles', 13),
('Zamora', 16),
('Zapopan', 14),
('Zapotiltic', 14),
('Zapotitlán', 21),
('Zapotitlán de Méndez', 21),
('Zapotitlán de Vadillo', 14),
('Zapotitlán Lagunas', 20),
('Zapotitlán Palmas', 20),
('Zapotitlán Tablas', 12),
('Zapotlán de Juárez', 13),
('Zapotlán del Rey', 14),
('Zapotlán el Grande', 14),
('Zapotlanejo', 14),
('Zaragoza', 30),
('Zaragoza', 24),
('Zaragoza', 21),
('Zaragoza', 5),
('Zautla', 21),
('Zempoala', 13),
('Zentla', 30),
('Zihuatanejo de Azueta', 12),
('Zihuateutla', 21),
('Ziltlaltépec de Trinidad Sánchez Santos', 29),
('Zimapán', 13),
('Zimatlán de Álvarez', 20),
('Zinacantán', 7),
('Zinacantepec', 15),
('Zinacatepec', 21),
('Zináparo', 16),
('Zinapécuaro', 16),
('Ziracuaretiro', 16),
('Zirándaro', 12),
('Zitácuaro', 16),
('Zitlala', 12),
('Zongolica', 30),
('Zongozotla', 21),
('Zontecomatlán de López y Fuentes', 30),
('Zoquiapan', 21),
('Zoquitlán', 21),
('Zozocolco de Hidalgo', 30),
('Zumpahuacán', 15),
('Zumpango', 15);

