/* VISTA DE DATOS DE PERFIL DE ALUMNO */
DROP VIEW IF EXISTS VW_PERFIL_ALUMNO;
CREATE VIEW VW_PERFIL_ALUMNO AS
SELECT CAT_USUARIO.PK_USUARIO,
       CAT_USUARIO.FK_CARRERA,
       CAT_USUARIO.FK_COLONIA,
       CAT_USUARIO.FK_ESTADO_CIVIL,
       CAT_USUARIO.FK_SITUACION_RESIDENCIA,
       CAT_USUARIO.FK_CODIGO_POSTAL,
       CAT_USUARIO.PERFIL_COMPLETO,
       CAT_USUARIO.NOMBRE,
       CAT_USUARIO.PRIMER_APELLIDO,
       CAT_USUARIO.SEGUNDO_APELLIDO,
       CAT_USUARIO.CURP,
       CAT_USUARIO.NUMERO_CONTROL,
       CAT_USUARIO.SEMESTRE,
       CAT_USUARIO.FECHA_NACIMIENTO,
       CAT_USUARIO.SEXO,
       CAT_USUARIO.CORREO1,
       CAT_USUARIO.CORREO2,
       CAT_USUARIO.CORREO_INSTITUCIONAL,
       CAT_USUARIO.TELEFONO_CASA,
       CAT_USUARIO.TELEFONO_MOVIL,
       CAT_USUARIO.CALLE,
       CAT_USUARIO.NUMERO_EXTERIOR,
       CAT_USUARIO.NUMERO_INTERIOR,
       CAT_USUARIO.NOMBRE_CONTACTO,
       CAT_USUARIO.PARENTESCO_CONTACTO,
       CAT_USUARIO.TELEFONO_CONTACTO,
       CAT_USUARIO.CORREO_CONTACTO,
       CAT_USUARIO.PK_ENCRIPTADA,
       CAT_USUARIO.FOTO_PERFIL,

       CAT_CODIGO_POSTAL.NUMERO        AS CODIGO_POSTAL,
       CAT_CARRERA.NOMBRE              AS CARRERA,
       CASE
           WHEN SEXO IS NULL THEN ''
           WHEN SEXO = 1 THEN 'MASCULINO'
           WHEN SEXO = 2 THEN 'FEMENINO'
           END                         AS TEXTO_SEXO,
       CAT_ESTADO_CIVIL.NOMBRE         AS ESTADO_CIVIL,
       CAT_SITUACION_RESIDENCIA.NOMBRE AS SITUACION_RESIDENCIA,
       CAT_ENTIDAD_FEDERATIVA.NOMBRE   AS ENTIDAD_FEDERATIVA,
       CAT_CIUDAD.NOMBRE               AS CIUDAD,
       CAT_COLONIA.NOMBRE              AS COLONIA
FROM TR_COLONIA_CODIGO_POSTAL
         LEFT JOIN CAT_COLONIA
                   ON TR_COLONIA_CODIGO_POSTAL.FK_COLONIA = CAT_COLONIA.PK_COLONIA
         LEFT JOIN CAT_CODIGO_POSTAL
                   ON TR_COLONIA_CODIGO_POSTAL.FK_CODIGO_POSTAL = CAT_CODIGO_POSTAL.PK_CODIGO_POSTAL
         LEFT JOIN CAT_CIUDAD
                   ON CAT_CODIGO_POSTAL.FK_CIUDAD = CAT_CIUDAD.PK_CIUDAD
         LEFT JOIN CAT_ENTIDAD_FEDERATIVA
                   ON CAT_CIUDAD.FK_ENTIDAD_FEDERATIVA = CAT_ENTIDAD_FEDERATIVA.PK_ENTIDAD_FEDERATIVA
         LEFT JOIN CAT_PAIS
                   ON CAT_ENTIDAD_FEDERATIVA.FK_PAIS = CAT_PAIS.PK_PAIS
         RIGHT JOIN CAT_USUARIO
                    ON CAT_CODIGO_POSTAL.PK_CODIGO_POSTAL = CAT_USUARIO.FK_CODIGO_POSTAL
         LEFT JOIN CAT_CARRERA
                   ON CAT_USUARIO.FK_CARRERA = CAT_CARRERA.PK_CARRERA
         LEFT JOIN CAT_ESTADO_CIVIL
                   ON CAT_USUARIO.FK_ESTADO_CIVIL = CAT_ESTADO_CIVIL.PK_ESTADO_CIVIL
         LEFT JOIN CAT_SITUACION_RESIDENCIA
                   ON CAT_USUARIO.FK_SITUACION_RESIDENCIA = CAT_SITUACION_RESIDENCIA.PK_SITUACION_RESIDENCIA;

/* VISTA DE DATOS DE USAURIO */
DROP VIEW IF EXISTS VW_USUARIOS;
CREATE VIEW VW_USUARIOS AS
SELECT
    -- DATOS USUARIO
    CAT_USUARIO.PK_USUARIO,
    CAT_USUARIO.PK_ENCRIPTADA,
    CAT_USUARIO.NOMBRE,
    CAT_USUARIO.PRIMER_APELLIDO,
    CAT_USUARIO.SEGUNDO_APELLIDO,
    CAT_USUARIO.CURP,
    CAT_USUARIO.NUMERO_CONTROL,
    CAT_USUARIO.SEMESTRE,
    CAT_USUARIO.FECHA_NACIMIENTO,
    CAT_USUARIO.SEXO,
    CASE
        WHEN SEXO IS NULL THEN ''
        WHEN SEXO = 1 THEN 'MASCULINO'
        WHEN SEXO = 2 THEN 'FEMENINO'
        END                         AS TEXTO_SEXO,
    CAT_USUARIO.CORREO1,
    CAT_USUARIO.CORREO2,
    CAT_USUARIO.CORREO_INSTITUCIONAL,
    CAT_USUARIO.TELEFONO_CASA,
    CAT_USUARIO.TELEFONO_MOVIL,
    CAT_USUARIO.CALLE,
    CAT_USUARIO.NUMERO_EXTERIOR,
    CAT_USUARIO.NUMERO_INTERIOR,
    CAT_USUARIO.NOMBRE_CONTACTO,
    CAT_USUARIO.PARENTESCO_CONTACTO,
    CAT_USUARIO.TELEFONO_CONTACTO,
    CAT_USUARIO.CORREO_CONTACTO,
    CAT_USUARIO.TIPO_USUARIO,
    CAT_USUARIO.PERFIL_COMPLETO,
    CAT_USUARIO.FOTO_PERFIL,
    CAT_USUARIO.BORRADO,

    -- DATOS CARRERA
    CAT_USUARIO.FK_CARRERA,
    CAT_CARRERA.NOMBRE              AS CARRERA,

    -- DATOS CODIGO POSTAL
    CAT_USUARIO.FK_CODIGO_POSTAL,
    CAT_CODIGO_POSTAL.NUMERO        AS CODIGO_POSTAL,

    -- DATOS ESTADO CIVIL
    CAT_USUARIO.FK_ESTADO_CIVIL,
    CAT_ESTADO_CIVIL.NOMBRE         AS ESTADO_CIVIL,

    -- DATOS SITUACION RESIDENCIA
    CAT_USUARIO.FK_SITUACION_RESIDENCIA,
    CAT_SITUACION_RESIDENCIA.NOMBRE AS SITUACION_RESIDENCIA,

    -- DATOS DE ENTIDAD FEDERATIVA
    CAT_ENTIDAD_FEDERATIVA.NOMBRE   AS ENTIDAD_FEDERATIVA,

    -- DATOS DE CIUDAD
    CAT_CIUDAD.NOMBRE               AS CIUDAD,

    -- DATOS COLONIA
    CAT_USUARIO.FK_COLONIA,
    CAT_COLONIA.NOMBRE              AS COLONIA,

    -- DATOS AREA ACADEMICA
    CAT_USUARIO.FK_AREA_ACADEMICA,
    CAT_AREA_ACADEMICA.NOMBRE       AS AREA_ACADEMICA
FROM CAT_USUARIO
         LEFT JOIN CAT_CARRERA
                   ON CAT_USUARIO.FK_CARRERA = CAT_CARRERA.PK_CARRERA
         LEFT JOIN CAT_ESTADO_CIVIL
                   ON CAT_USUARIO.FK_ESTADO_CIVIL = CAT_ESTADO_CIVIL.PK_ESTADO_CIVIL
         LEFT JOIN CAT_SITUACION_RESIDENCIA
                   ON CAT_USUARIO.FK_SITUACION_RESIDENCIA = CAT_SITUACION_RESIDENCIA.PK_SITUACION_RESIDENCIA
         LEFT JOIN CAT_AREA_ACADEMICA
                   ON CAT_USUARIO.FK_AREA_ACADEMICA = CAT_AREA_ACADEMICA.PK_AREA_ACADEMICA
         LEFT JOIN CAT_COLONIA
                   ON CAT_USUARIO.FK_COLONIA = CAT_COLONIA.PK_COLONIA
         LEFT JOIN CAT_CODIGO_POSTAL
                   ON CAT_USUARIO.FK_CODIGO_POSTAL = CAT_CODIGO_POSTAL.PK_CODIGO_POSTAL
         LEFT JOIN CAT_CIUDAD
                   ON CAT_CODIGO_POSTAL.FK_CIUDAD = CAT_CIUDAD.PK_CIUDAD
         LEFT JOIN CAT_ENTIDAD_FEDERATIVA
                   ON CAT_CIUDAD.FK_ENTIDAD_FEDERATIVA = CAT_ENTIDAD_FEDERATIVA.PK_ENTIDAD_FEDERATIVA
         LEFT JOIN CAT_PAIS
                   ON CAT_ENTIDAD_FEDERATIVA.FK_PAIS = CAT_PAIS.PK_PAIS;

