use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/
 /* VISTA DE DATOS DE PERFIL DE ALUMNO */
DROP VIEW IF EXISTS VW_PERFIL_ALUMNO;
CREATE VIEW VW_PERFIL_ALUMNO AS
SELECT
    CAT_USUARIO.*,
    CAT_CARRERA.NOMBRE AS CARRERA,
    CAT_ESTADO_CIVIL.NOMBRE AS ESTADO_CIVIL
FROM CAT_USUARIO
         LEFT JOIN CAT_ESTADO_CIVIL
                   ON CAT_ESTADO_CIVIL.PK_ESTADO_CIVIL = CAT_USUARIO.FK_ESTADO_CIVIL
         LEFT JOIN CAT_COLONIA
                   ON CAT_COLONIA.PK_COLONIA = CAT_USUARIO.FK_COLONIA
         LEFT JOIN CAT_TIPO_ASENTAMIENTO
                   ON CAT_TIPO_ASENTAMIENTO.PK_TIPO_ASENTAMIENTO = CAT_COLONIA.FK_TIPO_ASENTAMIENTO
         LEFT JOIN TR_COLONIA_CODIGO_POSTAL
                   ON TR_COLONIA_CODIGO_POSTAL.FK_COLONIA = CAT_COLONIA.PK_COLONIA
         LEFT JOIN CAT_CODIGO_POSTAL
                   ON CAT_CODIGO_POSTAL.PK_CODIGO_POSTAL = TR_COLONIA_CODIGO_POSTAL.FK_CODIGO_POSTAL
         LEFT JOIN CAT_CIUDAD
                   ON CAT_CIUDAD.PK_CIUDAD = CAT_CODIGO_POSTAL.FK_CIUDAD
         LEFT JOIN CAT_ENTIDAD_FEDERATIVA
                   ON CAT_ENTIDAD_FEDERATIVA.PK_ENTIDAD_FEDERATIVA = CAT_CIUDAD.FK_ENTIDAD_FEDERATIVA
         LEFT JOIN CAT_PAIS
                   ON CAT_PAIS.PK_PAIS = CAT_ENTIDAD_FEDERATIVA.FK_PAIS
         LEFT JOIN CAT_CARRERA ON CAT_USUARIO.FK_CARRERA = CAT_CARRERA.PK_CARRERA
;

/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/



-- --------------------------------------------------------------------------------------------------------------------------------
