use SWIITL;

/*********************  INICIO MODIFICACIONES LUNES 15 DE ABRIL 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/
-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

-- SCRIPT INICIAL PARA LAS TABLAS DEL ESQUEMA TECNOLÓGICO

UPDATE CAT_INSTITUCION SET CLAVE_CIE = '1369296' WHERE ALIAS = 'ITL'

UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5191
WHERE CLAVE_TECNM = 'IELC-2010-211';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5189
WHERE CLAVE_TECNM = 'IEME-2010-210';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 6157
WHERE CLAVE_TECNM = 'IGEM-2009-201';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5190
WHERE CLAVE_TECNM = 'IIND-2010-227';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5188
WHERE CLAVE_TECNM = 'ISIC-2010-224';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5997
WHERE CLAVE_TECNM = 'ILOG-2009-202';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 6628
WHERE CLAVE_TECNM = 'IMCT-2010-229';
UPDATE CAT_CARRERA
SET CLAVE_CARRERA = 5192
WHERE CLAVE_TECNM = 'ITIC-2010-225';


INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Papá', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Mamá', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Padres', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Tutor', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Familiar', 1);
INSERT INTO CAT_DEPENDENCIA (NOMBRE, ESTADO)
VALUES ('Nadie', 1);


INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Fórum educativo', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Visitaron mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Visite las instalaciones con mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Visite las instalaciones por mi cuenta', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Grupo deportivo', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Grupo cultural/artístico', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Curso de idioma', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Otro tipo de curso', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un familiar', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un familiar egresado del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un amigo o conocido', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un amigo o conocido egresado del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un docente de mi escuela', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Recomendación de un docente del ITL', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Decisión de mis padres', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Facebook', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Twitter', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Folleto', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Internet', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Radio', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Periódico', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Televisión', 1);
INSERT INTO CAT_PROPAGANDA_TECNOLOGICO (NOMBRE, ESTADO)
VALUES ('Por su ubicación', 1);


INSERT INTO CAT_INCAPACIDAD (NOMBRE, ESTADO)
VALUES ('Visual', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE, ESTADO)
VALUES ('Motriz', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE, ESTADO)
VALUES ('Auditiva', 1);
INSERT INTO CAT_INCAPACIDAD (NOMBRE, ESTADO)
VALUES ('Otra', 1);


INSERT INTO CAT_UNIVERSIDAD (NOMBRE)
VALUES ('Otra'),
       ('ATENAS ESTUDIOS SUPERIORES'),
       ('ESCUELA DE CONTADURÍA Y ADMINISTRACIÓN'),
       ('CAMPUS UNIVERSITARIO SIGLO XXI ESCUELA DE ADMINISTRACIÓN'),
       ('CENTRO AMERICANO CULTURAL DE ESTUDIOS SUPERIORES'),
       ('CENTRO CULTURAL ÍTACA, S. C.'),
       ('CENTRO DE DISEÑO, CINE Y TELEVISIÓN'),
       ('CENTRO DE ENSEÑANZA TÉCNICA INDUSTRIAL'),
       ('CENTRO DE ESTUDIOS AVANZADOS DE LAS AMÉRICAS'),
       ('CENTRO DE ESTUDIOS DE CELAYA'),
       ('CENTRO DE ESTUDIOS DE LAS CIENCIAS EDUCATIVAS S.C.'),
       ('CENTRO DE ESTUDIOS ESTRATÉGICOS DEL BAJÍO'),
       ('CENTRO DE ESTUDIOS INTERNACIONAL DE QUERÉTARO'),
       ('CENTRO DE ESTUDIOS MEXIQUENSE'),
       ('CENTRO DE ESTUDIOS PROFESIONALES DEL ESTADO DE MÉXICO'),
       ('CENTRO DE ESTUDIOS SUPERIORES ALLENDE'),
       ('CENTRO DE ESTUDIOS SUPERIORES ATENEA PALAS S. C.'),
       ('CENTRO DE ESTUDIOS SUPERIORES AZTECA'),
       ('CENTRO DE ESTUDIOS SUPERIORES CONCORDIA PLANTEL SAN MATEO ATENCO'),
       ('CENTRO DE ESTUDIOS SUPERIORES CORNEJO'),
       ('CENTRO DE ESTUDIOS SUPERIORES DE CELAYA'),
       ('CENTRO DE ESTUDIOS SUPERIORES DE CORTÁZAR'),
       ('CENTRO DE ESTUDIOS SUPERIORES DE LA ESCUELA MEXICANA DE TURISMO'),
       ('CENTRO DE ESTUDIOS SUPERIORES DE SAN ÁNGEL'),
       ('CENTRO DE ESTUDIOS SUPERIORES DEL BAJÍO CAMPUS QUERÉTARO'),
       ('CENTRO DE ESTUDIOS SUPERIORES DEL ESTADO DE AGUASCALIENTES'),
       ('CENTRO DE ESTUDIOS SUPERIORES DEL ORIENTE DE MICHOACÁN'),
       ('CENTRO DE ESTUDIOS SUPERIORES FRANCÉS MEXICANO'),
       ('CENTRO DE ESTUDIOS SUPERIORES FRAY PEDRO DE GANTE'),
       ('CENTRO DE ESTUDIOS SUPERIORES IGNACIO LOPEZ RAYÓN'),
       ('CENTRO DE ESTUDIOS SUPERIORES INTERCONTINENTAL'),
       ('CENTRO DE ESTUDIOS SUPERIORES JOHN VON NEWMAN'),
       ('CENTRO DE ESTUDIOS SUPERIORES NET'),
       ('CENTRO DE ESTUDIOS SUPERIORES OLIMPO'),
       ('CENTRO DE ESTUDIOS SUPERIORES SOR JUANA INÉS DE LA CRUZ'),
       ('CENTRO DE ESTUDIOS SUPERIORES UNIVERSITARIOS, S.C.'),
       ('CENTRO DE ESTUDIOS TECNOLÓGICOS Y UNIVERSITARIOS IAMP'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS ALLENDE'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS COYOTL'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS DE LA CIUDAD DE MÉXICO'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS DE QUERÉTARO A.C.'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS DEL BAJÍO, S. C.'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS HERMAN GRASSMANN'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS HORACIO ZÚÑIGA'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS PART'),
       ('CENTRO DE ESTUDIOS UNIVERSITARIOS UNIVER - SAHUAYO'),
       ('CENTRO DE GASTRONOMÍA Y SAZÓN'),
       ('CENTRO EDUCATIVO DE ESTUDIOS SUPERIORES'),
       ('CENTRO INTERAMERICANO DE ESTUDIOS SUPERIORES'),
       ('CENTRO SUPERIOR EN TECNOLOGÍAS DE INFORMACIÓN'),
       ('CENTRO UNIVERSITARIO ANGLOAMERICANO - PLANTEL CHURUBUSCO'),
       ('CENTRO UNIVERSITARIO BRITÁNICO DE MÉXICO'),
       ('CENTRO UNIVERSITARIO COLUMBIA'),
       ('CENTRO UNIVERSITARIO DE ARQUITECTURA INGENIERÍA Y DISEÑO UNIARQ'),
       ('CENTRO UNIVERSITARIO DE ATIZAPÁN MÉXICO'),
       ('CENTRO UNIVERSITARIO DE COMUNICACIÓN'),
       ('CENTRO UNIVERSITARIO DE EDUCACIÓN SUPERIOR HERMOSA PROVINCIA'),
       ('CENTRO UNIVERSITARIO DE GASTRONOMÍA'),
       ('CENTRO UNIVERSITARIO DE GUANAJUATO'),
       ('CENTRO UNIVERSITARIO DE IRAPUATO'),
       ('CENTRO UNIVERSITARIO DE IXTLAHUACA, A.C'),
       ('CENTRO UNIVERSITARIO DE MERCADOTECNIA Y PUBLICIDAD'),
       ('CENTRO UNIVERSITARIO DE MONTERREY'),
       ('CENTRO UNIVERSITARIO DE NEGOCIOS DEL BAJÍO'),
       ('CENTRO UNIVERSITARIO DEL ESTADO DE GUANAJUATO'),
       ('CENTRO UNIVERSITARIO DEL ESTADO DE MÉXICO'),
       ('CENTRO UNIVERSITARIO DEL VALLE DE TEOTIHUACÁN'),
       ('CENTRO UNIVERSITARIO DEL VALLE DE ZACAPU'),
       ('CENTRO UNIVERSITARIO EN PERIODISMO Y PUBLICIDAD'),
       ('CENTRO UNIVERSITARIO ETAC'),
       ('CENTRO UNIVERSITARIO EUROAMERICANO'),
       ('CENTRO UNIVERSITARIO FRANCISCO LARROYO'),
       ('CENTRO UNIVERSITARIO GUADALAJARA LAMAR - CAMPUS CHAPULTEPEC'),
       ('CENTRO UNIVERSITARIO HALLER'),
       ('CENTRO UNIVERSITARIO HISPANOAMERICANO'),
       ('CENTRO UNIVERSITARIO IMEC'),
       ('CENTRO UNIVERSITARIO INCARNATE WORD'),
       ('CENTRO UNIVERSITARIO INTERAMERICANO'),
       ('CENTRO UNIVERSITARIO INTERNACIONAL DE MÉXICO'),
       ('CENTRO UNIVERSITARIO ISIDRO FABELA'),
       ('CENTRO UNIVERSITARIO ITURBIDE'),
       ('CENTRO UNIVERSITARIO LOS ÁNGELES'),
       ('CENTRO UNIVERSITARIO MERIDIANO'),
       ('CENTRO UNIVERSITARIO ORIENTE DE MÉXICO'),
       ('CENTRO UNIVERSITARIO PALMIRA'),
       ('CENTRO UNIVERSITARIO PARA EL DESARROLLO EMPRESARIAL DE MÉXICO'),
       ('CENTRO UNIVERSITARIO PARA LA PROFESIONALIZACIÓN ESTRATÉGICA'),
       ('CENTRO UNIVERSITARIO PEDRO DE GANTE'),
       ('CENTRO UNIVERSITARIO PRIVADO DE SALAMANCA'),
       ('CENTRO UNIVERSITARIO SAN ÁNGEL'),
       ('CENTRO UNIVERSITARIO SAN MARCOS'),
       ('CENTRO UNIVERSITARIO SAN PABLO'),
       ('CENTRO UNIVERSITARIO TENANGO DEL VALLE'),
       ('CENTRO UNIVERSITARIO TLACAELEL'),
       ('CENTRO UNIVERSITARIO UTEG'),
       ('COLEGIO AMAUTA'),
       ('COLEGIO CULINARIO DE MORELIA'),
       ('COLEGIO DE CONSULTORES EN IMAGEN PÚBLICA'),
       ('COLEGIO DE EDUCACIÓN INTEGRAL Y PROFESIONAL'),
       ('COLEGIO DE EMPRESARIOS EXCELLENTIA FERVIC'),
       ('COLEGIO DE ESTUDIOS DE POSGRADO DE LA CIUDAD DE MÉXICO PLANTEL ATLACOMULCO'),
       ('COLEGIO DE ESTUDIOS SUPERIORES HUMANITAS DEL ESTADO DE GUANAJUATO'),
       ('COLEGIO DE ESTUDIOS SUPERIORES DE LOS REYES'),
       ('EL COLEGIO DE SAN FRANCISCO'),
       ('COLEGIO EN ALTA DIRECCIÓN EMPRESARIAL'),
       ('CIKEGUI GASTRONÓMICO DE MORELIA'),
       ('COLEGIO JUAN PABLO II'),
       ('COLEGIO MEXIQUENSE UNIVERSITARIO'),
       ('COLEGIO SUPERIOR DE GASTRONOMÍA LEONARDO DA VINCI'),
       ('COLEGIO SUPERIOR DE GASTRONOMÍA'),
       ('COLEGIO UNIVERSITARIO ARTURO ROSENBLUETH'),
       ('COLEGIO UNIVERSITARIO BICENTENARIO'),
       ('COLEGIO UNIVERSITARIO DE HUMANIDADES'),
       ('COLEGIO UNIVERSITARIO DE YAHUALICA'),
       ('COLEGIO UNIVERSITARIO DEL DISTRITO FEDERAL'),
       ('COLEGIO UNIVERSITARIO DEL VALLE DE BERACA'),
       ('COLEGIO UNIVERSITARIO DEL VALLE DE MÉXICO'),
       ('COMPLEJO EDUCATIVO DE ESTUDIOS SUPERIORES SAN MIGUEL'),
       ('COMPLEJO EDUCATIVO LEONARDO DA VINCI'),
       ('COMPLEJO ESCOLAR INTERACTIVO DEL BAJÍO'),
       ('CORPORATIVO ACADÉMICO CADE'),
       ('CORPORATIVO INTERNACIONAL UNIVERSITARIO'),
       ('EDUCACIÓN INTEGRAL DE SAN MIGUEL EL ALTO'),
       ('EDUCACIÓN NUEVO MILENIO'),
       ('EL COLEGIO DE LEÓN, A. C.'),
       ('EL COLEGIO DE MÉXICO, A.C.'),
       ('UNIVERSIDAD TECMILENIO'),
       ('ESCUELA BANCARIA Y COMERCIAL'),
       ('ESCUELA CULINARIA INTERNACIONAL, S.C.'),
       ('ESCUELA DE EDUCACIÓN SUPERIOR LIBERTAD'),
       ('ESCUELA GASTRONÓMICA ESPECIALIZADA'),
       ('ESCUELA INTERNACIONAL DE TURISMO, A.C.'),
       ('ESCUELA INTERNACIONAL DE TURISMO, A.C. - CAMPUS TOLUCA'),
       ('ESCUELA SUPERIOR DE COMERCIO INTERNACIONAL'),
       ('ESCUELA SUPERIOR DE CONTADURÍA Y ADMINISTRACIÓN VILLANUEVA MONTAÑO, S.C.'),
       ('ESCUELA SUPERIOR DE ESTUDIOS HUMANÍSTICOS'),
       ('ESCUELA SUPERIOR DE ESTUDIOS PROFESIONALES DIEGO RIVERA'),
       ('ESCUELA SUPERIOR DE GASTRONOMÍA DE MORELIA'),
       ('ESCUELA SUPERIOR DE INGENIERÍA AUTOMOTRIZ'),
       ('ESCUELA SUPERIOR DE INGENIERÍA AUTOMOTRIZ DE URUAPAN'),
       ('ESCUELA SUPERIOR DE INGENIERÍA AUTOMOTRIZ'),
       ('ESCUELA SUPERIOR DE TURISMO Y GASTRONOMÍA'),
       ('GRUPO UNIVERSITARIO SAN ÁNGEL DEL SUR'),
       ('HUMANITAS ESCUELA SUPERIOR DE LEYES Y NEGOCIOS'),
       ('POLITÉCNICO DE GUANAJUATO'),
       ('INSTITUTO BONAMPAK'),
       ('INSTITUTO UNIVERSITARIO BRIMA'),
       ('INSTITUTO CARLOS LINDBERGH'),
       ('INSTITUTO CESAR RITZ'),
       ('INSTITUTO CIENTÍFICO TÉCNICO Y EDUCATIVO'),
       ('INSTITUTO CULINARIO DE QUERÉTARO'),
       ('CENTRO DE ESTUDIOS SUPERIORES ICEP'),
       ('CENTRO DE ESTUDIOS SUPERIORES EN CIENCIAS JURÍDICAS Y CRIMINOLÓGICAS'),
       ('INSTITUTO DE CIENCIAS Y ESTUDIOS SUPERIORES DE MICHOACÁN'),
       ('UNIVERSIDAD DE EDUCACIÓN PRODUCTIVA S.C.'),
       ('UNIVERSIDAD TECNOLÓGICA DE MÉXICO'),
       ('INSTITUTO DE EDUCACIÓN SUPERIOR JOSÉ VASCONCELOS'),
       ('INSTITUTO DE ENSEÑANZA SUPERIOR EN CONTADURÍA Y ADMINISTRACIÓN, S.C.'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES AMERICANO DE COMERCIO E INFORMÁTICA'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES DE MÉXICO'),
       ('INSTITUTO ESTUDIOS SUPERIORES DE TURISMO'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES DEL BAJÍO'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES DEL COLEGIO HOLANDÉS'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES DEL COLEGIO PATRIA DE LEÓN'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES EN ADMINISTRACIÓN PÚBLICA Y PRIVADA, S.C.'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES INEGAH'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES ISIMA'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES NUEVA INGLATERRA'),
       ('INSTITUTO DE ESTUDIOS SUPERIORES NÚÑEZ FRAGOSO'),
       ('INST DE EST UNIVERSITARIOS DEL VALLE DE ZAMORA'),
       ('INSTITUTO DE FORMACIÓN EDUCATIVA SUPERIOR, PLANTEL SAN JUAN DEL RIO'),
       ('INSTITUTO DE GASTRONOMÍA MÉXICO'),
       ('INSTITUTO DE INVESTIGACIÓN PARA LAS CIENCIAS AMBIENTALES AC'),
       ('INSTITUTO DE MERCADOTECNIA Y PUBLICIDAD'),
       ('INSTITUTO DE POSGRADOS Y ESPECIALIDADES'),
       ('INSTITUTO DEL POTOSÍ, A.C.'),
       ('INSTITUTO DEL VALLE DE APATZINGÁN'),
       ('INSTITUTO EDUCATIVO YOLDA'),
       ('INSTITUTO ESPECIALIZADO EN COMPUTACIÓN Y ADMINISTRACIÓN GAUSS JORDÁN'),
       ('INSTITUTO FRAY ANTONIO DE LISBOA'),
       ('INSTITUTO GASTRONÓMICO DE ESTUDIOS SUPERIORES, S. C.'),
       ('INSTITUTO GASTRONÓMICO LETTY GORDON'),
       ('INSTITUTO GASTRONÓMICO PROFESIONAL DE SALVATIERRA'),
       ('INSTITUTO INTERNACIONAL UNIVERSITARIO'),
       ('INSTITUTO IRAPUATO'),
       ('INSTITUTO LEONARDO BRAVO A.C. - PLANTEL CENTRO'),
       ('INSTITUTO MODSTIL'),
       ('INSTITUTO MUNDIAL DE ESTUDIOS SUPERIORES'),
       ('INSTITUTO NACIONAL DE ADMINISTRACIÓN PUBLICA, A.C.'),
       ('INSTITUTO OCTAVIO PAZ'),
       ('INSTITUTO POLITÉCNICO NACIONAL'),
       ('INSTITUTO RENACIMIENTO DE GUANAJUATO'),
       ('INSTITUTO SANJUANENSE DE ESTUDIOS SUPERIORES, A.C.'),
       ('INSTITUTO SECUNDARIA Y EDUCACIÓN SUBPROFESIONAL S. C.'),
       ('UNIVERSIDAD SOR JUANA INÉS DE LA CRUZ'),
       ('INSTITUTO SUPERIOR CONCORDIA'),
       ('INSTITUTO SUPERIOR DE INGENIERÍA'),
       ('INSTITUTO SUPERIOR DE VANGUARDIA EDUCATIVA'),
       ('INSTITUTO SUPERIOR DEL CENTRO'),
       ('INSTITUTO SUPERIOR INTERESTATAL DE LAS HUASTECAS'),
       ('INSTITUTO TÉCNICO DE FORMACIÓN POLICIAL'),
       ('INSTITUTO TÉCNICO Y BANCARIO SAN CARLOS'),
       ('INSTITUTO TECNOLÓGICO AUTÓNOMO DE MÉXICO'),
       ('INSTITUTO TECNOLÓGICO DE AGUASCALIENTES'),
       ('INSTITUTO TECNOLÓGICO DE ÁLVARO OBREGÓN'),
       ('INSTITUTO TECNOLÓGICO DE CELAYA'),
       ('INSTITUTO TECNOLÓGICO DE CIUDAD GUZMÁN'),
       ('INSTITUTO TECNOLÓGICO DE CIUDAD VALLES'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE HUETAMO'),
       ('INSTITUTO TECNOLÓGICO DE ESTUDIOS SUPERIORES DE ZAMORA'),
       ('INSTITUTO TECNOLÓGICO DE GUSTAVO A. MADERO'),
       ('INSTITUTO TECNOLÓGICO DE GUSTAVO A. MADERO II'),
       ('INSTITUTO TECNOLÓGICO DE INGENIERÍA AUTOMOTRIZ'),
       ('INSTITUTO TECNOLÓGICO DE IZTAPALAPA'),
       ('INSTITUTO TECNOLÓGICO DE IZTAPALAPA II'),
       ('INSTITUTO TECNOLÓGICO DE IZTAPALAPA III'),
       ('INSTITUTO TECNOLÓGICO DE JIQUILPAN'),
       ('INSTITUTO TECNOLÓGICO DE LA CONSTRUCCIÓN - CAMPUS CIUDAD DE MÉXICO'),
       ('INSTITUTO TECNOLÓGICO DE LA PIEDAD'),
       ('INSTITUTO TECNOLÓGICO DE LEÓN'),
       ('INSTITUTO TECNOLÓGICO DE MATEHUALA'),
       ('INSTITUTO TECNOLÓGICO DE MILPA ALTA'),
       ('INSTITUTO TECNOLÓGICO DE MILPA ALTA II'),
       ('INSTITUTO TECNOLÓGICO DE MORELIA'),
       ('INSTITUTO TECNOLÓGICO DE OCOTLÁN'),
       ('INSTITUTO TECNOLÓGICO DE PABELLÓN DE ARTEAGA'),
       ('INSTITUTO TECNOLÓGICO DE QUERÉTARO'),
       ('INSTITUTO TECNOLÓGICO DE ROQUE'),
       ('INSTITUTO TECNOLÓGICO DE SAN JUAN DEL RIO'),
       ('INSTITUTO TECNOLÓGICO DE SAN LUIS POTOSÍ'),
       ('INSTITUTO TECNOLÓGICO DE TLÁHUAC'),
       ('INSTITUTO TECNOLÓGICO DE TLÁHUAC II'),
       ('INSTITUTO TECNOLÓGICO DE TLÁHUAC III'),
       ('INSTITUTO TECNOLÓGICO DE TLAJOMULCO'),
       ('INSTITUTO TECNOLÓGICO DE TLALNEPANTLA'),
       ('INSTITUTO TECNOLÓGICO DE TLALPAN'),
       ('INSTITUTO TECNOLÓGICO DE TOLUCA'),
       ('INSTITUTO TECNOLÓGICO DE ZACATECAS'),
       ('INSTITUTO TECNOLÓGICO DEL VALLE DE MORELIA'),
       ('INSTITUTO TECNOLÓGICO EL LLANO AGUASCALIENTES'),
       ('INSTITUTO TECNOLÓGICO DE LÁZARO CÁRDENAS'),
       ('INSTITUTO TECNOLÓGICO RESTAURANTERO'),
       ('INSTITUTO TECNOLÓGICO SSC'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ABASOLO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE APATZINGÁN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ARANDAS'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE CHAPALA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE CIUDAD HIDALGO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE COALCOMÁN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE COCULA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ÉBANO, S.L.P.'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE EL GRULLO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE FRESNILLO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE IRAPUATO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE JEREZ'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE LA HUERTA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE LAGOS DE MORENO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE LORETO, ZAC.'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE LOS REYES'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE MASCOTA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE NOCHISTLAN'),
       ('UNIVERSIDAD TECNOLÓGICA DE MORELIA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE PÁTZCUARO, MICHOACÁN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE PUERTO VALLARTA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE PURÍSIMA DEL RINCÓN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE PURUANDIRO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE RIOVERDE'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE SALVATIERRA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE SAN LUIS POTOSÍ CAPITAL'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE TACÁMBARO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE TALA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE TAMAZUNCHALE'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE TEQUILA'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE URUAPAN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ZACATECAS NORTE'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ZACATECAS OCCIDENTE'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR ZACATECAS SUR'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ZAPOPAN'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR DE ZAPOTLANEJO'),
       ('INSTITUTO TECNOLÓGICO DEL SUR DE GUANAJUATO'),
       ('INSTITUTO TECNOLÓGICO SUPERIOR PURÉPECHA'),
       ('INSTITUTO TECNOLÓGICO Y DE ESTUDIOS SUPERIORES DE MONTERREY'),
       ('DEPARTAMENTO RESPECTIVO'),
       ('INSTITUTO TECNOLÓGICO DE ZITÁCUARO'),
       ('INSTITUTO TEPEYAC DE ESTUDIOS SUPERIORES'),
       ('INSTITUTO UNIVERSITARIO DE CUAUTITLÁN MÉXICO'),
       ('INSTITUTO UNIVERSITARIO DEL ALTIPLANO'),
       ('INSTITUTO UNIVERSITARIO DEL CENTRO DE MÉXICO'),
       ('UNIVERSIDAD IUEM'),
       ('INSTITUTO UNIVERSITARIO DEL LAGO Y DEL SOL'),
       ('INSTITUTO UNIVERSITARIO DEL PRADO'),
       ('INSTITUTO UNIVERSITARIO FRANCO INGLES DE MÉXICO, S. C.'),
       ('INSTITUTO UNIVERSITARIO LATINOAMERICANO'),
       ('INSTITUTO UNIVERSITARIO PUEBLA EXTENSIÓN MORELIA'),
       ('INSTITUTO UNIVERSITARIO UNIEM'),
       ('INSTITUTO UNIVERSITARIO Y TECNOLÓGICO MODELO (COACALCO)'),
       ('INTER CENTRO DE ESTUDIOS SUPERIORES PLANTEL IZCALLI'),
       ('ISSADE INSTITUTO SUPERIOR DE SISTEMA ABIERTO DE ENSEÑANZA'),
       ('IUM INSTITUTO UNIVERSITARIO MEXIQUENSE'),
       ('IUYTEM INSTITUTO UNIVERSITARIO Y TECNOLÓGICO DEL ESTADO DE MÉXICO'),
       ('JANNETTE KLEIN UNIVERSIDAD'),
       ('LICEO ESTUDIOS SUPERIORES'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CHALCO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CHIMALHUACÁN'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CHIMALHUACÁN'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE COACALCO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE CUAUTITLÁN IZCALLI'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE ECATEPEC'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE HUIXQUILUCAN'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE IXTAPALUCA'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE JILOTEPEC'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE JOCOTITLAN'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE SAN FELIPE DEL PROGRESO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE TIANGUISTENCO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE VALLE DE BRAVO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DE VILLA GUERRERO'),
       ('TECNOLÓGICO DE ESTUDIOS SUPERIORES DEL ORIENTE DEL ESTADO DE MÉXICO'),
       ('TECNOLÓGICO DE GUADALAJARA'),
       ('TECNOLÓGICO IBEROAMERICANO ARAGÓN, S.C.'),
       ('TECNOLÓGICO IBEROAMERICANO COYOACÁN'),
       ('TECNOLÓGICO PROFESIONAL EN HOTELERÍA Y RESTAURANTES HUGO ALBERTO MEDRANO PARADA'),
       ('TECNOLÓGICO UNIVERSITARIO DE MÉXICO'),
       ('TECNOLÓGICO UNIVERSITARIO NAUCALPAN'),
       ('TECPATL CENTRO DE ESTUDIOS SUPERIORES'),
       ('CENTRO DE ESTUDIOS Y CAPACITACIÓN TÉCNICO Y PROFESIONAL DE LEÓN'),
       ('UNIR MÉXICO'),
       ('UNIVERSIDAD ABIERTA Y A DISTANCIA DE MÉXICO (UNAD DE MÉXICO)'),
       ('UNIVERSIDAD NACIONAL AERONÁUTICA EN QUERÉTARO'),
       ('UNIVERSIDAD ALBERT EINSTEIN'),
       ('UNIVERSIDAD ALFA LAMBDA'),
       ('UNIVERSIDAD ALFRED NOBEL DE MÉXICO'),
       ('UNIVERSIDAD ALLENDE'),
       ('UNIVERSIDAD ALZATE DE OZUMBA'),
       ('UNIVERSIDAD ANÁHUAC'),
       ('UNIVERSIDAD ANGLO MEXICANA EUROPEA'),
       ('UNIVERSIDAD AUTÓNOMA CHAPINGO'),
       ('UNIVERSIDAD AUTÓNOMA DE AGUASCALIENTES'),
       ('UNIVERSIDAD AUTÓNOMA DE FRESNILLO'),
       ('UNIVERSIDAD AUTÓNOMA DE GUADALAJARA - CAMPUS CIUDAD UNIVERSITARIA'),
       ('UNIVERSIDAD AUTÓNOMA DE LA CIUDAD DE MÉXICO'),
       ('UNIVERSIDAD AUTÓNOMA DE QUERÉTARO'),
       ('UNIVERSIDAD AUTÓNOMA DE SAN LUIS POTOSÍ'),
       ('UNIDAD ACADÉMICA'),
       ('UNIVERSIDAD AUTÓNOMA DEL ESTADO DE MÉXICO'),
       ('UNIVERSIDAD AUTÓNOMA METROPOLITANA'),
       ('UNIVERSIDAD BANCARIA DE MÉXICO'),
       ('UNIVERSIDAD BONAGENS'),
       ('UNIVERSIDAD CASAURANC'),
       ('UNIVERSIDAD CENTRAL DE QUERÉTARO'),
       ('UCH. ESCUELA DE COMERCIO Y ADMINISTRACIÓN'),
       ('UNIVERSIDAD CNCI - CAMPUS POLANCO'),
       ('UNIVERSIDAD CONTEMPORÁNEA'),
       ('UNIVERSIDAD CONTEMPORÁNEA DE LAS AMÉRICAS'),
       ('UNIVERSIDAD CONTINENTAL'),
       ('UNIVERSIDAD CONTINENTE AMERICANO'),
       ('UNIVERSIDAD CORREGIDORA DE QUERÉTARO'),
       ('UNIVERSIDAD CUAUHTÉMOC'),
       ('UNIVERSIDAD DE ATLACOMULCO'),
       ('UNIVERSIDAD DE CELAYA'),
       ('UNIVERSIDAD DE CIENCIAS Y ADMINISTRACIÓN'),
       ('UNIVERSIDAD DE CUAUTITLÁN I'),
       ('UNIVERSIDAD DE DURANGO'),
       ('UNIVERSIDAD ECATEPEC'),
       ('CENTRO UNIVERSITARIO DE ESPAÑA Y MÉXICO'),
       ('UNIVERSIDAD DE ESTUDIOS AVANZADOS'),
       ('ESCUELA PROFESIONAL DE COMERCIO Y ADMINISTRACIÓN'),
       ('COLEGIO PITÁGORAS A.C.'),
       ('UNIVERSIDAD DE GUADALAJARA'),
       ('UNIVERSIDAD DE GUANAJUATO'),
       ('UNIVERSIDAD DE LA COMUNICACIÓN, S.C.'),
       ('UNIVERSIDAD DE LA REPÚBLICA MEXICANA'),
       ('UDLA ESCUELA DE CIENCIAS ADMINISTRATIVAS'),
       ('UNIVERSIDAD DE LEÓN'),
       ('UNIVERSIDAD DE LONDRES'),
       ('UNIVERSIDAD DE MORELIA'),
       ('UNIVERSIDAD DE NORTEAMÉRICA'),
       ('UNIVERSIDAD DEL CENTRO DE MÉXICO'),
       ('UNIVERSIDAD DEL CENTRO DEL BAJÍO'),
       ('UNIVERSIDAD DEL CLAUSTRO DE SOR JUANA, A.C.'),
       ('UNIVERSIDAD DEL DESARROLLO EMPRESARIAL Y PEDAGÓGICO'),
       ('UNIVERSIDAD DEL DESARROLLO PROFESIONAL'),
       ('UNIVERSIDAD DEL DISTRITO FEDERAL'),
       ('UNIVERSIDAD DEL EJERCITO Y FUERZA AÉREA'),
       ('UNIVERSIDAD DEL GOLFO DE MÉXICO NORTE'),
       ('UNIVERSIDAD DEL MÉXICO CONTEMPORÁNEO'),
       ('UNIVERSIDAD DEL PEDREGAL'),
       ('UNIVERSIDAD DEL TEPEYAC A.C.'),
       ('UNIVERSIDAD DEL VALLE DE ATEMAJAC'),
       ('UNIVERSIDAD DEL VALLE DE MÉXICO '),
       ('UNIVERSIDAD DEL VALLE DE TOLUCA'),
       ('UNIVERSIDAD DEL VALLE DE ZAMORA'),
       ('UNIVERSIDAD DIGITAL DEL ESTADO DE MÉXICO,  PLANTEL ETAC'),
       ('UNIVERSIDAD DON VASCO, A.C.'),
       ('UNIVERSIDAD EUROPEA'),
       ('UNIVERSIDAD FRANCISCANA DE MÉXICO'),
       ('UNIVERSIDAD FRANCO MEXICANA, S.C.'),
       ('INSTITUTO DE PSICOTERAPIA GESTALT'),
       ('UNIVERSIDAD IBEROAMERICANA CIUDAD DE MÉXICO'),
       ('UNIVERSIDAD IBEROAMERICANA'),
       ('UNIVERSIDAD ICEL'),
       ('UNIVERSIDAD INACE '),
       ('UNIVERSIDAD INSURGENTES '),
       ('UNIVERSIDAD INTERACTIVA Y A DISTANCIA DEL ESTADO DE GUANAJUATO'),
       ('UNIVERSIDAD INTERAMERICANA PARA EL DESARROLLO'),
       ('UNIVERSIDAD INTERCONTINENTAL'),
       ('UNIVERSIDAD INTERCULTURAL DE SAN LUIS POTOSÍ'),
       ('UNIVERSIDAD INTERNACIONAL'),
       ('UNIVERSIDAD INTERNACIONAL JEFFERSON'),
       ('UNIVERSIDAD ISEC - NEGOCIOS INTERNACIONALES'),
       ('UNIVERSIDAD ISIDRO FABELA DE TOLUCA, S.C.'),
       ('UNIVERSIDAD JUSTO SIERRA'),
       ('UNIVERSIDAD LA CONCORDIA'),
       ('UNIVERSIDAD LA PROVIDENCIA'),
       ('UNIVERSIDAD LA SALLE'),
       ('UNIVERSIDAD LA SALLE, A.C. - CIUDAD DE MÉXICO'),
       ('UNIVERSIDAD LAS AMÉRICAS DE CENTRO OCCIDENTE'),
       ('UNIVERSIDAD LATINA DE AMÉRICA'),
       ('ESCUELA DE COMERCIO DE LA UNIVERSIDAD LATINA DE MÉXICO'),
       ('UNIVERSIDAD LATINA'),
       ('UNIVERSIDAD LATINOAMERICANA'),
       ('UNIVERSIDAD LUCERNA'),
       ('UNIVERSIDAD MARISTA DE GUADALAJARA'),
       ('UNIVERSIDAD MARISTA DE QUERÉTARO, A. C.'),
       ('UNIVERSIDAD MARISTA DE QUERÉTARO, A. C.'),
       ('UNIVERSIDAD MARISTA DE SAN LUIS POTOSÍ'),
       ('UNIVERSIDAD MARISTA VALLADOLID'),
       ('UNIVERSIDAD MESOAMERICANA - CAMPUS SAN JUAN'),
       ('UNIVERSIDAD MEXICANA'),
       ('UNIVERSIDAD MEXICANA DE EDUCACIÓN A DISTANCIA'),
       ('UNIVERSIDAD MEXICANA DE INNOVACIÓN EN NEGOCIOS'),
       ('UNIVERSIDAD MEXIQUENSE'),
       ('UNIVERSIDAD MEXIQUENSE DEL BICENTENARIO'),
       ('UNIVERSIDAD MICHAEL FARADAY, A.C.'),
       ('UNIVERSIDAD MICHOACANA DE SAN NICOLÁS DE HIDALGO'),
       ('UNIVERSIDAD MONTRER'),
       ('UNIVERSIDAD MOTOLINIA DEL PEDREGAL'),
       ('UNIVERSIDAD MULTICULTURAL CUDEC'),
       ('UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO'),
       ('UNIVERSIDAD OPARIN S. C.'),
       ('UNIVERSIDAD PANAMERICANA'),
       ('UNIVERSIDAD PARA LA PROFESIONALIZACIÓN EDUCATIVA S. C.'),
       ('UNIVERSIDAD PATRIA'),
       ('UNIVERSIDAD PEDAGÓGICA NACIONAL - UNIDAD AJUSCO'),
       ('UNIVERSIDAD POLITÉCNICA DE AGUASCALIENTES'),
       ('UNIVERSIDAD POLITÉCNICA DE ATLACOMULCO'),
       ('UNIVERSIDAD POLITÉCNICA DE ATLAUTLA'),
       ('UNIVERSIDAD POLITÉCNICA DE GUANAJUATO'),
       ('UNIVERSIDAD POLITÉCNICA DE JUVENTINO ROSAS'),
       ('UNIVERSIDAD POLITÉCNICA DE LA ZONA METROPOLITANA DE GUADALAJARA'),
       ('UNIVERSIDAD POLITÉCNICA DE LÁZARO CÁRDENAS, MICHOACÁN'),
       ('UNIVERSIDAD POLITÉCNICA DE OTZOLOTEPEC'),
       ('UNIVERSIDAD POLITÉCNICA DE OTZOLOTEPEC'),
       ('UNIVERSIDAD POLITÉCNICA DE PÉNJAMO'),
       ('UNIVERSIDAD POLITÉCNICA DE QUERÉTARO'),
       ('UNIVERSIDAD POLITÉCNICA DE SANTA ROSA JÁUREGUI'),
       ('UNIVERSIDAD POLITÉCNICA DE TECÁMAC'),
       ('UNIVERSIDAD POLITÉCNICA DE TECÁMAC'),
       ('UNIVERSIDAD POLITÉCNICA DE TEXCOCO'),
       ('UNIVERSIDAD POLITÉCNICA DE TEXCOCO'),
       ('UNIVERSIDAD POLITÉCNICA DE URUAPAN, MICHOACÁN'),
       ('UNIVERSIDAD POLITÉCNICA DE ZACATECAS'),
       ('UNIVERSIDAD POLITÉCNICA DEL BICENTENARIO'),
       ('UNIVERSIDAD POLITÉCNICA DEL SUR DE ZACATECAS'),
       ('UNIVERSIDAD POLITÉCNICA DEL VALLE DE MÉXICO'),
       ('UNIVERSIDAD POLITÉCNICA DEL VALLE DE TOLUCA'),
       ('UNIVERSIDAD POTOSINA'),
       ('UNIVERSIDAD PRIVADA DE IRAPUATO'),
       ('UNIVERSIDAD PRIVADA DE MICHOACÁN'),
       ('UNIVERSIDAD PRIVADA DEL ESTADO DE MÉXICO'),
       ('UNIVERSIDAD QUETZALCÓATL'),
       ('UNIVERSIDAD SALESIANA, A.C.'),
       ('INSTITUTO DE EDUCACIÓN SUPERIOR SANTA FE'),
       ('UNIVERSIDAD SIERRA MADRE'),
       ('UNIVERSIDAD SIMÓN BOLÍVAR'),
       ('UNIVERSIDAD SOR JUANA INÉS DE LA CRUZ'),
       ('UNIVERSIDAD SUPERIOR BAJÍO - PLANTEL CELAYA'),
       ('UNIVERSIDAD TANGAMANGA'),
       ('UNIVERSIDAD TECNOLÓGICA AMERICANA'),
       ('UNIVERSIDAD TECNOLÓGICA DE AGUASCALIENTES'),
       ('UNIVERSIDAD TECNOLÓGICA DE CALVILLO'),
       ('UNIVERSIDAD TECNOLÓGICA DE CORREGIDORA'),
       ('UNIVERSIDAD TECNOLÓGICA DE JALISCO'),
       ('UNIVERSIDAD TECNOLÓGICA DE LA ZONA METROPOLITANA DE GUADALAJARA'),
       ('UNIVERSIDAD TECNOLÓGICA DE LEÓN'),
       ('UNIVERSIDAD TECNOLÓGICA DE NEZAHUALCÓYOTL'),
       ('UNIVERSIDAD TECNOLÓGICA DE QUERÉTARO'),
       ('UNIVERSIDAD TECNOLÓGICA DE SALAMANCA'),
       ('UNIVERSIDAD TECNOLÓGICA DE SAN JUAN DEL RIO'),
       ('UNIVERSIDAD TECNOLÓGICA DE SAN LUIS POTOSÍ'),
       ('UNIVERSIDAD TECNOLÓGICA DE SAN MIGUEL DE ALLENDE'),
       ('UNIVERSIDAD TECNOLÓGICA DE TECÁMAC'),
       ('UNIVERSIDAD TECNOLÓGICA DE ZINACANTEPEC'),
       ('UNIVERSIDAD TECNOLÓGICA DEL CENTRO DE MÉXICO'),
       ('UNIVERSIDAD TECNOLÓGICA DEL ESTADO DE ZACATECAS'),
       ('UNIVERSIDAD TECNOLÓGICA DEL NORTE'),
       ('UNIVERSIDAD TECNOLÓGICA DEL NORTE DE AGUASCALIENTES'),
       ('UNIVERSIDAD TECNOLÓGICA DEL SUR DEL ESTADO DE MÉXICO'),
       ('UNIVERSIDAD TECNOLÓGICA DEL SUROESTE DE GUANAJUATO'),
       ('UNIVERSIDAD TECNOLÓGICA DEL VALLE DE TOLUCA'),
       ('UNIVERSIDAD TECNOLÓGICA DE EL RETOÑO'),
       ('UNIVERSIDAD TECNOLÓGICA FIDEL VELÁZQUEZ'),
       ('UNIVERSIDAD TECNOLÓGICA FIDEL VELÁZQUEZ'),
       ('CENTRO UNIVERSITARIO IBEROAMERICANO'),
       ('UNIVERSIDAD TECNOLÓGICA INTERNACIONAL'),
       ('UNIVERSIDAD TECNOLÓGICA LAJA BAJÍO'),
       ('UNIVERSIDAD TECNOLÓGICA LATINOAMERICANA EN LÍNEA'),
       ('UNIVERSIDAD TECNOLÓGICA ROOSEVELT'),
       ('UNIVERSIDAD TRES CULTURAS'),
       ('UNIVERSIDAD UCUGS - CAMPUS CUAUHTÉMOC'),
       ('UNIVERSIDAD UNIVBAJIO ESTUDIOS UNIVERSITARIOS'),
       ('UNIVERSIDAD UNIVER'),
       ('UNIVERSIDAD UNIVER  MILENIUM'),
       ('UNIVERSIDAD VASCO DE QUIROGA'),
       ('UNIVERSIDAD VICTORIA'),
       ('UNIVERSIDAD VIRTUAL DE ESTUDIOS SUPERIORES'),
       ('UNIVERSIDAD VIRTUAL DEL ESTADO DE GUANAJUATO'),
       ('UNIVERSIDAD VIRTUAL DEL ESTADO DE MICHOACÁN (UNIVIM)'),
       ('UNIVERSIDAD WESTHILL'),
       ('UNIVERSIDAD YMCA');


INSERT INTO CAT_CARRERA_UNIVERSIDAD (NOMBRE)
VALUES ('Otra'),
       ('ING. AERONÁUTICA EN MANUFACTURA'),
       ('ING. AGROINDUSTRIAL'),
       ('ING. AGRÓNOMO INDUSTRIAL'),
       ('ING. AMBIENTAL'),
       ('ING. AUTOMOTRIZ'),
       ('ING. BIOQUÍMICA'),
       ('ING. BIOTECNÓLOGO'),
       ('ING. DE LOS ALIMENTOS'),
       ('ING. DE PROCESOS Y COMERCIO INTERNACIONAL'),
       ('ING. ELÉCTRICA'),
       ('ING. ELÉCTRICA Y ELECTRÓNICA'),
       ('ING. ELECTROMECÁNICA'),
       ('ING. ELECTRÓNICA'),
       ('ING. ELECTRÓNICA BIOMÉDICA'),
       ('ING. ELECTRÓNICA Y DE COMUNICACIONES'),
       ('ING. EN ADMINISTRACIÓN'),
       ('ING. EN AERONÁUTICA'),
       ('ING. EN AGRONEGOCIOS'),
       ('ING. EN ALIMENTOS'),
       ('ING. EN AUTOMATIZACIÓN'),
       ('ING. EN BIÓNICA'),
       ('ING. EN BIOPROCESOS'),
       ('ING. EN BIOTECNOLOGÍA'),
       ('ING. EN COMPUTACIÓN'),
       ('ING. EN COMUNICACIONES Y ELECTRÓNICA'),
       ('ING. EN CONTROL Y AUTOMATIZACIÓN'),
       ('ING. EN DESARROLLO DE VIDEO JUEGOS'),
       ('ING. EN DESARROLLO SUSTENTABLE'),
       ('ING. EN DISEÑO AUTOMOTRIZ'),
       ('ING. EN DISEÑO INDUSTRIAL'),
       ('ING. EN DISEÑO MECÁNICO'),
       ('ING. EN DISEÑO MECÁNICO AERONÁUTICO'),
       ('ING. EN ELECTRICIDAD Y AUTOMATIZACIÓN'),
       ('ING. EN ELECTROMECÁNICA'),
       ('ING. EN ELECTRÓNICA'),
       ('ING. EN ELECTRÓNICA AUTOMOTRIZ'),
       ('ING. EN ELECTRÓNICA Y COMPUTACIÓN'),
       ('ING. EN ELECTRÓNICA Y CONTROL DE SISTEMAS DE AERONAVES'),
       ('ING. EN ELECTRÓNICA Y SISTEMAS DIGITALES'),
       ('ING. EN ELECTRÓNICA Y TELECOMUNICACIONES'),
       ('ING. EN ENERGÍA'),
       ('ING. EN GESTIÓN DE PROYECTOS'),
       ('ing. EN GESTIÓN EMPRESARIAL'),
       ('ING. EN INNOVACIÓN Y DISEÑO'),
       ('ING. EN INSTRUMENTACIÓN ELECTRÓNICA Y NANOSENSORES'),
       ('ING. EN MANTENIMIENTO INDUSTRIAL'),
       ('ING. EN MANUFACTURA Y AUTOMATIZACIÓN INDUSTRIAL'),
       ('ING. EN MATERIALES'),
       ('ING. EN MECATRÓNICA'),
       ('ING. EN METAL MECÁNICA'),
       ('ING. EN METROLOGÍA INDUSTRIAL'),
       ('ING. EN NEGOCIOS Y GESTIÓN EMPRESARIAL'),
       ('ING. EN PROCESOS ALIMENTARIOS'),
       ('ING. EN PROCESOS Y OPERACIONES INDUSTRIALES'),
       ('ING. EN PRODUCCIÓN INDUSTRIAL'),
       ('ING. EN PRODUCCIÓN Y DISEÑO DIGITAL'),
       ('ING. EN RECURSOS NATURALES RENOVABLES'),
       ('ING. EN ROBÓTICA'),
       ('ING. EN SISTEMAS AMBIENTALES'),
       ('ING. EN SISTEMAS AUTOMOTRICES'),
       ('ING. EN SISTEMAS COMPUTACIONALES'),
       ('ING. EN SISTEMAS DE CALIDAD Y PRODUCTIVIDAD'),
       ('ING. EN SISTEMAS DIGITALES Y ROBÓTICA'),
       ('ING. EN SISTEMAS ELECTRÓNICOS INDUSTRIALES'),
       ('ING. EN SISTEMAS ELECTRÓNICOS Y DE TELECOMUNICACIONES'),
       ('ING. EN SISTEMAS ENERGÉTICOS SUSTENTABLES'),
       ('ING. EN SISTEMAS ESTRATÉGICOS DE LA INFORMACIÓN'),
       ('ING. EN SISTEMAS INTELIGENTES'),
       ('ING. EN SISTEMAS PRODUCTIVOS'),
       ('ING. EN SISTEMAS Y COMUNICACIONES'),
       ('ING. EN SISTEMAS Y TECNOLOGÍAS DE INFORMACIÓN'),
       ('ING. EN SISTEMAS Y TECNOLOGÍAS INDUSTRIALES'),
       ('ING. EN TECNOLOGÍA AMBIENTAL'),
       ('ING. EN TECNOLOGÍA AUTOMOTRIZ'),
       ('ING. EN TECNOLOGÍA DE LA MADERA'),
       ('ING. EN TECNOLOGÍAS COMPUTACIONALES'),
       ('ING. EN TECNOLOGÍAS DE AUTOMATIZACIÓN'),
       ('ING. EN TECNOLOGÍAS DE LA PRODUCCIÓN'),
       ('ING. EN TECNOLOGÍAS ELECTRÓNICAS'),
       ('ING. EN TECNOLOGÍAS PARA LA AUTOMATIZACIÓN'),
       ('ING. EN TECNOTRÓNICA'),
       ('ING. FINANCIERA'),
       ('ING. FISCAL Y FINANCIERA'),
       ('ING. INDUSTRIAL'),
       ('ING. MECÁNICA'),
       ('ING. MECÁNICA ADMINISTRATIVA'),
       ('ING. MECÁNICA AUTOMOTRIZ'),
       ('ING. MECÁNICA ELÉCTRICA'),
       ('ING. MECÁNICA ELECTRÓNICA'),
       ('ING. MECÁNICA Y ELÉCTRICA'),
       ('ING. MECÁNICO ADMINISTRADOR'),
       ('ING. MECÁNICO AGRÍCOLA'),
       ('ING. MECÁNICO ELECTRICISTA'),
       ('ING. MECATRÓNICA'),
       ('ING. METALÚRGICA'),
       ('ING. METALÚRGICA Y DE MATERIALES'),
       ('ING. MILITAR EN COMPUTACIÓN E INFORMÁTICA'),
       ('ING. MILITAR EN COMUNICACIONES Y ELECTRÓNICA'),
       ('ING. QUÍMICA'),
       ('ING. QUÍMICO AMBIENTAL'),
       ('ING. QUÍMICO EN ALIMENTOS'),
       ('ING. QUÍMICO EN MATERIALES'),
       ('ING. QUÍMICO PETROLERO'),
       ('ING. ROBÓTICA'),
       ('LIC. EN ADMINISTRACIÓN DE EMPRESAS'),
       ('LIC. EN ADMINISTRACIÓN DE LA MERCADOTECNIA'),
       ('LIC. EN ADMINISTRACIÓN DE LAS VENTAS'),
       ('LIC. EN ADMINISTRACIÓN DE NEGOCIOS'),
       ('LIC. EN ADMINISTRACIÓN DE RECURSOS HUMANOS'),
       ('LIC. EN ADMINISTRACIÓN E INNOVACIÓN DE NEGOCIOS'),
       ('LIC. EN ADMINISTRACIÓN EDUCATIVA'),
       ('LIC. EN ADMINISTRACIÓN INDUSTRIAL'),
       ('LIC. EN ADMINISTRACIÓN Y FINANZAS'),
       ('LIC. EN ADMINISTRACIÓN Y GESTIÓN'),
       ('LIC. EN AGROBIOTECNOLOGÍA'),
       ('LIC. EN CIENCIA DE LOS ALIMENTOS'),
       ('LIC. EN ENERGÍA Y DESARROLLO SUSTENTABLE'),
       ('LIC. EN ING. DE MINAS Y METALURGIA'),
       ('LIC. EN ING. EN INTELIGENCIA ARTIFICIAL'),
       ('LIC. EN ING. EN NANOTECNOLOGÍA'),
       ('LIC. EN ING. EN OPTIMIZACIÓN DE PROCESOS'),
       ('LIC. EN ING. PETROQUÍMICA'),
       ('QUÍMICO AGRÍCOLA');


INSERT INTO CAT_ESTATUS_ASPIRANTE (NOMBRE, ESTADO)
VALUES ('Preregistrado', 1);
INSERT INTO CAT_ESTATUS_ASPIRANTE (NOMBRE, ESTADO)
VALUES ('Pago realizado', 1);
INSERT INTO CAT_ESTATUS_ASPIRANTE (NOMBRE, ESTADO)
VALUES ('Preregistro CENEVAL', 1);
INSERT INTO CAT_ESTATUS_ASPIRANTE (NOMBRE, ESTADO)
VALUES ('Registrado CENEVAL', 1);
INSERT INTO CAT_ESTATUS_ASPIRANTE (NOMBRE, ESTADO)
VALUES ('Asistencia a CENEVAL', 1);

INSERT INTO CAT_CAMPUS(NOMBRE, FK_INSTITUCION)
SELECT 'I', PK_INSTITUCION
FROM CAT_INSTITUCION
WHERE ALIAS = 'ITL';
INSERT INTO CAT_CAMPUS(NOMBRE, FK_INSTITUCION)
SELECT 'II', PK_INSTITUCION
FROM CAT_INSTITUCION
WHERE ALIAS = 'ITL';

INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IELC-2010-211' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IEME-2010-210' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IGEM-2009-201' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS, ESTADO)
SELECT PK_CARRERA, PK_CAMPUS, 0
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IGEM-2009-201' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IIND-2010-227' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'ISIC-2010-224' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'ILOG-2009-202' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS, ESTADO)
SELECT PK_CARRERA, PK_CAMPUS, 0
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'ILOG-2009-202' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'IMCT-2010-229' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO TR_CARRERA_CAMPUS(FK_CARRERA, FK_CAMPUS)
SELECT PK_CARRERA, PK_CAMPUS
FROM CAT_CARRERA
         INNER JOIN CAT_CAMPUS ON CLAVE_TECNM = 'ITIC-2010-225' AND CAT_CAMPUS.NOMBRE = 'I';

INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Aula');
INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Laboratorio');
INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Cubículo');
INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Planta');
INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Sala');
INSERT INTO CAT_TIPO_ESPACIO (NOMBRE)
values ('Centro');

INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'A'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'B'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Centro de Cómputo', 'C'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Edificio de Sistemas', 'D'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'E'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'F'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'G'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'H'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Centro de Información', 'I'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Cafetería', 'J'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'K'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'L'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'M'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Departamento de Ciencias Básicas', 'N'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'O'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Laboratorio de Química', 'P'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Departamento de Ciencias Económico-Administrativas', 'Q'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'R'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Planta Piloto', 'S'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Laboratorio Electromecánica', 'T'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'U'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'V'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Auditorio', 'W'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'X'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'Y'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Gestión Tecnológica y Vinculación', 'Z'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'I';

INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'A'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'B'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, '', 'C'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Centro de Información', 'D'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'II';
INSERT INTO CATR_EDIFICIO (FK_CAMPUS, NOMBRE, PREFIJO)
SELECT PK_CAMPUS, 'Cafetería', 'E'
FROM CAT_CAMPUS
         INNER JOIN CAT_INSTITUCION ON CAT_INSTITUCION.ALIAS = 'ITL' AND CAT_CAMPUS.NOMBRE = 'II';

/*********************  FIN MODIFICACIONES MARTES 16 DE ABRIL 2019  *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
