use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

INSERT INTO PER_CAT_SISTEMA (NOMBRE, ABREVIATURA)
VALUES ('Aspirantes', 'ASP');

INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Dashboard');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Datos');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Prefichas');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Prefichas pagadas');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Lista grupos');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Crear grupos');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Archivos');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Gráficas');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Periodo');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Archivos de pagos');
INSERT INTO PER_CAT_MODULO (NOMBRE)
VALUES ('Referencias pagadas');

INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Aspirante', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Coordinador institucional', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Recursos financieros', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Servicios escolares', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Vinculación', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));

INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Aspirante'), 3);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Aspirante'), 4);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 5);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 6);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 7);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 8);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 9);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 10);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Coordinador institucional'), 11);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Recursos financieros'), 12);
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Recursos financieros'), 13);

/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Reportes', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));

INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Plantilla SIIA', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CAT_ROL (NOMBRE, FK_SISTEMA)
VALUES ('Examen ubicación', (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));


INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Servicios escolares'), );
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Vinculación'), );
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO)
VALUES ((SELECT PK_ROL FROM PER_CAT_ROL WHERE NOMBRE = 'Reportes'), );


-- --------------------------------------------------------------------------------------------------------------------------------
