use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIO QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

INSERT INTO PER_CAT_SISTEMA (NOMBRE, ESTADO) VALUES ('Aspirantes', 1);

INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Dashboard', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Datos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Prefichas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Prefichas pagadas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Lista grupos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Crear grupos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Archivos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Graficas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Periodo', 1, 1);

INSERT INTO PER_CATR_ROL (NOMBRE, ESTADO, FK_SISTEMA) VALUES ('Aspirante', 1, (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));
INSERT INTO PER_CATR_ROL (NOMBRE, ESTADO, FK_SISTEMA) VALUES ('Coordinador', 1, (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE NOMBRE = 'Aspirantes'));



INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Aspirante'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Dashboard'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Aspirante'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Datos'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Prefichas'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Prefichas pagadas'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Lista grupos'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Crear grupos'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Archivos'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Graficas'));
INSERT INTO PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES ((SELECT PK_ROL FROM PER_CATR_ROL WHERE NOMBRE = 'Coordinador'), (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE NOMBRE = 'Periodo'));



/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------