use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIO QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS


ALTER TABLE dbo.users ADD NUMERO_CONTROL NVARCHAR(8);

INSERT INTO PER_CAT_SISTEMA (NOMBRE, ESTADO) VALUES ('Aspirantes', 1);

INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Dashboard', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Datos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Prefichas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Prefichas pagadas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Lista grupos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Crear grupos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Archivos', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Graficas', 1, 1);
INSERT INTO PER_CAT_MODULO (NOMBRE, ESTADO, ORDEN) VALUES ('Periodo', 1, 1);

INSERT INTO PER_CATR_ROL (NOMBRE, ESTADO, FK_SISTEMA) VALUES ('Aspirante', 1, 1);
INSERT INTO PER_CATR_ROL (NOMBRE, ESTADO, FK_SISTEMA) VALUES ('Coordinador', 1, 1);

INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (1, 1);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (1, 2);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 3);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 4);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 5);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 6);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 7);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 8);
INSERT INTO SWIITL.dbo.PER_TR_ROL_MODULO (FK_ROL, FK_MODULO) VALUES (2, 9);



/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------