use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/


/* REGISTRO DE SISTEMA */
SET IDENTITY_INSERT PER_CAT_SISTEMA ON;
INSERT INTO PER_CAT_SISTEMA(PK_SISTEMA, NOMBRE, RUTA_ANGULAR, ABREVIATURA, CORREO1, INDICIO1)
VALUES(1, 'tutorias', 'tutorias', 'SIT', 'tutorias@itleon.edu.mx', 'tutorias');
SET IDENTITY_INSERT PER_CAT_SISTEMA OFF;

/* REGISTRO DE ROLES */
SET IDENTITY_INSERT PER_CAT_ROL ON;
INSERT INTO PER_CAT_ROL(PK_ROL, FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (1, 1, 'Estudiante', 'Estudiante');
SET IDENTITY_INSERT PER_CAT_ROL OFF;

/* REGISTRO DE MÓDULOS */
SET IDENTITY_INSERT PER_CAT_MODULO ON;
INSERT INTO PER_CAT_MODULO(PK_MODULO, NOMBRE, ESTADO, ORDEN)
VALUES (1, 'Encuestas', 1, 1);
SET IDENTITY_INSERT PER_CAT_MODULO OFF;

/* REGISTRO DE ROLES POR MÓDULO */
SET IDENTITY_INSERT PER_TR_ROL_MODULO ON;
INSERT INTO PER_TR_ROL_MODULO(PK_ROL_MODULO, FK_ROL, FK_MODULO)
VALUES (1, 1, 1);
SET IDENTITY_INSERT PER_TR_ROL_MODULO OFF;

/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
