USE [SWIITL]
DROP TABLE IF EXISTS[dbo].[AnteproyectoResidencias]

GO

/****** Object:  Table [dbo].[AnteproyectoResidencias]    Script Date: 15/04/2019 12:41:54 p. m. ******/

CREATE TABLE [dbo].[CAT_ANTEPROYECTO_RESIDENCIA](
	[ID_ANTEPROYECTO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[PDF] [nvarchar](255) NULL,
	[ALUMNO] [nvarchar](255) NULL,
	[ESTATUS] [nvarchar](255) NULL,
	[AREA_ACADEMICA] [int] NULL,
	[AUTOR] [nvarchar](255) NULL,
	[EMPRESA] [nvarchar](255) NULL,
	[COMENTARIO] [nvarchar](255) NULL,
	[PERIODO] [INT] NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ANTEPROYECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
 
CREATE TABLE [dbo].[CAT_REPORTE_RESIDENCIA](
	[PK_REPORTE] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](255) NULL,
	[PDF] [nvarchar](255) NULL,
	[ALUMNO] [nvarchar](255) NULL,
	[NUMERO] [nvarchar](255) NULL,
	[PERIODO] [int] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_REPORTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAT_REPORTE_RESIDENCIA] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_REPORTE_RESIDENCIA] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR EL CATALOGO RELACIONADO DE ALUMNOS */



CREATE TABLE [dbo].[CATR_ALUMNO](
	[NUMERO_CONTROL] [nvarchar](10) NOT NULL,
	[FECHA_INGRESO] [date] NOT NULL,
	[CLAVE_CARRERA] [char](5) NOT NULL,
	[ID_PADRE] INT NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
CONSTRAINT PK_ALUMNO PRIMARY KEY (NUMERO_CONTROL ASC)
)

ALTER TABLE [dbo].[CATR_ALUMNO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_ALUMNO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR EL CATALOGO RELACIONADO DE EMPLEADOS DE TIPO DOCENTE */
CREATE TABLE [dbo].[CATR_DOCENTE] (
  NUMERO_EMPLEADO_DOCENTE INT IDENTITY(1,1)		NOT NULL,
  ID_AREA_ACADEMICA       INT			NOT NULL,
  ID_PADRE                INT			NOT NULL,
  ID_USUARIO_REGISTRO	  INT				NULL,
  FECHA_REGISTRO		  DATETIME			NULL,
  ID_USUARIO_MODIFICACION INT				NULL,
  FECHA_MODIFICACION	  DATETIME			NULL,
  BORRADO				  nchar(1)			NULL,
  CONSTRAINT PK_DOCENTE PRIMARY KEY (NUMERO_EMPLEADO_DOCENTE ASC)
)
ALTER TABLE [dbo].[CATR_DOCENTE] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_DOCENTE] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR EL CATALOGO DE PROYECTOS ACTIVOS DE RESIDENCIAS */
CREATE TABLE [dbo].[CATR_PROYECTO](
	[PK_PROYECTO] [int] IDENTITY(1,1) NOT NULL,
	[FK_ANTEPROYECTO] [int] NULL,
	[FK_DOCENTE] [int] NULL,
	[FK_ASESOR_EXT] [int] NULL,
	[PERIODO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_PROYECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CATR_PROYECTO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_PROYECTO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/*TABLA PARA REGISTRAR LA CANTIDA DE PROYECTOS ASIGNADOS A UN MAESTRO*/
CREATE TABLE [dbo].[PER_DOCENTE_PROYECTO](
	[PK_DOCENTE_PROYECTO] [int] IDENTITY(1,1) NOT NULL,
	[FK_DOCENTE] [int] NULL,
	[CANTIDAD] [int] NULL,
	[PERIODO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_DOCENTE_PROYECTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PER_DOCENTE_PROYECTO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[PER_DOCENTE_PROYECTO] ADD  DEFAULT ('0') FOR [BORRADO]
GO
select * from PER_DOCENTE_PROYECTO

select PK_USUARIO, name from users join CATR_DOCENTE on users.PK_USUARIO = CATR_DOCENTE.ID_PADRE where ID_AREA_ACADEMICA = '1';

/*TABLA PARA REGISTRAR LOS COMENTARIOS SOBRE LOS REPORTES*/
CREATE TABLE [dbo].[CATR_COMENTARIO_REPORTE](
	[PK_COMENTARIO] [int] IDENTITY(1,1) NOT NULL,
	[FK_REPORTE] [int] NULL,
	[FK_USUARIO] [int] NULL,
	[COMENTARIO] [nvarchar](255) NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_COMENTARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CATR_COMENTARIO_REPORTE] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_COMENTARIO_REPORTE] ADD  DEFAULT ('0') FOR [BORRADO]
GO
/* TABLA PARA REGISTRAR LOS REPORTES DOCENTES */
CREATE TABLE [dbo].[CAT_REPORTE_DOCENTE](
	[PK_REPORTE_DOCENTE] [int] IDENTITY(1,1) NOT NULL,
	[PDF] [nvarchar](255) NULL,
	[DOCENTE] [nvarchar](255) NULL,
	[NUMERO] [nvarchar](255) NULL,
	[ALUMNO] [int] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PK_REPORTE_DOCENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAT_REPORTE_DOCENTE] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_REPORTE_DOCENTE] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/*TABLA PARA REGISTRAR LA INFORMACI�N DE LOS EXTERNOS */
CREATE TABLE [dbo].[CATR_EXTERNO](
	[NUMERO_EXTERNO]			[int] IDENTITY(1,1)	NOT NULL,
	[ID_PADRE]					[int]					NULL,
	[ID_USUARIO_REGISTRO]		[int]					NULL,
	[FECHA_REGISTRO]			[datetime]				NULL,
	[ID_USUARIO_MODIFICACION]	[int]					NULL,
	[FECHA_MODIFICACION]		[datetime]				NULL,
	[BORRADO]					[bit]					NULL,
	CONSTRAINT PK_EXTERNO PRIMARY KEY (NUMERO_EXTERNO ASC)
)
ALTER TABLE [dbo].[CATR_EXTERNO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_EXTERNO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/*TABLA PARA REGISTRAR LA INFORMACI�N DE LA DOCUMENTACION */
CREATE TABLE [dbo].[CAT_DOCUMENTACION](
	[PK_DOCUMENTACION] [int] IDENTITY(1,1) NOT NULL,
	[ALUMNO] [nvarchar](255) NULL,
	[CARTA_ACEPTACION] [nvarchar](255) NULL,
	[SOLICITUD] [nvarchar](255) NULL,
	[CARTA_FINALIZACION] [nvarchar](255) NULL,
	[PERIODO] [int] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_DOCUMENTACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAT_DOCUMENTACION] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_DOCUMENTACION] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/*TABLA PARA REGISTRAR LOS PERIODOS HABILES PARA LOS PROCESOS DE RESIDENCIAS*/
CREATE TABLE [dbo].[CAT_PERIODO_RESIDENCIA](
	[PK_PERIODO] [int] IDENTITY(1,1) NOT NULL,
	[FK_AREA_ACADEMICA] [int] NULL,
	[ID_PROCESO] [int] NULL,
	[FECHA_INICIO] [date] NULL,
	[FECHA_FIN] [date] NULL,
	[PERIODO] [int] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_PERIODO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAT_PERIODO_RESIDENCIA] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_PERIODO_RESIDENCIA] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/*TABLA PARA REGISTRAR LA INFORMACION DE LAS EMPRESAS PARA GENERAR LOS CONVENIOS*/
CREATE TABLE [dbo].[CAT_INFO_EMPRESA](
	[PK_INFO_EMPRESA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_EMPRESA] [nvarchar](255) NULL,
	[NOMBRE_REPRESENTANTE] [nvarchar](255) NULL,
	[NO_ACTA_CONSTITUTIVA] [nvarchar](255) NULL,
	[FECHA_FIRMA] [date] NULL,
	[NOMBRE_NOTARIO] [nvarchar](255) NULL,
	[NO_NOTARIA] [nvarchar](255) NULL,
	[ENTIDAD_FEDERATIVA] [nvarchar](255) NULL,
	[FECHA_REGISTRO_E] [date] NULL,
	[FOLIO_MERCANTIL] [nvarchar](255) NULL,
	[NO_VOLUMEN] [nvarchar](255) NULL,
	[OBJETO_SOCIAL] [nvarchar](255) NULL,
	[NO_ESCRITURA] [nvarchar](255) NULL,
	[FECHA_NOTARIO] [date] NULL,
	[NOMBRE_NOTARIO_NOTARIO] [nvarchar](255) NULL,
	[NO_NOTARIA_NOTARIO] [nvarchar](255) NULL,
	[ENTIDAD_FEDERATIVA_NOTARIO] [nvarchar](255) NULL,
	[NO_RFC] [nvarchar](255) NULL,
	[DIR_EMPRESA] [nvarchar](255) NULL,
	[NOMBRE_TESTIGO] [nvarchar](255) NULL,
	[LOGO_EMPRESA] [nvarchar](255) NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_INFO_EMPRESA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAT_INFO_EMPRESA] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_INFO_EMPRESA] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR CALIFICACION DE RESIDENCIAS DE LOS ALUMNOS */
CREATE TABLE [dbo].[CATR_CALIFICACION_ALUMNO](
	[PK_CALIFICACION_ALUMNO] [INT] IDENTITY(1,1) NOT NULL,
	[CALIFICACION] [INT] NULL,
  [TITULACION] [NVARCHAR](255) NULL,
	[OBSERVACIONES] [NVARCHAR](255) NULL,
	[FK_ALUMNO] [INT] NULL,
	[FK_DOCENTE] [INT] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_CALIFICACION_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATR_CALIFICACION_ALUMNO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CATR_CALIFICACION_ALUMNO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR INFORME TECNICO DE RESIDENTE*/
CREATE TABLE [dbo].[CAT_INFORME_ALUMNO](
	[PK_INFORME_ALUMNO] [INT] IDENTITY(1,1) NOT NULL,
	[INFORME] [NVARCHAR](255) NULL,
	[FK_ALUMNO] [INT] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_INFORME_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAT_INFORME_ALUMNO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_INFORME_ALUMNO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR LOS REPORTES DE ASESOR EXTERNO */
CREATE TABLE [dbo].[CAT_REPORTE_EXTERNO](
	[PK_REPORTE_EXTERNO] [int] IDENTITY(1,1) NOT NULL,
	[PDF] [nvarchar](255) NULL,
	[EXTERNO] [int] NULL,
	[NUMERO] [int] NULL,
	[ALUMNO] [int] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[PK_REPORTE_EXTERNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CAT_REPORTE_EXTERNO] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_REPORTE_EXTERNO] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR LA CARTA DE FINALIZACION DE RESIDENCIAS DEL RESIDENTE*/
CREATE TABLE [dbo].[CAT_CARTA_FINALIZACION_RESIDENCIAS](
	[PK_CARTA_FINALIZACION_RESIDENCIAS] [INT] IDENTITY(1,1) NOT NULL,
	[CARTA] [NVARCHAR](255) NULL,
	[FK_ALUMNO] [INT] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED
(
	[PK_CARTA_FINALIZACION_RESIDENCIAS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAT_CARTA_FINALIZACION_RESIDENCIAS] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_CARTA_FINALIZACION_RESIDENCIAS] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR LAS CONFIGURACIONES DE ESCOLARES*/
CREATE TABLE [dbo].[CAT_CONFIGURACION_ESCOLARES](
	[PK_CONFIGURACION_ESCOLARES] [INT] IDENTITY(1,1) NOT NULL,
	[FOLIO] [INT] NULL,
	[FECHA] [DATE] NULL,
	[PERIODO] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED
(
	[PK_CONFIGURACION_ESCOLARES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAT_CONFIGURACION_ESCOLARES] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_CONFIGURACION_ESCOLARES] ADD  DEFAULT ('0') FOR [BORRADO]
GO

/* TABLA PARA REGISTRAR DATOS PARA ACTA DE CALIFICACION*/
CREATE TABLE [dbo].[CAT_CARTA_CALIFICACION_RESIDENCIA](
	[PK_CARTA_CALIFICACION_RESIDENCIA] [INT] IDENTITY(1,1) NOT NULL,
	[FOLIO_ASIGNADO] [NVARCHAR](255) NULL,
	[FECHA] [DATE] NULL,
	[NUMERO_CONTROL] [INT] NULL,
	[FK_USUARIO_REGISTRO] [int] NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[FK_USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[BORRADO] [nchar](1) NOT NULL
PRIMARY KEY CLUSTERED
(
	[PK_CARTA_CALIFICACION_RESIDENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAT_CARTA_CALIFICACION_RESIDENCIA] ADD  DEFAULT (getdate()) FOR [FECHA_REGISTRO]
GO

ALTER TABLE [dbo].[CAT_CARTA_CALIFICACION_RESIDENCIA] ADD  DEFAULT ('0') FOR [BORRADO]
GO