use SWIITL;

/*********************  INICIO MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
INSERT INTO PER_CAT_SISTEMA(NOMBRE, ESTADO) VALUES ('Residencias','0');

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco Proyectos','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Documentacion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Correos','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco vista','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco seleccion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Proyectos','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco edicion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco aprobacion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Maestros','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco Proyectos','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Reporte vista','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Vista comentarios','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Reporte docente','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Vista reportes','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Ficha unica asignacion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Convenios','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Periodos','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Periodos reportes','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Calificacion alumno','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Habilitar residentes','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Reporte asesor externo','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Vista documentacion','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Banco estadistica','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Estadisticas reportes','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Informe tecnico','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Generar convenios','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Configuracion acta','0','0');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN) VALUES ('Informacion residencias','0','0');

INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Jefe Division de Estudios','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Residente','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Jefe Area Academica','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Asesor Docente','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Asesor Externo','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Academia','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Vinculacion','0','3');
INSERT INTO PER_CATR_ROL(NOMBRE,ESTADO,FK_SISTEMA) VALUES ('Jefe de servicios escolares','0','3');

INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','32');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','34');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','38');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','48');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','51');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','53');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('7','54');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('8','32');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('8','33');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('8','36');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('8','37');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('8','43');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','35');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','39');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','40');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','42');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','45');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','46');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','55');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','56');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('9','49');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('10','43');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('10','44');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('10','50');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('11','43');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('11','44');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('12','35');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('13','32');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('13','57');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('14','58');
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES ('14','59');