/*********************  INICIO MODIFICACIONES PUESTA EN PRODUCCIÓN (14-08-2019)  *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      OK
 * PRUEBAS:    OK
 * PRODUCCIÓN: OK
*/


/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE CAPACITACION DOCENTE ******** *
 * *************************************************** */
 USE TECVIRTUAL

/* INICIO TABLA PARA PERIODOS */
CREATE TABLE CAT_PERIODO_CADO(
    PK_PERIODO_CADO        INT  NOT NULL IDENTITY (1,1),
    NOMBRE_PERIODO        VARCHAR(100) NOT NULL,
    FECHA_INICIO          DATETIME NOT NULL,
    FECHA_FIN             DATETIME NOT NULL,
        -- DEFAULT IN ALL TABLES ------>
    -- ESTADO                  SMALLINT     NOT NULL DEFAULT 1,
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PERIODO_CADO
    ADD CONSTRAINT PRK_PERIODO_CADO_CAT_PERIODO_CADO PRIMARY KEY (PK_PERIODO_CADO ASC);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA PERIODOS */


/* INICIO TABLA PARA PARTICIPANTES */
CREATE TABLE CAT_TIPO_PARTICIPANTE_CADO(
    PK_TIPO_PARTICIPANTE_CADO        SMALLINT  NOT NULL,
    NOMBRE_TIPO        VARCHAR(100)  NOT NULL, -- FK
    DESCRIPCION              VARCHAR(100) NULL, --FK
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_TIPO_PARTICIPANTE_CADO
    ADD CONSTRAINT PK_TIPO_PARTICIPANTE_CADO_CAT_TIPO_PARTICIPANTE_CADO PRIMARY KEY (PK_TIPO_PARTICIPANTE_CADO ASC);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA PARTICIPANTES */

/* INICIO TABLA PARA PARTICIPANTES */
CREATE TABLE CAT_PARTICIPANTE_CADO(
    PK_PARTICIPANTE_CADO        INT  NOT NULL IDENTITY (1,1),
    FK_TIPO_PARTICIPANTE        SMALLINT  NOT NULL, -- FK
    FK_USUARIO               INT  NOT NULL, --FK
    --FK_CV                      INT  NULL, --FK
   -- FECHA_INICIO          DATETIME NOT NULL,
   -- FECHA_FIN             DATETIME NOT NULL,
        -- DEFAULT IN ALL TABLES ------>
    -- ESTADO                  SMALLINT     NOT NULL DEFAULT 1,
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT PRK_PARTICIPANTE_CADO_CAT_PARTICIPANTE_CADO PRIMARY KEY (PK_PARTICIPANTE_CADO ASC);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT FRK_TIPO_PARTICIPANTE_CAT_TIPO_PARTICIPANTE_CADO FOREIGN KEY (FK_TIPO_PARTICIPANTE) REFERENCES CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT FRK_USUARIO_CAT_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO(PK_USUARIO);
/* FIN TABLA PARA PARTICIPANTES */

/* INICIO TABLA PARA ESTADOS CURSOS */
CREATE TABLE CAT_ESTADOS_CURSO(
    PK_ESTADO_CURSO        TINYINT  NOT NULL,
    NOMBRE_ESTADO        VARCHAR(100)  NOT NULL, -- FK
    DESCRIPCION              VARCHAR(100) NULL, --FK
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_ESTADOS_CURSO
    ADD CONSTRAINT PK_ESTADO_CURSO_CADO_CAT_ESTADOS_CURSO PRIMARY KEY (PK_ESTADO_CURSO ASC);
/* FIN TABLA PARA ESTADOS CURSOS */

/* INICIO TABLA PARA CURSOS */
CREATE TABLE CAT_CURSO_CADO(
    PK_CAT_CURSO_CADO        INT  NOT NULL IDENTITY (1,1),
    NOMBRE_CURSO            TEXT NOT NULL,
    TIPO_CURSO          TINYINT NOT NULL, --FUTURA FK DE LA TABLA TIPO CURSO
    CUPO_ACTUAL          SMALLINT  NOT NULL DEFAULT 0,
    CUPO_MAXIMO             SMALLINT NOT NULL,
    TOTAL_HORAS             TINYINT NOT NULL,
    FK_AREA_ACADEMICA           INT  NULL, --FK
    FECHA_INICIO             DATE NOT NULL,
    FECHA_FIN             DATE NOT NULL,
    HORA_INICIO             DATETIME NOT NULL,
    HORA_FIN             DATETIME NOT NULL,
    FK_EDIFICIO             INT NOT NULL,
    NOMBRE_ESPACIO             VARCHAR (100)NOT NULL,
    ESTADO                 TINYINT NOT NULL DEFAULT 1, -- FK
    FK_FICHA_TECNICA_CADO        INT  NULL, --FK
    FK_PERIODO_CADO             INT NOT NULL, --FK
    RUTA_IMAGEN_CURSO          NVARCHAR(250) NULL,
        -- DEFAULT IN ALL TABLES ------>
    FK_PARTICIPANTE_REGISTRO     INT NOT NULL, -- FK
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_PARTICIPANTE_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CURSO_CADO
    ADD CONSTRAINT PRK_CAT_CURSO_CADO_CAT_CURSO_CADO PRIMARY KEY (PK_CAT_CURSO_CADO ASC);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_AREA_ACADEMICA_CAT_AREA_ACADEMICA FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA(PK_AREA_ACADEMICA);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_EDIFICIO_CATR_EDIFICIO FOREIGN KEY (FK_EDIFICIO) REFERENCES CATR_EDIFICIO(PK_EDIFICIO);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_PERIODO_CADO_CAT_PERIODO_CADO FOREIGN KEY (FK_PERIODO_CADO) REFERENCES CAT_PERIODO_CADO(PK_PERIODO_CADO);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_PARTICIPANTE_REGISTRO_CAT_PARTICIPANTE_CADO FOREIGN KEY (FK_PARTICIPANTE_REGISTRO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
--    ADD CONSTRAINT FRK_AREA_ACADEMICA_CAT_AREA_ACADEMICA FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA(PK_AREA_ACADEMICA);
/* FIN TABLA PARA CURSOS */

/* INICIO TABLA PARA TABLA RELACION PARTICIPANTE INPARTE CURSO */
CREATE TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO(
    FK_PARTICIPANTE_CADO        INT  NOT NULL,
    FK_CAT_CURSO_CADO        INT  NOT NULL, -- FK
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
     ADD CONSTRAINT FK_PARTICIPANTE_CADO_CATTR_PARTICIPANTE_IMPARTE_CURSO
      FOREIGN KEY (FK_PARTICIPANTE_CADO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
     ADD CONSTRAINT FK_CAT_CURSO_CADO_CATTR_PARTICIPANTE_IMPARTE_CURSO
      FOREIGN KEY (FK_CAT_CURSO_CADO) REFERENCES CAT_CURSO_CADO(PK_CAT_CURSO_CADO);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
    ADD CONSTRAINT PRK_PARTICIPANTE_CADO_FRK_CAT_CURSO_CADO
    PRIMARY KEY (FK_PARTICIPANTE_CADO,FK_CAT_CURSO_CADO);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA TABLA RELACION PARTICIPANTE INPARTE CURSO */

/* INICIO TABLA PARA TABLA RELACION PROPONE  CURSO */
CREATE TABLE CATTR_PARTICIPANTE_PROPONE_CURSO(
    PK_PROPUESTA_CURSO              INT  NOT NULL IDENTITY (1,1),
    FK_PARTICIPANTE_CADO        INT  NOT NULL,
    FK_CAT_CURSO_CADO        INT  NOT NULL, -- FK

            -- DEFAULT IN ALL TABLES ------>
    FECHA_REGISTRO_PROPUESTA      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_PARTICIPANTE_AUTORIZA INT  NULL, --FK
    FECHA_REGISTRO_AUTORIZA      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
    ADD CONSTRAINT PK_PROPUESTA_CURSO_CATTR_PARTICIPANTE_PROPONE_CURSO
    PRIMARY KEY (PK_PROPUESTA_CURSO ASC);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
     ADD CONSTRAINT FK_PARTICIPANTE_CADO_CATTR_PARTICIPANTE_PROPONE_CURSO
      FOREIGN KEY (FK_PARTICIPANTE_CADO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
     ADD CONSTRAINT FK_CAT_CURSO_CADO_CATTR_PARTICIPANTE_PROPONE_CURSO
      FOREIGN KEY (FK_CAT_CURSO_CADO) REFERENCES CAT_CURSO_CADO(PK_CAT_CURSO_CADO);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA TABLA RELACION PARTICIPANTE PROPONE CURSO */

/* INICIO TABLA PARA TABLA CAT_FICHA_TECNICA_CADO */
CREATE TABLE CAT_FICHA_TECNICA_CADO(
    PK_CAT_FICHA_TECNICA    INT  NOT NULL IDENTITY (1,1),
    FK_LUGAR                INT  NOT NULL,-- FK
    INTRODUCCION            NVARCHAR(MAX)  NOT NULL,
    JUSTIFICACION          NVARCHAR(MAX)  NOT NULL,
    OBJETIVO_GENERAL       NVARCHAR(MAX)  NOT NULL,
    TIPO_SERVICIO          INT  NOT NULL,
    OTRO_SERVICIO          VARCHAR(100)   NULL,
    -- RUTA_IMAGEN_CURSO          NVARCHAR(250) NULL,
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_FICHA_TECNICA_CADO
    ADD CONSTRAINT PK_CAT_FICHA_TECNICA_CAT_FICHA_TECNICA_CADO
    PRIMARY KEY (PK_CAT_FICHA_TECNICA ASC);
ALTER TABLE CAT_FICHA_TECNICA_CADO
     ADD CONSTRAINT FK_LUGAR_CAT_FICHA_TECNICA_CADO
      FOREIGN KEY (FK_LUGAR) REFERENCES CAT_INSTITUCION(PK_INSTITUCION);
      -- AGREGAMOS REFERENCIA DE LA FICHA TECNICA EN EL CURSO
ALTER TABLE CAT_CURSO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CADO_CAT_CURSO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA_CADO) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_FICHA_TECNICA_CADO  */

/* INICIO TABLA PARA TABLA CAT_CONTENIDO_TEMATICO_CADO */
CREATE TABLE CAT_CONTENIDO_TEMATICO_CADO(
    PK_CONTENIDO_TEMATICO    INT  NOT NULL IDENTITY (1,1),
    NOMBRE_TEMA             VARCHAR(200)  NOT NULL,
    TIEMPO_TEMA              INT  NOT NULL,
    ACTIVIDAD_APRENDIZAJE   VARCHAR(200)  NOT NULL,
    FK_CAT_FICHA_TECNICA     INT  NOT NULL,-- FK
    INDICE_TEMA     INT  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CONTENIDO_TEMATICO_CADO
    ADD CONSTRAINT PK_CONTENIDO_TEMATICO_CAT_CONTENIDO_TEMATICO_CADO
    PRIMARY KEY (PK_CONTENIDO_TEMATICO ASC);
ALTER TABLE CAT_CONTENIDO_TEMATICO_CADO
     ADD CONSTRAINT FK_CAT_FICHA_TECNICA_CAT_CONTENIDO_TEMATICO_CADO
      FOREIGN KEY (FK_CAT_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_CONTENIDO_TEMATICO_CADO  */


/* INICIO TABLA PARA TABLA CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO */
CREATE TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO(
    PK_ARCHIVO_CONTENIDO_TEMATICO    INT  NOT NULL IDENTITY (1,1),
    FK_CONTENIDO_TEMATICO            INT  NOT NULL,-- FK
    RUTA_ARCHIVO                     VARCHAR(200)  NOT NULL,
    NOMBRE_ARCHIVO                   VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
    ADD CONSTRAINT PK_ARCHIVO_CONTENIDO_TEMATICO_CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
    PRIMARY KEY (PK_ARCHIVO_CONTENIDO_TEMATICO ASC);
ALTER TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
     ADD CONSTRAINT FK_CONTENIDO_TEMATICO_CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
      FOREIGN KEY (FK_CONTENIDO_TEMATICO) REFERENCES CAT_CONTENIDO_TEMATICO_CADO(PK_CONTENIDO_TEMATICO);
/* FIN TABLA PARA TABLA CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO  */

/* INICIO TABLA PARA TABLA CAT_MATERIAL_DIDACTICO_CADO */
CREATE TABLE CAT_MATERIAL_DIDACTICO_CADO(
    PK_MATERIAL_DIDACTICO    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    NOMBRE_MATERIAL                     VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_MATERIAL_DIDACTICO_CADO
    ADD CONSTRAINT PK_MATERIAL_DIDACTICO_CAT_MATERIAL_DIDACTICO_CADO
    PRIMARY KEY (PK_MATERIAL_DIDACTICO ASC);
ALTER TABLE CAT_MATERIAL_DIDACTICO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_MATERIAL_DIDACTICO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_MATERIAL_DIDACTICO_CADO  */

/* INICIO TABLA PARA TABLA CAT_CRITERIO_EVALUACION_CADO */
CREATE TABLE CAT_CRITERIO_EVALUACION_CADO(
    PK_CRITERIO_EVALUACION    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    NOMBRE_CRITERIO             VARCHAR(200)  NOT NULL,
    VALOR_CRITERIO              INT  NOT NULL,
    INSTRUMENTO_DE_EVALUACION    VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CRITERIO_EVALUACION_CADO
    ADD CONSTRAINT PK_CRITERIO_EVALUACION_CAT_CRITERIO_EVALUACION_CADO
    PRIMARY KEY (PK_CRITERIO_EVALUACION ASC);
ALTER TABLE CAT_CRITERIO_EVALUACION_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_CRITERIO_EVALUACION_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_CRITERIO_EVALUACION_CADO  */

/* INICIO TABLA PARA TABLA CAT_COMPETENCIAS_CURSO_CADO */
CREATE TABLE CAT_COMPETENCIAS_CURSO_CADO(
    PK_COMPETENCIA_CURSO    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    TEXTO_COMPETENCIA             VARCHAR(500)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_COMPETENCIAS_CURSO_CADO
    ADD CONSTRAINT PK_COMPETENCIA_CURSO_CAT_COMPETENCIAS_CURSO_CADO
    PRIMARY KEY (PK_COMPETENCIA_CURSO ASC);
ALTER TABLE CAT_COMPETENCIAS_CURSO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_COMPETENCIAS_CURSO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_COMPETENCIAS_CURSO_CADO  */

/* INICIO TABLA PARA TABLA CAT_FUENTE_INFORMACION_CADO */
CREATE TABLE CAT_FUENTE_INFORMACION_CADO(
    PK_FUENTE_INFORMACION    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    TEXTO_FUENTE             VARCHAR(500)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_FUENTE_INFORMACION_CADO
    ADD CONSTRAINT PK_FUENTE_INFORMACION_CAT_FUENTE_INFORMACION_CADO
    PRIMARY KEY (PK_FUENTE_INFORMACION ASC);
ALTER TABLE CAT_FUENTE_INFORMACION_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_FUENTE_INFORMACION_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_FUENTE_INFORMACION_CADO  */

/* INICIO TABLA PARA TABLA CAT_COMENTARIO_FICHA_CADO */
CREATE TABLE CAT_COMENTARIO_FICHA_CADO(
    PK_COMENTARIO_CADO    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    TEXTO_COMENTARIO             VARCHAR(500)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_PARTICIPANTE_REGISTRO     INT  NOT NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_COMENTARIO_FICHA_CADO
    ADD CONSTRAINT PK_COMENTARIO_CADO_CAT_COMENTARIO_FICHA_CADO
    PRIMARY KEY (PK_COMENTARIO_CADO ASC);
ALTER TABLE CAT_COMENTARIO_FICHA_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_COMENTARIO_FICHA_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
ALTER TABLE CAT_COMENTARIO_FICHA_CADO
     ADD CONSTRAINT FK_PARTICIPANTE_REGISTRO_CAT_COMENTARIO_FICHA_CADO
      FOREIGN KEY (FK_PARTICIPANTE_REGISTRO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
/* FIN TABLA PARA TABLA CAT_COMENTARIO_FICHA_CADO  */


/* INICIO TABLA PARA TABLA CAT_CV_PARTICIPANTE_CADO */
CREATE TABLE CAT_CV_PARTICIPANTE_CADO(
    PK_CV_PARTICIPANTE    INT  NOT NULL IDENTITY (1,1),
    RFC                      VARCHAR(30)  NOT NULL,
    BIOGRAFIA                VARCHAR(500)  NOT NULL,
    FK_PARTICIPANTE_CADO    INT  NOT NULL,-- FK,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CV_PARTICIPANTE_CADO
    ADD CONSTRAINT PK_CV_PARTICIPANTE_CAT_CV_PARTICIPANTE_CADO
    PRIMARY KEY (PK_CV_PARTICIPANTE ASC);
ALTER TABLE CAT_CV_PARTICIPANTE_CADO
     ADD CONSTRAINT FK_PARTICIPANTE_CADO_CAT_CV_PARTICIPANTE_CADO
      FOREIGN KEY (FK_PARTICIPANTE_CADO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
/* FIN TABLA PARA TABLA CAT_CV_PARTICIPANTE_CADO  */

/* INICIO TABLA PARA TABLA CAT_TIPO_FORMACIÓN_ACADEMICA_CADO */
CREATE TABLE CAT_TIPO_FORMACION_ACADEMICA_CADO(
    PK_TIPO_FORMACION_ACADEMICA    INT  NOT NULL ,
    NOMBRE_TIPO                      VARCHAR(100)  NOT NULL,
    DESCRIPCION                    VARCHAR(100)  NOT NULL,    
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_TIPO_FORMACION_ACADEMICA_CADO
    ADD CONSTRAINT PK_TIPO_FORMACION_ACADEMICA_CAT_TIPO_FORMACION_ACADEMICA_CADO
    PRIMARY KEY (PK_TIPO_FORMACION_ACADEMICA ASC);
/* FIN TABLA PARA TABLA CAT_TIPO_FORMACION_ACADEMICA_CADO  */

/* INICIO TABLA PARA TABLA CAT_FORMACION_ACADEMICA_CV_CADO */
CREATE TABLE CAT_FORMACION_ACADEMICA_CV_CADO(
    PK_FORMACION_ACADEMICA_CV    INT  NOT NULL IDENTITY (1,1),
    FK_CV                        INT  NOT NULL,-- FK,
    TIPO_FORMACION               TINYINT NOT NULL,
    OTRO_TIPO                    VARCHAR(200)  NULL,
    NOMBRE_CARRERA               VARCHAR(200) NOT NULL,
    INSTITUCION                  VARCHAR(200) NOT NULL,
    FECHA_TITULACION             DATE NOT NULL,
    CEDULA_PROFESIONAL           INT   NULL,    
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_FORMACION_ACADEMICA_CV_CADO
    ADD CONSTRAINT PK_FORMACION_ACADEMICA_CV_CAT_FORMACION_ACADEMICA_CV_CADO
    PRIMARY KEY (PK_FORMACION_ACADEMICA_CV ASC);
ALTER TABLE CAT_FORMACION_ACADEMICA_CV_CADO
     ADD CONSTRAINT FK_CV_CAT_FORMACION_ACADEMICA_CV_CADO
   FOREIGN KEY (FK_CV) REFERENCES CAT_CV_PARTICIPANTE_CADO(PK_CV_PARTICIPANTE);  
/* FIN TABLA PARA TABLA CAT_FORMACION_ACADEMICA_CV_CADO  */



/* INICIO TABLA PARA TABLA CAT_EXPERIENCIA_LABORAL_CV_CADO */
CREATE TABLE CAT_EXPERIENCIA_LABORAL_CV_CADO(
    PK_EXPERIENCIA_LABORAL_CV    INT  NOT NULL IDENTITY (1,1),
    FK_CV                        INT  NOT NULL,-- FK,
    NOMBRE_PUESTO                VARCHAR(200) NOT NULL,
    NOMBRE_EMPRESA               VARCHAR(200) NOT NULL,
    FECHA_INICIO_PERMANENCIA     DATE NOT NULL,
    FECHA_FIN_PERMANENCIA        DATE  NULL, --falta modificar en el código
    ACTIVIDADES_A_CARGO          VARCHAR(400) NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_EXPERIENCIA_LABORAL_CV_CADO
    ADD CONSTRAINT PK_FORMACION_ACADEMICA_CV_CAT_EXPERIENCIA_LABORAL_CV_CADO
    PRIMARY KEY (PK_EXPERIENCIA_LABORAL_CV ASC);
ALTER TABLE CAT_EXPERIENCIA_LABORAL_CV_CADO
     ADD CONSTRAINT FK_CV_CAT_EXPERIENCIA_LABORAL_CV_CADO
   FOREIGN KEY (FK_CV) REFERENCES CAT_CV_PARTICIPANTE_CADO(PK_CV_PARTICIPANTE);  
/* FIN TABLA PARA TABLA CAT_EXPERIENCIA_LABORAL_CV_CADO  */

/* INICIO TABLA PARA TABLA CAT_EXPERIENCIA_DOCENTE_CV_CADO */
CREATE TABLE CAT_EXPERIENCIA_DOCENTE_CV_CADO(
    PK_EXPERIENCIA_DOCENTE_CV    INT  NOT NULL IDENTITY (1,1),
    FK_CV                        INT  NOT NULL,-- FK,
    NOMBRE_MATERIA               VARCHAR(200) NOT NULL,
    FK_INSTITUCION               INT  NOT NULL,
    NOMBRE_OTRA_INSTITUCION      VARCHAR(200)  NULL, 
    FECHA_INICIO_PERIODO        DATE NOT NULL,
    FECHA_FIN_PERIODO           DATE NOT NULL,    
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_EXPERIENCIA_DOCENTE_CV_CADO
    ADD CONSTRAINT PK_EXPERIENCIA_DOCENTE_CV_CAT_EXPERIENCIA_DOCENTE_CV_CADO
    PRIMARY KEY (PK_EXPERIENCIA_DOCENTE_CV ASC);
ALTER TABLE CAT_EXPERIENCIA_DOCENTE_CV_CADO
     ADD CONSTRAINT FK_CV_CAT_EXPERIENCIA_DOCENTE_CV_CADO
   FOREIGN KEY (FK_CV) REFERENCES CAT_CV_PARTICIPANTE_CADO(PK_CV_PARTICIPANTE);  
/* FIN TABLA PARA TABLA CAT_EXPERIENCIA_DOCENTE_CV_CADO  */


/* INICIO TABLA PARA TABLA CAT_PRODUCTOS_ACADEMICOS_CV_CADO */
CREATE TABLE CAT_PRODUCTOS_ACADEMICOS_CV_CADO(
    PK_PRODUCTOS_ACADEMICOS_CV   INT  NOT NULL IDENTITY (1,1),
    FK_CV                        INT  NOT NULL,-- FK,
    NOMBRE_PRODUCTO              VARCHAR(200) NOT NULL,
    DESCRIPCION                  VARCHAR(300) NOT NULL,
    FECHA_PRODUCTO               DATE NOT NULL,  
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PRODUCTOS_ACADEMICOS_CV_CADO
    ADD CONSTRAINT PK_PRODUCTOS_ACADEMICOS_CV_CAT_PRODUCTOS_ACADEMICOS_CV_CADO
    PRIMARY KEY (PK_PRODUCTOS_ACADEMICOS_CV ASC);
ALTER TABLE CAT_PRODUCTOS_ACADEMICOS_CV_CADO
     ADD CONSTRAINT FK_CV_CAT_PRODUCTOS_ACADEMICOS_CV_CADO
   FOREIGN KEY (FK_CV) REFERENCES CAT_CV_PARTICIPANTE_CADO(PK_CV_PARTICIPANTE);  
/* FIN TABLA PARA TABLA CAT_PRODUCTOS_ACADEMICOS_CV_CADO  */

/* INICIO TABLA PARA TABLA CAT_PARTICIPACION_INSTRUCTOR_CV_CADO */
CREATE TABLE CAT_PARTICIPACION_INSTRUCTOR_CV_CADO(
    PK_PARTICIPACION_INSTRUCTOR_CV   INT  NOT NULL IDENTITY (1,1),
    FK_CV                            INT  NOT NULL,-- FK,
    TITULO_CURSO                     VARCHAR(200) NOT NULL,
    NOMBRE_INSTITUCION               VARCHAR(200) NOT NULL,
    HRS_DURACION_CURSO               INT  NOT NULL,
    FECHA_IMPARTICION                DATE NOT NULL,  
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT   NULL,-- FK,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PARTICIPACION_INSTRUCTOR_CV_CADO
    ADD CONSTRAINT PK_PARTICIPACION_INSTRUCTOR_CV_CAT_PARTICIPACION_INSTRUCTOR_CV_CADO
    PRIMARY KEY (PK_PARTICIPACION_INSTRUCTOR_CV ASC);
ALTER TABLE CAT_PARTICIPACION_INSTRUCTOR_CV_CADO
     ADD CONSTRAINT FK_CV_CAT_PARTICIPACION_INSTRUCTOR_CV_CADO
   FOREIGN KEY (FK_CV) REFERENCES CAT_CV_PARTICIPANTE_CADO(PK_CV_PARTICIPANTE);  
/* FIN TABLA PARA TABLA CAT_PARTICIPACION_INSTRUCTOR_CV_CADO  */



/*************************************************** *
 * ********** FINALIZA LA CREACIÓN DE TABLAS DE CAPACITACION DOCENTE ******** *
 * *************************************************** */


/******************************************************************************************************* *
 * ********** COMIENZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */


-- CREACION DEL SISTEMA
INSERT INTO PER_CAT_SISTEMA(NOMBRE, RUTA_ANGULAR, ABREVIATURA, CORREO1, INDICIO1)
VALUES('Capacitación docente', 'capacitacion', 'CADO', 'cado@itleon.edu.mx', 'cado');

--select * from PER_CAT_SISTEMA;
--se debE asignar el FK_SISTEMA obtenido al realizar el insert anterior
INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (5, 'Coordinador', 'COORD_CADO');

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (5, 'Participante', 'PART_CADO');

--select * from PER_CAT_ROL;

--SE CREAN LOS MODULOS
--INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)VALUES ('Periodos', 1, 1);
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Periodos',1,1,  'e990c920d0d77fa0937fce0bc4e5a67b' ,  'Lista de periodos intersemestrales'
 ,  'periodos');
 INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Cursos',1,1,  'fdf484eeeb011a5fb52cf33751b4e22f' ,
  'Lista de Cursos de Capacitación' , 'cursos');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Captura cursos',1,1,  '7b44125ec5b3b7b61b000cdee93c6796' ,
  'Módulo de Captura' , 'captura_cursos');
  INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Curriculum',1,1,  'de3ec0aa2234aa1e3ee275bbc715c6c9' ,
  'CV del instructor' , 'cv');
    INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Convocatoria',1,1,  '1191b30011f35ae3bfa0e376dbdff635' ,
  'Convocatoria de cursos' , 'convocatoria');
   INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Modificar curriculum',1,1,  'b0ea21e8d9f5703448517968a9403973' ,
  'Apartado para modificar CV del instructor' , 'modificar_cv');

--select * from PER_CAT_MODULO

--select * from CAT_USUARIO
-- EL ROL Y EL MODULO SE DEBEN RELACIONAR ACORDE A LAS PK OBTENIDAS CON LOS INSERTS ANTERIORES
-- ROL DE COORDINADOR Y MODULO DE PERIODOS Y CURSOS
-- SELECT * FROM PER_CAT_ROL where pK_ROL =23 ;
-- SELECT * FROM PER_CAT_MODULO
-- SELECT * FROM PER_TR_ROL_MODULO where fK_ROL =23
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (22, 71);--periodo
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (22, 72);--cursos
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (22,93);--convocatoria

-- ROL DE PARTICIPANTE Y MODULO DE CURSOS
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (23, 72);--cursos
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (23,92);--cv
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (23,93);--convocatoria
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (23,94);--modificar cv

--SELECT * FROM PER_TR_ROL_MODULO
-- INSERT PARA ASIGNAR EL ROL AL USUARIO
INSERT INTO PER_TR_ROL_USUARIO(FK_ROL, FK_USUARIO)
VALUES (22, 1353); --coordinador
INSERT INTO PER_TR_ROL_USUARIO(FK_ROL, FK_USUARIO)
VALUES (2, 1384); --participante

-- SELECT * FROM PER_TR_ROL_USUARIO where FK_USUARIO in(951)
 --delete FROM PER_TR_ROL_USUARIO  where FK_USUARIO in(951) and FK_ROL=22
--select * from CAT_USUARIO where  pK_USUARIO in(1353,951,1005);
--select * from CAT_USUARIO where  PRIMER_APELLIDO like '%peñ%';

-- CREACION DE TIPOS PARTICIPANTES
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( PK_TIPO_PARTICIPANTE_CADO,NOMBRE_TIPO, DESCRIPCION)
VALUES(1,'Instructor', 'Personal del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(2,'Participante', 'Personal del ITL que puede inscribirse a los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(3,'Instructor externo', 'Personal externo del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(4,'Coordinador', 'Personal del ITL que se encarga de gestionar los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(5,'Jefe Desarrollo Académico', 'Jefe del Departamento de Desarollo Académico');
-- select * from CAT_TIPO_PARTICIPANTE_CADO

-- CREACION DE ESTADOS CURSO
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(1,'ASIGNADO', 'Asignado a un instructor');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(2,'AUTORIZADO', 'Autorizado y listo para la convocatoria');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(3,'RECHAZADO', 'Rechazado por que la ficha técnica no cumple con los requisitos');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(4,'EVALUADO', 'El curso termino, y ha sido evaluado por los participantes');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(5,'ENVIADO A REVISIÓN', 'Cuenta con ficha técnica y cv del instructor para ser revisado');

-- CREACION DE PARTICIPANTE COORDINADOR
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(4, 1353); -- VALIDAR PK A LA HORA DE IMPLEMENTAR
-- select * from CAT_PARTICIPANTE_CADO
-- CREACION DE PARTICIPANTE JEFE DESARROLLO ACADEMICO
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(5, X); -- VALIDAR PK A LA HORA DE IMPLEMENTAR
select * from CAT_PARTICIPANTE_CADO
/*CATALAGOS DE CV */

INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(1,'Licenciatura', 'TIPO DE FORMACIÓN NIVEL LICENCIATURA');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(2,'Maestría', 'TIPO DE FORMACIÓN NIVEL MAESTRÍA');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(3,'Doctorado', 'TIPO DE FORMACIÓN NIVEL DOCTORADO');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(4,'Especialidad', 'TIPO DE FORMACIÓN DE ALGUNA ESPECIALIDAD');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(5,'Otros estudios', 'TIPO DE FORMACIÓN DE OTRO TIPO DE ESTUDIOS QUE NO ESTA EN LA LISTA');


/******************************************************************************************************* *
 * ********** FINALIZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */

