/******************************************************************************************************* *
 * ********** COMIENZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */

-- CREACION DEL SISTEMA - PASO 1
INSERT INTO PER_CAT_SISTEMA(NOMBRE, RUTA_ANGULAR, ABREVIATURA, CORREO1, INDICIO1)
VALUES (
	'Capacitación docente',
	'capacitacion',
	'CADO',
	'cado@itleon.edu.mx',
	'cado'
);

--select * from PER_CAT_SISTEMA;
--se debE asignar el FK_SISTEMA obtenido al realizar el insert anterior - PASO 2
INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (
    (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE ABREVIATURA = 'CADO'),
    'Coordinador',
    'COORD_CADO'
);

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (
    (SELECT PK_SISTEMA FROM PER_CAT_SISTEMA WHERE ABREVIATURA = 'CADO'),
    'Participante',
    'PART_CADO'
);

--select * from PER_CAT_ROL;

--SE CREAN LOS MODULOS
--INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)VALUES ('Periodos', 1, 1);
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Periodos',1,1,  'e990c920d0d77fa0937fce0bc4e5a67b' ,  'Lista de periodos intersemestrales'
 ,  'periodos');

 INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Cursos',1,1,  'fdf484eeeb011a5fb52cf33751b4e22f' ,
  'Lista de Cursos de Capacitación' , 'cursos');

INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Captura cursos',1,1,  '7b44125ec5b3b7b61b000cdee93c6796' ,
  'Módulo de Captura' , 'captura_cursos');

  INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Curriculum',1,1,  'de3ec0aa2234aa1e3ee275bbc715c6c9' ,
  'CV del instructor' , 'cv');

    INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Convocatoria',1,1,  '1191b30011f35ae3bfa0e376dbdff635' ,
  'Convocatoria de cursos' , 'convocatoria');

   INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Modificar curriculum',1,1,  'b0ea21e8d9f5703448517968a9403973' ,
  'Apartado para modificar CV del instructor' , 'modificar_cv');

--select * from PER_CAT_MODULO

--select * from CAT_USUARIO
-- EL ROL Y EL MODULO SE DEBEN RELACIONAR ACORDE A LAS PK OBTENIDAS CON LOS INSERTS ANTERIORES
-- ROL DE COORDINADOR Y MODULO DE PERIODOS Y CURSOS
-- SELECT * FROM PER_CAT_ROL;
-- SELECT * FROM PER_CAT_MODULO

--periodo
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORD_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = 'e990c920d0d77fa0937fce0bc4e5a67b')
);

--cursos
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORD_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = 'fdf484eeeb011a5fb52cf33751b4e22f')
);

--convocatoria
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORD_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = '1191b30011f35ae3bfa0e376dbdff635')
);

-- ROL DE PARTICIPANTE Y MODULO DE CURSOS
--cursos
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'PART_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = 'fdf484eeeb011a5fb52cf33751b4e22f')
);

--cv
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'PART_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = 'de3ec0aa2234aa1e3ee275bbc715c6c9')
);

--convocatoria
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'PART_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = '1191b30011f35ae3bfa0e376dbdff635')
);

-- modificar cv
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO) VALUES
(
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'PART_CADO'),
    (SELECT PK_MODULO FROM PER_CAT_MODULO WHERE RUTA_MD5 = 'b0ea21e8d9f5703448517968a9403973')
);


--SELECT * FROM PER_TR_ROL_MODULO
-- INSERT PARA ASIGNAR EL ROL AL USUARIO
-- KARINA ESTRADA
INSERT INTO PER_TR_ROL_USUARIO(FK_ROL, FK_USUARIO)
VALUES (
    (SELECT PK_ROL FROM PER_CAT_ROL WHERE ABREVIATURA = 'COORD_CADO'),
    (SELECT PK_USUARIO FROM CAT_USUARIO WHERE NUMERO_CONTROL = '978')
);

-- SELECT * FROM PER_TR_ROL_USUARIO

-- CREACION DE TIPOS PARTICIPANTES
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( PK_TIPO_PARTICIPANTE_CADO,NOMBRE_TIPO, DESCRIPCION)
VALUES(1,'Instructor', 'Personal del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(2,'Participante', 'Personal del ITL que puede inscribirse a los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(3,'Instructor externo', 'Personal externo del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(4,'Coordinador', 'Personal del ITL que se encarga de gestionar los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO, NOMBRE_TIPO, DESCRIPCION)
VALUES(5,'Jefe Desarrollo Académico', 'Jefe del Departamento de Desarollo Académico');
-- select * from CAT_TIPO_PARTICIPANTE_CADO

-- CREACION DE ESTADOS CURSO
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(1,'ASIGNADO', 'Asignado a un instructor');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(2,'AUTORIZADO', 'Autorizado y listo para la convocatoria');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(3,'RECHAZADO', 'Rechazado por que la ficha técnica no cumple con los requisitos');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(4,'EVALUADO', 'El curso termino, y ha sido evaluado por los participantes');
INSERT INTO CAT_ESTADOS_CURSO(PK_ESTADO_CURSO, NOMBRE_ESTADO, DESCRIPCION)
VALUES(5,'ENVIADO A REVISIÓN', 'Cuenta con ficha técnica y cv del instructor para ser revisado');

-- CREACION DE PARTICIPANTE COORDINADOR
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(
	(SELECT PK_TIPO_PARTICIPANTE_CADO FROM CAT_TIPO_PARTICIPANTE_CADO WHERE NOMBRE_TIPO = 'Coordinador'),
 	(SELECT PK_USUARIO FROM CAT_USUARIO WHERE NUMERO_CONTROL = '978')
); -- VALIDAR PK A LA HORA DE IMPLEMENTAR

/*CATALAGOS DE CV */

INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(1,'Licenciatura', 'TIPO DE FORMACIÓN NIVEL LICENCIATURA');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(2,'Maestría', 'TIPO DE FORMACIÓN NIVEL MAESTRÍA');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(3,'Doctorado', 'TIPO DE FORMACIÓN NIVEL DOCTORADO');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(4,'Especialidad', 'TIPO DE FORMACIÓN DE ALGUNA ESPECIALIDAD');
INSERT INTO CAT_TIPO_FORMACION_ACADEMICA_CADO(PK_TIPO_FORMACION_ACADEMICA, NOMBRE_TIPO, DESCRIPCION)
VALUES(5,'Otros estudios', 'TIPO DE FORMACIÓN DE OTRO TIPO DE ESTUDIOS QUE NO ESTA EN LA LISTA');


/******************************************************************************************************* *
 * ********** FINALIZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */





-- ------------------------------------------------------- -
-- ------ CAMBIOS PENDIENTES EN QA Y PRODUCCIÓN ---------- -
-- ------------------------------------------------------- -

-- select * from CAT_PARTICIPANTE_CADO
-- CREACION DE PARTICIPANTE JEFE DESARROLLO ACADEMICO
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(5, X); -- VALIDAR PK A LA HORA DE IMPLEMENTAR