/*********************  INICIO MODIFICACIONES PUESTA EN PRODUCCIÓN (14-08-2019)  *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      OK
 * PRUEBAS:    OK
 * PRODUCCIÓN: OK
*/


/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE CAPACITACION DOCENTE ******** *
 * *************************************************** */
 USE TECVIRTUAL

/* INICIO TABLA PARA PERIODOS */
CREATE TABLE CAT_PERIODO_CADO(
    PK_PERIODO_CADO        INT  NOT NULL IDENTITY (1,1),
    NOMBRE_PERIODO        VARCHAR(100) NOT NULL,
    FECHA_INICIO          DATETIME NOT NULL,
    FECHA_FIN             DATETIME NOT NULL,
        -- DEFAULT IN ALL TABLES ------>
    -- ESTADO                  SMALLINT     NOT NULL DEFAULT 1,
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PERIODO_CADO
    ADD CONSTRAINT PRK_PERIODO_CADO_CAT_PERIODO_CADO PRIMARY KEY (PK_PERIODO_CADO ASC);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA PERIODOS */


/* INICIO TABLA PARA PARTICIPANTES */
CREATE TABLE CAT_TIPO_PARTICIPANTE_CADO(
    PK_TIPO_PARTICIPANTE_CADO        SMALLINT  NOT NULL IDENTITY (1,1),
    NOMBRE_TIPO        VARCHAR(100)  NOT NULL, -- FK
    DESCRIPCION              VARCHAR(100) NULL, --FK
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_TIPO_PARTICIPANTE_CADO
    ADD CONSTRAINT PK_TIPO_PARTICIPANTE_CADO_CAT_TIPO_PARTICIPANTE_CADO PRIMARY KEY (PK_TIPO_PARTICIPANTE_CADO ASC);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA PARTICIPANTES */

/* INICIO TABLA PARA PARTICIPANTES */
CREATE TABLE CAT_PARTICIPANTE_CADO(
    PK_PARTICIPANTE_CADO        INT  NOT NULL IDENTITY (1,1),
    FK_TIPO_PARTICIPANTE        SMALLINT  NOT NULL, -- FK
    FK_USUARIO               INT  NOT NULL, --FK
    FK_CV                      INT  NULL, --FK
   -- FECHA_INICIO          DATETIME NOT NULL,
   -- FECHA_FIN             DATETIME NOT NULL,
        -- DEFAULT IN ALL TABLES ------>
    -- ESTADO                  SMALLINT     NOT NULL DEFAULT 1,
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT PRK_PARTICIPANTE_CADO_CAT_PARTICIPANTE_CADO PRIMARY KEY (PK_PARTICIPANTE_CADO ASC);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT FRK_TIPO_PARTICIPANTE_CAT_TIPO_PARTICIPANTE_CADO FOREIGN KEY (FK_TIPO_PARTICIPANTE) REFERENCES CAT_TIPO_PARTICIPANTE_CADO(PK_TIPO_PARTICIPANTE_CADO);
ALTER TABLE CAT_PARTICIPANTE_CADO
    ADD CONSTRAINT FRK_USUARIO_CAT_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES CAT_USUARIO(PK_USUARIO);
/* FIN TABLA PARA PARTICIPANTES */



/* INICIO TABLA PARA CURSOS */
CREATE TABLE CAT_CURSO_CADO(
    PK_CAT_CURSO_CADO        INT  NOT NULL IDENTITY (1,1),
    NOMBRE_CURSO            TEXT NOT NULL,
    TIPO_CURSO          TINYINT NOT NULL, --FUTURA FK DE LA TABLA TIPO CURSO
    CUPO_ACTUAL          SMALLINT  NOT NULL DEFAULT 0,
    CUPO_MAXIMO             SMALLINT NOT NULL,
    TOTAL_HORAS             TINYINT NOT NULL,
    FK_AREA_ACADEMICA           INT  NULL, --FK
    FECHA_INICIO             DATE NOT NULL,
    FECHA_FIN             DATE NOT NULL,
    HORA_INICIO             DATETIME NOT NULL,
    HORA_FIN             DATETIME NOT NULL,
    FK_EDIFICIO             INT NOT NULL,
    NOMBRE_ESPACIO             VARCHAR (100)NOT NULL,
    ESTADO                 TINYINT NOT NULL DEFAULT 1, -- FK
    FK_FICHA_TECNICA_CADO        INT  NULL, --FK
    FK_PERIODO_CADO             INT NOT NULL, --FK
    RUTA_IMAGEN_CURSO          NVARCHAR(250) NULL,
        -- DEFAULT IN ALL TABLES ------>
    FK_PARTICIPANTE_REGISTRO     INT NOT NULL, -- FK
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_PARTICIPANTE_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CURSO_CADO
    ADD CONSTRAINT PRK_CAT_CURSO_CADO_CAT_CURSO_CADO PRIMARY KEY (PK_CAT_CURSO_CADO ASC);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_AREA_ACADEMICA_CAT_AREA_ACADEMICA FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA(PK_AREA_ACADEMICA);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_EDIFICIO_CATR_EDIFICIO FOREIGN KEY (FK_EDIFICIO) REFERENCES CATR_EDIFICIO(PK_EDIFICIO);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_PERIODO_CADO_CAT_PERIODO_CADO FOREIGN KEY (FK_PERIODO_CADO) REFERENCES CAT_PERIODO_CADO(PK_PERIODO_CADO);
ALTER TABLE CAT_CURSO_CADO
   ADD CONSTRAINT FRK_PARTICIPANTE_REGISTRO_CAT_PARTICIPANTE_CADO FOREIGN KEY (FK_PARTICIPANTE_REGISTRO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
--    ADD CONSTRAINT FRK_AREA_ACADEMICA_CAT_AREA_ACADEMICA FOREIGN KEY (FK_AREA_ACADEMICA) REFERENCES CAT_AREA_ACADEMICA(PK_AREA_ACADEMICA);
/* FIN TABLA PARA CURSOS */

/* INICIO TABLA PARA TABLA RELACION PARTICIPANTE INPARTE CURSO */
CREATE TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO(
    FK_PARTICIPANTE_CADO        INT  NOT NULL,
    FK_CAT_CURSO_CADO        INT  NOT NULL, -- FK
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
     ADD CONSTRAINT FK_PARTICIPANTE_CADO_CATTR_PARTICIPANTE_IMPARTE_CURSO
      FOREIGN KEY (FK_PARTICIPANTE_CADO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
     ADD CONSTRAINT FK_CAT_CURSO_CADO_CATTR_PARTICIPANTE_IMPARTE_CURSO
      FOREIGN KEY (FK_CAT_CURSO_CADO) REFERENCES CAT_CURSO_CADO(PK_CAT_CURSO_CADO);
ALTER TABLE CATTR_PARTICIPANTE_IMPARTE_CURSO
    ADD CONSTRAINT PRK_PARTICIPANTE_CADO_FRK_CAT_CURSO_CADO
    PRIMARY KEY (FK_PARTICIPANTE_CADO,FK_CAT_CURSO_CADO);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA TABLA RELACION PARTICIPANTE INPARTE CURSO */

/* INICIO TABLA PARA TABLA RELACION PROPONE  CURSO */
CREATE TABLE CATTR_PARTICIPANTE_PROPONE_CURSO(
    PK_PROPUESTA_CURSO              INT  NOT NULL IDENTITY (1,1),
    FK_PARTICIPANTE_CADO        INT  NOT NULL,
    FK_CAT_CURSO_CADO        INT  NOT NULL, -- FK

            -- DEFAULT IN ALL TABLES ------>
    FECHA_REGISTRO_PROPUESTA      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_PARTICIPANTE_AUTORIZA INT  NULL, --FK
    FECHA_REGISTRO_AUTORIZA      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
    ADD CONSTRAINT PK_PROPUESTA_CURSO_CATTR_PARTICIPANTE_PROPONE_CURSO
    PRIMARY KEY (PK_PROPUESTA_CURSO ASC);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
     ADD CONSTRAINT FK_PARTICIPANTE_CADO_CATTR_PARTICIPANTE_PROPONE_CURSO
      FOREIGN KEY (FK_PARTICIPANTE_CADO) REFERENCES CAT_PARTICIPANTE_CADO(PK_PARTICIPANTE_CADO);
ALTER TABLE CATTR_PARTICIPANTE_PROPONE_CURSO
     ADD CONSTRAINT FK_CAT_CURSO_CADO_CATTR_PARTICIPANTE_PROPONE_CURSO
      FOREIGN KEY (FK_CAT_CURSO_CADO) REFERENCES CAT_CURSO_CADO(PK_CAT_CURSO_CADO);
    -- ADD CONSTRAINT FRK_CAT_PERIODO_CADO_CF_ESTADOS_PERIODO FOREIGN KEY (FK_USUARIO_REGISTRO) REFERENCES CF_ESTADOS_PERIODO(PK_VALOR);
/* FIN TABLA PARA TABLA RELACION PARTICIPANTE PROPONE CURSO */

/* INICIO TABLA PARA TABLA CAT_FICHA_TECNICA_CADO */
CREATE TABLE CAT_FICHA_TECNICA_CADO(
    PK_CAT_FICHA_TECNICA    INT  NOT NULL IDENTITY (1,1),
    FK_LUGAR                INT  NOT NULL,-- FK
    INTRODUCCION            NVARCHAR(MAX)  NOT NULL,
    JUSTIFICACION          NVARCHAR(MAX)  NOT NULL,
    OBJETIVO_GENERAL       NVARCHAR(MAX)  NOT NULL,
    TIPO_SERVICIO          INT  NOT NULL,
    OTRO_SERVICIO          VARCHAR(100)   NULL,
    -- RUTA_IMAGEN_CURSO          NVARCHAR(250) NULL,
            -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_FICHA_TECNICA_CADO
    ADD CONSTRAINT PK_CAT_FICHA_TECNICA_CAT_FICHA_TECNICA_CADO
    PRIMARY KEY (PK_CAT_FICHA_TECNICA ASC);
ALTER TABLE CAT_FICHA_TECNICA_CADO
     ADD CONSTRAINT FK_LUGAR_CAT_FICHA_TECNICA_CADO
      FOREIGN KEY (FK_LUGAR) REFERENCES CAT_INSTITUCION(PK_INSTITUCION);
      -- AGREGAMOS REFERENCIA DE LA FICHA TECNICA EN EL CURSO
ALTER TABLE CAT_CURSO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CADO_CAT_CURSO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA_CADO) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_FICHA_TECNICA_CADO  */

/* INICIO TABLA PARA TABLA CAT_CONTENIDO_TEMATICO_CADO */
CREATE TABLE CAT_CONTENIDO_TEMATICO_CADO(
    PK_CONTENIDO_TEMATICO    INT  NOT NULL IDENTITY (1,1),
    NOMBRE_TEMA             VARCHAR(200)  NOT NULL,
    TIEMPO_TEMA              INT  NOT NULL,
    ACTIVIDAD_APRENDIZAJE   VARCHAR(200)  NOT NULL,
    FK_CAT_FICHA_TECNICA     INT  NOT NULL,-- FK
    INDICE_TEMA     INT  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CONTENIDO_TEMATICO_CADO
    ADD CONSTRAINT PK_CONTENIDO_TEMATICO_CAT_CONTENIDO_TEMATICO_CADO
    PRIMARY KEY (PK_CONTENIDO_TEMATICO ASC);
ALTER TABLE CAT_CONTENIDO_TEMATICO_CADO
     ADD CONSTRAINT FK_CAT_FICHA_TECNICA_CAT_CONTENIDO_TEMATICO_CADO
      FOREIGN KEY (FK_CAT_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_CONTENIDO_TEMATICO_CADO  */


/* INICIO TABLA PARA TABLA CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO */
CREATE TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO(
    PK_ARCHIVO_CONTENIDO_TEMATICO    INT  NOT NULL IDENTITY (1,1),
    FK_CONTENIDO_TEMATICO            INT  NOT NULL,-- FK
    RUTA_ARCHIVO                     VARCHAR(200)  NOT NULL,
    NOMBRE_ARCHIVO                   VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
    ADD CONSTRAINT PK_ARCHIVO_CONTENIDO_TEMATICO_CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
    PRIMARY KEY (PK_ARCHIVO_CONTENIDO_TEMATICO ASC);
ALTER TABLE CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
     ADD CONSTRAINT FK_CONTENIDO_TEMATICO_CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO
      FOREIGN KEY (FK_CONTENIDO_TEMATICO) REFERENCES CAT_CONTENIDO_TEMATICO_CADO(PK_CONTENIDO_TEMATICO);
/* FIN TABLA PARA TABLA CAT_ARCHIVO_CONTENIDO_TEMATICO_CADO  */

/* INICIO TABLA PARA TABLA CAT_MATERIAL_DIDACTICO_CADO */
CREATE TABLE CAT_MATERIAL_DIDACTICO_CADO(
    PK_MATERIAL_DIDACTICO    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    NOMBRE_MATERIAL                     VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_MATERIAL_DIDACTICO_CADO
    ADD CONSTRAINT PK_MATERIAL_DIDACTICO_CAT_MATERIAL_DIDACTICO_CADO
    PRIMARY KEY (PK_MATERIAL_DIDACTICO ASC);
ALTER TABLE CAT_MATERIAL_DIDACTICO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_MATERIAL_DIDACTICO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_MATERIAL_DIDACTICO_CADO  */

/* INICIO TABLA PARA TABLA CAT_CRITERIO_EVALUACION_CADO */
CREATE TABLE CAT_CRITERIO_EVALUACION_CADO(
    PK_CRITERIO_EVALUACION    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    NOMBRE_CRITERIO             VARCHAR(200)  NOT NULL,
    VALOR_CRITERIO              INT  NOT NULL,
    INSTRUMENTO_DE_EVALUACION    VARCHAR(200)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CRITERIO_EVALUACION_CADO
    ADD CONSTRAINT PK_CRITERIO_EVALUACION_CAT_CRITERIO_EVALUACION_CADO
    PRIMARY KEY (PK_CRITERIO_EVALUACION ASC);
ALTER TABLE CAT_CRITERIO_EVALUACION_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_CRITERIO_EVALUACION_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_CRITERIO_EVALUACION_CADO  */

/* INICIO TABLA PARA TABLA CAT_COMPETENCIAS_CURSO_CADO */
CREATE TABLE CAT_COMPETENCIAS_CURSO_CADO(
    PK_COMPETENCIA_CURSO    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    TEXTO_COMPETENCIA             VARCHAR(500)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_COMPETENCIAS_CURSO_CADO
    ADD CONSTRAINT PK_COMPETENCIA_CURSO_CAT_COMPETENCIAS_CURSO_CADO
    PRIMARY KEY (PK_COMPETENCIA_CURSO ASC);
ALTER TABLE CAT_COMPETENCIAS_CURSO_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_COMPETENCIAS_CURSO_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_COMPETENCIAS_CURSO_CADO  */

/* INICIO TABLA PARA TABLA CAT_FUENTE_INFORMACION_CADO */
CREATE TABLE CAT_FUENTE_INFORMACION_CADO(
    PK_FUENTE_INFORMACION    INT  NOT NULL IDENTITY (1,1),
    FK_FICHA_TECNICA            INT  NOT NULL,-- FK
    TEXTO_FUENTE             VARCHAR(500)  NOT NULL,
               -- DEFAULT IN ALL TABLES ------>
    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);
ALTER TABLE CAT_FUENTE_INFORMACION_CADO
    ADD CONSTRAINT PK_FUENTE_INFORMACION_CAT_FUENTE_INFORMACION_CADO
    PRIMARY KEY (PK_FUENTE_INFORMACION ASC);
ALTER TABLE CAT_FUENTE_INFORMACION_CADO
     ADD CONSTRAINT FK_FICHA_TECNICA_CAT_FUENTE_INFORMACION_CADO
      FOREIGN KEY (FK_FICHA_TECNICA) REFERENCES CAT_FICHA_TECNICA_CADO(PK_CAT_FICHA_TECNICA);
/* FIN TABLA PARA TABLA CAT_FUENTE_INFORMACION_CADO  */


/*************************************************** *
 * ********** FINALIZA LA CREACIÓN DE TABLAS DE CAPACITACION DOCENTE ******** *
 * *************************************************** */


/******************************************************************************************************* *
 * ********** COMIENZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */


-- CREACION DEL SISTEMA
INSERT INTO PER_CAT_SISTEMA(NOMBRE, RUTA_ANGULAR, ABREVIATURA, CORREO1, INDICIO1)
VALUES('Capacitación docente', 'capacitacion', 'CADO', 'cado@itleon.edu.mx', 'cado');

--select * from PER_CAT_SISTEMA;
--se debE asignar el FK_SISTEMA obtenido al realizar el insert anterior
INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (5, 'Coordinador', 'COORD_CADO');

INSERT INTO PER_CAT_ROL(FK_SISTEMA, NOMBRE, ABREVIATURA)
VALUES (5, 'Participante', 'PART_CADO');

--select * from PER_CAT_ROL;

--SE CREAN LOS MODULOS
--INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN)VALUES ('Periodos', 1, 1);
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Periodos',1,1,  'e990c920d0d77fa0937fce0bc4e5a67b' ,  'Lista de periodos intersemestrales'
 ,  'periodos');
 INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Cursos',1,1,  'fdf484eeeb011a5fb52cf33751b4e22f' ,
  'Lista de Cursos de Capacitación' , 'cursos');
INSERT INTO PER_CAT_MODULO(NOMBRE, ESTADO, ORDEN, RUTA_MD5, DESCRIPCION, RUTA)
VALUES ('Captura cursos',1,1,  '7b44125ec5b3b7b61b000cdee93c6796' ,
  'Módulo de Captura' , 'captura_cursos');

--select * from PER_CAT_MODULO

--select * from CAT_USUARIO
-- EL ROL Y EL MODULO SE DEBEN RELACIONAR ACORDE A LAS PK OBTENIDAS CON LOS INSERTS ANTERIORES
-- ROL DE COORDINADOR Y MODULO DE PERIODOS Y CURSOS
-- SELECT * FROM PER_CAT_ROL;
-- SELECT * FROM PER_CAT_MODULO
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (22, 71);
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (22, 72);

-- ROL DE PARTICIPANTE Y MODULO DE CURSOS
INSERT INTO PER_TR_ROL_MODULO(FK_ROL, FK_MODULO)
VALUES (23, 72);

--SELECT * FROM PER_TR_ROL_MODULO
-- INSERT PARA ASIGNAR EL ROL AL USUARIO
INSERT INTO PER_TR_ROL_USUARIO(FK_ROL, FK_USUARIO)
VALUES (22, 1353);

-- SELECT * FROM PER_TR_ROL_USUARIO

-- CREACION DE TIPOS PARTICIPANTES
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( NOMBRE_TIPO, DESCRIPCION)
VALUES('Instructor', 'Personal del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( NOMBRE_TIPO, DESCRIPCION)
VALUES('Participante', 'Personal del ITL que puede inscribirse a los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( NOMBRE_TIPO, DESCRIPCION)
VALUES('Instructor externo', 'Personal externo del ITL que puede impartir uno o más cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( NOMBRE_TIPO, DESCRIPCION)
VALUES('Coordinador', 'Personal del ITL que se encarga de gestionar los cursos de Capacitación Docente');
INSERT INTO CAT_TIPO_PARTICIPANTE_CADO( NOMBRE_TIPO, DESCRIPCION)
VALUES('Jefe Desarrollo Académico', 'Jefe del Departamento de Desarollo Académico');
-- select * from CAT_TIPO_PARTICIPANTE_CADO

-- CREACION DE PARTICIPANTE COORDINADOR
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(4, 1353); -- VALIDAR PK A LA HORA DE IMPLEMENTAR
-- select * from CAT_PARTICIPANTE_CADO
-- CREACION DE PARTICIPANTE JEFE DESARROLLO ACADEMICO
INSERT INTO CAT_PARTICIPANTE_CADO( FK_TIPO_PARTICIPANTE, FK_USUARIO)
VALUES(5, X); -- VALIDAR PK A LA HORA DE IMPLEMENTAR

/******************************************************************************************************* *
 * ********** FINALIZA LA CREACIÓN DEL SISTEMA, LOS MODULOS Y ROLES DEL SISTEMA DE  CAPACITACION DOCENTE ******** *
 * ******************************************************************************************************************** */

