<?php

namespace App\Helpers;

class Abreviaturas
{
    /* ROLES DE TUTORIAS */
    CONST TUTORIA_ROL_ESTUDIANTE      = 'EST_TUT';
    CONST TUTORIA_ROL_TUTOR           = 'TUT_TUT';
    CONST TUTORIA_ROL_COORDINADOR_DEP = 'COORD_TUT';
    CONST TUTORIA_ROL_COORDINADOR_INS = 'COORI_TUT';
    CONST TUTORIA_ROL_ADMINISTRADOR   = 'ADM_TUT';
    CONST TUTORIA_ROL_CAPTURISTA      = 'CAP_TUT';

    CONST CADO_ROL_COORDINADOR         = 'COORD_CADO';
    CONST CADO_ROL_PARTICIPANTE        = 'PART_CADO';
    CONST CADO_ROL_INSTRUCTOR          = 'INST_CADO';
    CONST CADO_ROL_INSTRUCTOR_EXT      = 'EXT_CADO';
    /* ROLES ASPIRANTES */
    CONST ROL_ASPIRANTE = 'ASP';
}
