use SWIITL;

/*********************  INICIO MODIFICACIONES LUNES 15 DE ABRIL 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

-- SE DEFINEN LAS TABLAS DEL ESQUEMA TECNOLÓGICO



DROP TABLE IF EXISTS CAT_TIPO_INSTITUTO;
CREATE TABLE CAT_TIPO_INSTITUTO(
    PK_TIPO_INSTITUTO INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(100),
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);
ALTER TABLE CAT_TIPO_INSTITUTO ADD CONSTRAINT PRK_TIPO_INSTITUTO_CAT_TIPO_INSTITUTO PRIMARY KEY (PK_TIPO_INSTITUTO ASC);

DROP TABLE IF EXISTS CATR_TECNM;
CREATE TABLE CATR_TECNM(
    PK_TECNOLOGICO INT NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR (100),
    ABREVIATURA VARCHAR (50),
    CLAVE VARCHAR (10),
    ID INT,
    FK_TIPO_INSTITUTO INT,
    FK_CODIGO_POSTAL INT,
    FK_USUARIO_REGISTRO INT,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);

ALTER TABLE CATR_TECNM ADD CONSTRAINT PRK_TECNOLOGICO_CATR_TECNM PRIMARY KEY (PK_TECNOLOGICO ASC);
ALTER TABLE CATR_TECNM ADD CONSTRAINT FRK_TIPO_INSTITUTO_CATR_TECNM  FOREIGN KEY (FK_TIPO_INSTITUTO) REFERENCES CAT_TIPO_INSTITUTO (PK_TIPO_INSTITUTO);
ALTER TABLE CATR_TECNM ADD CONSTRAINT FRK_CODIGO_POSTAL_CATR_TECNM FOREIGN KEY (FK_CODIGO_POSTAL) REFERENCES CATR_CODIGO_POSTAL (PK_NUMERO_CODIGO_POSTAL);


DROP TABLE IF EXISTS CAT_TIPO_ESPACIO;
CREATE TABLE CAT_TIPO_ESPACIO(
    PK_TIPO_ESPACIO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);
ALTER TABLE CAT_TIPO_ESPACIO ADD CONSTRAINT PRK_TIPO_ESPACIO_CAT_TIPO_ESPACIO PRIMARY KEY (PK_TIPO_ESPACIO);

DROP TABLE IF EXISTS CATR_CAMPUS;
CREATE TABLE CATR_CAMPUS(
    PK_CAMPUS INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    FK_TECNOLOGICO INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);
ALTER TABLE CATR_CAMPUS ADD CONSTRAINT PRK_CAMPUS_CATR_CAMPUS PRIMARY KEY (PK_CAMPUS);
ALTER TABLE CATR_CAMPUS ADD CONSTRAINT FRK_TECNOLOGICO_CATR_CAMPUS FOREIGN KEY (FK_TECNOLOGICO) REFERENCES CATR_TECNM (PK_TECNOLOGICO);

DROP TABLE IF EXISTS CATR_EDIFICIO;
CREATE TABLE CATR_EDIFICIO(
    PK_EDIFICIO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    PREFIJO VARCHAR (20),
    FK_CAMPUS  INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);
ALTER TABLE CATR_EDIFICIO ADD CONSTRAINT PRK_EDIFICIO_CATR_EDIFICIO PRIMARY KEY (PK_EDIFICIO);
ALTER TABLE CATR_EDIFICIO ADD CONSTRAINT FRK_CAMPUS_CATR_EDIFICIO FOREIGN KEY (FK_CAMPUS) REFERENCES CATR_CAMPUS (PK_CAMPUS);

DROP TABLE IF EXISTS TR_ESPACIO;
CREATE TABLE TR_ESPACIO (
    PK_ESPACIO INT NOT NULL IDENTITY,
    FK_EDIFICIO INT,
    FK_TIPO_ESPACIO INT,
    NOMBRE VARCHAR (100),
    IDENTIFICADOR VARCHAR (50),
    CAPACIDAD INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);
ALTER TABLE TR_ESPACIO ADD CONSTRAINT PRK_ESPACIO_TR_ESPACIO PRIMARY KEY (PK_ESPACIO);
ALTER TABLE TR_ESPACIO ADD CONSTRAINT FRK_EDIFICIO_TR_ESPACIO FOREIGN KEY (FK_EDIFICIO) REFERENCES CATR_EDIFICIO (PK_EDIFICIO);
ALTER TABLE TR_ESPACIO ADD CONSTRAINT FRK_TIPO_ESPACIO_TR_ESPACIO FOREIGN KEY (FK_TIPO_ESPACIO) REFERENCES CAT_TIPO_ESPACIO (PK_TIPO_ESPACIO);

DROP TABLE IF EXISTS CAT_CONVOCATORIA;
CREATE TABLE CAT_CONVOCATORIA (
    PK_CONVOCATORIA INT NOT NULL IDENTITY(1,1),
    NO_CONTROL_CONV INT,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT      NOT NULL DEFAULT 0
);
ALTER TABLE CAT_CONVOCATORIA ADD CONSTRAINT PRK_CONVOCATORIA_CAT_CONVOCATOTIA PRIMARY KEY (PK_CONVOCATORIA);

ALTER TABLE CAT_CONVOCATORIA ADD CAMPUS VARCHAR(10);
/*Agregar el CAMPUS donde sera la convocatoria*/
DROP TABLE IF EXISTS CATR_DATO_CONVOCATORIA;
CREATE TABLE CATR_DATO_CONVOCATORIA(
    PK_DATO_CONVOCATORIA INT NOT NULL IDENTITY(1,1),
    FK_CONVOCATOTIA INT,
    TURNO VARCHAR(10),
    FK_ESPACIO_CONVOCATORIA INT,
    HORARIO_CONVOCATORIA DATETIME NOT NULL,
    FECHA_CONVOCATORIA DATE,
    PERIODO CARCHAR(50),

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT      NOT NULL DEFAULT 0

);

ALTER TABLE CATR_DATO_CONVOCATORIA ADD CONSTRAINT PRK_DATO_CONVOCATORIA_CATR_DATO_CONVOCATORIA PRIMARY KEY (PK_DATO_CONVOCATORIA);
ALTER TABLE CATR_DATO_CONVOCATORIA ADD CONSTRAINT FRK_CONVOCATORIA_CATR_DATO_CONVOCATORIA FOREIGN KEY (FK_CONVOCATOTIA) REFERENCES CAT_CONVOCATORIA (PK_CONVOCATORIA);
ALTER TABLE CATR_DATO_CONVOCATORIA ADD CONSTRAINT FRK_ESPACIO_CONVOCATORIA_CATR_DATO_CONVOCATORIA FOREIGN KEY (FK_ESPACIO_CONVOCATORIA) REFERENCES TR_ESPACIO (PK_ESPACIO);


/*TO DO agregar FECHA_CONVOCATORIA, PERIODO */


/*********************  FIN MODIFICACIONES (RANGO DE FECHA O DÍA) (EJEMPLO LUNES 8 DE ABRIL) *********************************/

-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------

/*
****************ANTIGUO SCRIPT BASE DE DATOS*****************
CREATE TABLE CAT_TIPO_INSTITUTO(
    PK_TIPO_INSTITUTO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR(100)
    PRIMARY KEY (PK_TIPO_INSTITUTO),
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
);


CREATE TABLE CATR_TECNM(
    PK_TECNOLOGICO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    ABREVIATURA VARCHAR (50),
    CLAVE VARCHAR (10),
    ID INT,
    FK_TIPO_INSTITUTO INT,
    FK_CODIGO_POSTAL INT,
    FK_USUARIO_REGISTRO INT,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null   
    PRIMARY KEY (PK_TECNOLOGICO)
    FOREIGN KEY (FK_TIPO_INSTITUTO) REFERENCES CAT_TIPO_INSTITUTO (PK_TIPO_INSTITUTO)
    FOREIGN KEY (FK_CODIGO_POSTAL)  REFERENCES CATR_CODIGO_POSTAL (PK_NUMERO_CODIGO_POSTAL)
);


CREATE TABLE CAT_TIPO_ESPACIO(
    PK_TIPO_ESPACIO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
    PRIMARY KEY (PK_TIPO_ESPACIO)
);


CREATE TABLE CATR_CAMPUS(
    PK_CAMPUS INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    FK_TECNOLOGICO INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
    PRIMARY KEY (PK_CAMPUS)
    FOREIGN KEY (FK_TECNOLOGICO) REFERENCES CATR_TECNM (PK_TECNOLOGICO)
);


CREATE TABLE CATR_EDIFICIO(
    PK_EDIFICIO INT NOT NULL IDENTITY,
    NOMBRE VARCHAR (100),
    PREFIJO VARCHAR (20),
    FK_CAMPUS  INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
    PRIMARY KEY (PK_EDIFICIO)
    FOREIGN KEY (FK_CAMPUS) REFERENCES CATR_CAMPUS (PK_CAMPUS)
);


CREATE TABLE TR_ESPACIO (
    PK_ESPACIO INT NOT NULL IDENTITY,
    FK_EDIFICIO INT,
    FK_TIPO_ESPACIO INT,
    NOMBRE VARCHAR (100),
    IDENTIFICADOR VARCHAR (50),
    CAPACIDAD INT,
    FK_USUARIO_REGISTRO int,
    FECHA_REGISTRO datetime default getdate() not null,
    FK_USUARIO_MODIFICACION int,
    FECHA_MODIFICACION datetime,
    BORRADO nchar(1) default '0' not null
    PRIMARY KEY (PK_ESPACIO)
    FOREIGN KEY (FK_EDIFICIO) REFERENCES CATR_EDIFICIO (PK_EDIFICIO),
    FOREIGN KEY (FK_TIPO_ESPACIO) REFERENCES CAT_TIPO_ESPACIO (PK_TIPO_ESPACIO)
);

*/
