use SWIITL;

/*********************  INICIO MODIFICACIONES LUNES 15 DE ABRIL 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/
-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

-- SCRIPT INICIAL PARA LAS TABLAS DEL ESQUEMA TECNOLÓGICO
INSERT INTO CAT_TIPO_INSTITUTO (NOMBRE) VALUES ('FEDERAL');
INSERT INTO CAT_TIPO_INSTITUTO (NOMBRE) VALUES ('DESCENTRALIZADO');


INSERT INTO CATR_TECNM (NOMBRE,ABREVIATURA,CLAVE,ID,FK_TIPO_INSTITUTO,FK_CODIGO_POSTAL) VALUES ('LEÓN','ITL','11DIT0026P',24,1,37290);
INSERT INTO CATR_TECNM (NOMBRE,ABREVIATURA,CLAVE,ID,FK_TIPO_INSTITUTO,FK_CODIGO_POSTAL) VALUES ('CELAYA','ITC','11DIT0003E',03,1,38010);


INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Aula');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Laboratorio');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Cubículo');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Planta');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Sala');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Centro');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Sanitario');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Oficina');
INSERT INTO CAT_TIPO_ESPACIO(NOMBRE)VALUES('Auditorio');


INSERT INTO CATR_CAMPUS(NOMBRE,FK_TECNOLOGICO) VALUES ('I',1);
INSERT INTO CATR_CAMPUS(NOMBRE,FK_TECNOLOGICO) VALUES ('II',1);
INSERT INTO CATR_CAMPUS(NOMBRE,FK_TECNOLOGICO) VALUES ('I',2);
INSERT INTO CATR_CAMPUS(NOMBRE,FK_TECNOLOGICO) VALUES ('II',2);


INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('A',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('B',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('C',1,'Centro de Cómputo');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('D',1,'Edificio de Sistemas y Computación');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('E',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('F',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('G',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('H',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('I',1,'Centro de Información');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('J',1,'Cafetería');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('K',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('L',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('M',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('N',1,'Departamento de Ciencias Básicas');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('O',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('P',1,'Laboratorio de Química');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('Q',1,'Departamento de Ciencias Económico-Administrativas');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('R',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('S',1,'Planta Piloto');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('T',1,'Laboratorio de Electromecánica');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('U',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('V',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('W',1,'Auditorio');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('X',1,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('Y',1,'Coordinación de Lenguas Extranjeras');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('Z',1,'Gestión Tecnológica y Vinculación');

INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('A',2,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('B',2,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('C',2,'');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('D',2,'Centro de Información');
INSERT INTO CATR_EDIFICIO (PREFIJO,FK_CAMPUS,NOMBRE) VALUES ('E',2,'Cafetería');


INSERT INTO TR_ESPACIO (FK_EDIFICIO,FK_TIPO_ESPACIO,NOMBRE,IDENTIFICADOR,CAPACIDAD) VALUES (3,2,'C1',1,24);
INSERT INTO TR_ESPACIO (FK_EDIFICIO,FK_TIPO_ESPACIO,NOMBRE,IDENTIFICADOR,CAPACIDAD) VALUES (3,2,'Área de Usuarios',1,70);
INSERT INTO TR_ESPACIO (FK_EDIFICIO,FK_TIPO_ESPACIO,NOMBRE,IDENTIFICADOR,CAPACIDAD) VALUES (3,2,'C2',2,13);

/*********************  FIN MODIFICACIONES MARTES 16 DE ABRIL 2019  *********************************/




-- --------------------------------------------------------------------------------------------------------------------------------
