use SWIITL;

/*********************  INICIO MODIFICACIONES MIÉRCOLES 8 DE MAYO 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

-- DDL PARA LAS TABLAS: CAT_ENCUESTA, CATR_SECCION, CAT_TIPO_PREGUNTA, CATR_PREGUNTA, TR_SECCION_PREGUNTA, CATR_RESPUESTA_POSIBLE, TR_APLICACION_ENCUESTA, TR_RESPUESTA_USUARIO_ENCUESTA
CREATE TABLE CAT_ENCUESTA
(
    PK_ENCUESTA             INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_ENCUESTA),

    NOMBRE                  VARCHAR(100)               NOT NULL,
    OBJETIVO                TEXT,
    INSTRUCCIONES           TEXT,
    ES_ADMINISTRABLE        NCHAR(1) NOT NULL DEFAULT '1', -- Sí de administrable

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE CAT_TIPO_PREGUNTA
(
    PK_TIPO_PREGUNTA        INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_TIPO_PREGUNTA),

    NOMBRE_TIPO_PREGUNTA    VARCHAR(100)               NOT NULL,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL

);

CREATE TABLE CATR_SECCION
(
    PK_SECCION              INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_SECCION),
    FK_ENCUESTA             INT,
    FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA),

    NOMBRE_SECCION          VARCHAR(100)               NOT NULL,
    NUMERO_SECCION          INT                        NOT NULL,
    OBJETIVO                TEXT,
    INSTRUCCIONES           TEXT,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL

);

CREATE TABLE CATR_PREGUNTA
(
    PK_PREGUNTA             INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_PREGUNTA),
    FK_TIPO_PREGUNTA        INT,
    FOREIGN KEY (FK_TIPO_PREGUNTA) REFERENCES CAT_TIPO_PREGUNTA (PK_TIPO_PREGUNTA),

    ORDEN                   INT                        NOT NULL,
    PLANTEAMIENTO           VARCHAR(300)               NOT NULL,
    TEXTO_GUIA              VARCHAR(100)               NOT NULL,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE TR_SECCION_PREGUNTA
(
    PK_SECCION_PREGUNTA     INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_SECCION_PREGUNTA),

    FK_SECCION              INT                        NOT NULL,
    FOREIGN KEY (FK_SECCION) REFERENCES CATR_SECCION (PK_SECCION),
    FK_PREGUNTA             INT                        NOT NULL,
    FOREIGN KEY (FK_PREGUNTA) REFERENCES CATR_PREGUNTA (PK_PREGUNTA),

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE CATR_RESPUESTA_POSIBLE
(
    PK_RESPUESTA_POSIBLE    INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_RESPUESTA_POSIBLE),
    FK_PREGUNTA             INT,
    FOREIGN KEY (FK_PREGUNTA) REFERENCES CATR_PREGUNTA (PK_PREGUNTA),

    RESPUESTA               VARCHAR(100),

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE TR_APLICACION_ENCUESTA
(
    PK_APLICACION_ENCUESTA  INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_APLICACION_ENCUESTA),
    FK_USUARIO              INT,
    FOREIGN KEY (FK_USUARIO) REFERENCES users (PK_USUARIO),
    FK_ENCUESTA             INT,
    FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA),

    FECHA_APLICACION        DATETIME,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE TR_RESPUESTA_USUARIO_ENCUESTA
(
    PK_RESPUESTA_USUARIO_ENCUESTA INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_RESPUESTA_USUARIO_ENCUESTA),
    FK_RESPUESTA_POSIBLE          INT,
    FOREIGN KEY (FK_RESPUESTA_POSIBLE) REFERENCES CATR_RESPUESTA_POSIBLE (PK_RESPUESTA_POSIBLE),
    FK_APLICACION_ENCUESTA        INT,
    FOREIGN KEY (FK_APLICACION_ENCUESTA) REFERENCES TR_APLICACION_ENCUESTA (PK_APLICACION_ENCUESTA),

    RESPUESTA_ABIERTA             TEXT,

    FK_USUARIO_REGISTRO           INT,
    FK_USUARIO_MODIFICACION       INT,
    FECHA_REGISTRO                DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION            DATETIME,
    BORRADO                       NCHAR(1) DEFAULT '0'       NOT NULL
);

/*********************  FIN MODIFICACIONES MIÉRCOLES 8 DE MAYO 2019 *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
