use SWIITL;

/*********************  INICIO MODIFICACIONES MIÉRCOLES 8 DE MAYO 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/

-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

-- DDL PARA LAS TABLAS: CAT_ENCUESTA, CATR_SECCION, CAT_TIPO_PREGUNTA, CATR_PREGUNTA, TR_SECCION_PREGUNTA, CATR_RESPUESTA_POSIBLE, TR_APLICACION_ENCUESTA, TR_RESPUESTA_USUARIO_ENCUESTA
/* ****************************************************** *
 * ********** ELIMINACIÓN DE TABLAS DE ENCUESTAS ******** *
 * ****************************************************** */
DROP TABLE IF EXISTS CATR_RESPUESTA_POSIBLE;
DROP TABLE IF EXISTS CATR_PREGUNTA;
DROP TABLE IF EXISTS CAT_TIPO_PREGUNTA;
DROP TABLE IF EXISTS CATR_SECCION;
DROP TABLE IF EXISTS CAT_ENCUESTA;

/* *************************************************** *
 * ********** CREACIÓN DE TABLAS DE ENCUESTAS ******** *
 * *************************************************** */

/* INICIO TABLA PARA ENCUESTAS */
CREATE TABLE CAT_ENCUESTA
(
    PK_ENCUESTA             INT          NOT NULL IDENTITY (1,1),

    NOMBRE                  VARCHAR(100) NOT NULL,
    OBJETIVO                TEXT,
    INSTRUCCIONES           TEXT,
    FUENTE_CITA             TEXT,
    ES_ADMINISTRABLE        SMALLINT     NOT NULL DEFAULT 1, -- Sí de administrable

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CAT_ENCUESTA
    ADD CONSTRAINT PRK_ENCUESTA PRIMARY KEY (PK_ENCUESTA ASC);
/* FIN TABLA PARA ENCUESTAS */

/* INICIO TABLA PARA SECCIONES */
CREATE TABLE CATR_SECCION
(
    PK_SECCION              INT          NOT NULL IDENTITY (1,1),
    FK_ENCUESTA             INT,

    NOMBRE                  VARCHAR(100) NOT NULL,
    NUMERO                  INT          NOT NULL,
    ORDEN                   SMALLINT     NOT NULL DEFAULT 1,
    OBJETIVO                TEXT                  DEFAULT NULL,
    INSTRUCCIONES           TEXT                  DEFAULT NULL,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CATR_SECCION
    ADD CONSTRAINT PRK_SECCION PRIMARY KEY (PK_SECCION ASC);
ALTER TABLE CATR_SECCION
    ADD CONSTRAINT FRK_ENCUESTA FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA)
/* FIN TABLA PARA SECCIONES */

/* INICIO TABLA PARA TIPOS DE PREGUNTA */
CREATE TABLE CAT_TIPO_PREGUNTA
(
    PK_TIPO_PREGUNTA        INT          NOT NULL IDENTITY (1,1),

    NOMBRE_TIPO_PREGUNTA    VARCHAR(100) NOT NULL,

    FK_USUARIO_REGISTRO     INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_USUARIO_MODIFICACION INT,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0,
);

ALTER TABLE CAT_TIPO_PREGUNTA
    ADD CONSTRAINT PRK_TIPO_PREGUNTA PRIMARY KEY (PK_TIPO_PREGUNTA ASC);
/* FIN TABLA PARA TIPOS DE PREGUNTA */

/* INICIO TABLA PARA PREGUNTAS */
CREATE TABLE CATR_PREGUNTA
(
    PK_PREGUNTA             INT          NOT NULL IDENTITY (1,1),
    FK_TIPO_PREGUNTA        INT,
    FK_SECCION        INT,

    ORDEN                   INT          NOT NULL,
    PLANTEAMIENTO           VARCHAR(300) NOT NULL,
    TEXTO_GUIA              VARCHAR(100) NOT NULL,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT     NOT NULL DEFAULT 0
);

ALTER TABLE CATR_PREGUNTA
    ADD CONSTRAINT PRK_PREGUNTA PRIMARY KEY (PK_PREGUNTA ASC);
ALTER TABLE CATR_PREGUNTA
    ADD CONSTRAINT FRK_TIPO_PREGUNTA FOREIGN KEY (FK_TIPO_PREGUNTA) REFERENCES CAT_TIPO_PREGUNTA (PK_TIPO_PREGUNTA);
ALTER TABLE CATR_PREGUNTA
    ADD CONSTRAINT FRK_SECCION FOREIGN KEY (FK_SECCION) REFERENCES CATR_SECCION(PK_SECCION);
/* FIN TABLA PARA PREGUNTAS */

/* INICIO TABLA PARA POSIBLES RESPUESTAS */
CREATE TABLE CATR_RESPUESTA_POSIBLE
(
    PK_RESPUESTA_POSIBLE    INT      NOT NULL IDENTITY (1,1),
    FK_PREGUNTA             INT,

    RESPUESTA               VARCHAR(100),
    VALOR_NUMERICO          INT               DEFAULT NULL,
    ORDEN                   INT               DEFAULT 1,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 SMALLINT NOT NULL DEFAULT 0
);

ALTER TABLE CATR_RESPUESTA_POSIBLE
    ADD CONSTRAINT PRK_RESPUESTA_POSIBLE PRIMARY KEY (PK_RESPUESTA_POSIBLE ASC);
ALTER TABLE CATR_RESPUESTA_POSIBLE
    ADD CONSTRAINT FRK_PREGUNTA FOREIGN KEY (FK_PREGUNTA) REFERENCES CATR_PREGUNTA (PK_PREGUNTA);
/* FIN TABLA PARA POSIBLES RESPUESTAS */

CREATE TABLE TR_APLICACION_ENCUESTA
(
    PK_APLICACION_ENCUESTA  INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_APLICACION_ENCUESTA),
    FK_USUARIO              INT,
    FOREIGN KEY (FK_USUARIO) REFERENCES users (PK_USUARIO),
    FK_ENCUESTA             INT,
    FOREIGN KEY (FK_ENCUESTA) REFERENCES CAT_ENCUESTA (PK_ENCUESTA),

    FECHA_APLICACION        DATETIME,

    FK_USUARIO_REGISTRO     INT,
    FK_USUARIO_MODIFICACION INT,
    FECHA_REGISTRO          DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION      DATETIME,
    BORRADO                 NCHAR(1) DEFAULT '0'       NOT NULL
);

CREATE TABLE TR_RESPUESTA_USUARIO_ENCUESTA
(
    PK_RESPUESTA_USUARIO_ENCUESTA INT                        NOT NULL IDENTITY,
    PRIMARY KEY (PK_RESPUESTA_USUARIO_ENCUESTA),
    FK_RESPUESTA_POSIBLE          INT,
    FOREIGN KEY (FK_RESPUESTA_POSIBLE) REFERENCES CATR_RESPUESTA_POSIBLE (PK_RESPUESTA_POSIBLE),
    FK_APLICACION_ENCUESTA        INT,
    FOREIGN KEY (FK_APLICACION_ENCUESTA) REFERENCES TR_APLICACION_ENCUESTA (PK_APLICACION_ENCUESTA),

    RESPUESTA_ABIERTA             TEXT,

    FK_USUARIO_REGISTRO           INT,
    FK_USUARIO_MODIFICACION       INT,
    FECHA_REGISTRO                DATETIME DEFAULT getdate() NOT NULL,
    FECHA_MODIFICACION            DATETIME,
    BORRADO                       NCHAR(1) DEFAULT '0'       NOT NULL
);

/*********************  FIN MODIFICACIONES MIÉRCOLES 8 DE MAYO 2019 *********************************/


-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------------------------------------------------------------------------
