use SWIITL;

/*********************  INICIO MODIFICACIONES LUNES 8 DE MAYO 2019 *********************************
 * CONTROL DE CAMBIOS EN AMBIENTES
 * LOCAL:      PENDIENTE (FECHA DE APLICACIÓN)
 * PRUEBAS:    PENDIENTE (FECHA DE APLICACIÓN)
 * PRODUCCIÓN: PENDIENTE (FECHA DE APLICACIÓN)
*/
-- AQUÍ SE INDICAN TODOS LOS CAMBIOS QUE SE HAGAN DURANTE EL DÍA O RANGO DE FECHAS

INSERT INTO SWIITL.dbo.CAT_ENCUESTA (NOMBRE, OBJETIVO, INSTRUCCIONES, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('EGRESADO', 'CONTESTAR PREGUNTAS', 'LEE Y CONTESTA CORRECTAMENTE', null, null, '2019-09-04 14:40:14.000', null, '0');
INSERT INTO SWIITL.dbo.CAT_ENCUESTA (NOMBRE, OBJETIVO, INSTRUCCIONES, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('EMPLEADORES', 'CONTESTAR PREGUNTAS', 'LEE Y CONTESTA CORRECTAMENTE', null, null, '2019-09-04 14:41:31.000', null, '0');
INSERT INTO SWIITL.dbo.CAT_ENCUESTA (NOMBRE, OBJETIVO, INSTRUCCIONES, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('LECCIONES', 'CONTESTA LO QUE SE TE PIDE', 'hola', null, null, '2019-09-04 14:41:55.000', null, '0');
INSERT INTO SWIITL.dbo.CAT_ENCUESTA (NOMBRE, OBJETIVO, INSTRUCCIONES, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('ESTUDIANTES', 'CONTESTA LO QUE SE TE PIDE', 'HOLA', null, null, '2019-09-04 14:41:55.000', null, '0');
INSERT INTO SWIITL.dbo.CAT_ENCUESTA (NOMBRE, OBJETIVO, INSTRUCCIONES, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('ASPIRANTES', 'CONTESTA LO QUE SE TE PIDE', 'Adios',  null, null, '2019-09-04 14:41:55.000', null, '0');

INSERT INTO SWIITL.dbo.CATR_SECCION (NOMBRE_SECCION, NUMERO_SECCION, OBJETIVO, INSTRUCCIONES, FK_ENCUESTA, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('DATOS CURRICULARES', 4, 'CONTESTA LAS SIGUIENTES..', 'LEE Y CONTESTA', null, null, null, '2019-09-04 14:40:14.000', null, '0');
INSERT INTO SWIITL.dbo.CATR_SECCION (NOMBRE_SECCION, NUMERO_SECCION, OBJETIVO, INSTRUCCIONES, FK_ENCUESTA, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('DATOS GENERALES', 1, 'CONTESTA LAS SIGUIENTES...', 'LEE Y CONTESTA', null, null, null,'2019-09-04 14:40:14.000', null, '0');
INSERT INTO SWIITL.dbo.CATR_SECCION (NOMBRE_SECCION, NUMERO_SECCION, OBJETIVO, INSTRUCCIONES, FK_ENCUESTA, FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('DATOS PERSONALES', 3, 'CONTESTA LO QUE SE TE PIDE', 'DATOS  PERSONALES', null, null, null, '2019-09-04 14:40:14.000',null, '0');

INSERT INTO SWIITL.dbo.CAT_TIPO_PREGUNTA (NOMBRE_TIPO_PREGUNTA,  FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('DICOTOMICA',  1, null, '2019-05-08 11:29:34.320', null, '0');
INSERT INTO SWIITL.dbo.CAT_TIPO_PREGUNTA (NOMBRE_TIPO_PREGUNTA,  FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('POLITOMICA',  1, null, '2019-05-08 11:29:34.350', null, '0');
INSERT INTO SWIITL.dbo.CAT_TIPO_PREGUNTA (NOMBRE_TIPO_PREGUNTA,  FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('MIXTA',  1, null, '2019-05-08 11:29:34.377', null, '0');
INSERT INTO SWIITL.dbo.CAT_TIPO_PREGUNTA (NOMBRE_TIPO_PREGUNTA,  FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('ESCALA NUMERICA',  1, null, '2019-05-08 11:29:34.400', null, '0');
INSERT INTO SWIITL.dbo.CAT_TIPO_PREGUNTA (NOMBRE_TIPO_PREGUNTA,  FK_USUARIO_REGISTRO, FK_USUARIO_MODIFICACION, FECHA_REGISTRO, FECHA_MODIFICACION, BORRADO) VALUES ('OPCION MULTIPLE',  1, null, '2019-05-08 11:29:34.427', null, '0');



/*********************  FIN MODIFICACIONES MARTES 16 DE ABRIL 2019  *********************************/




-- --------------------------------------------------------------------------------------------------------------------------------
